// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type AllianceRecord struct {
	AllianceID int64  `json:"alliance_id"`
	Payload    string `json:"payload"`
	State      string `json:"state"`
	FetchedAt  string `json:"fetched_at"`
	Priority   int64  `json:"priority"`
}

type Character struct {
	CharacterID  int64          `json:"character_id"`
	UserID       int64          `json:"user_id"`
	Name         string         `json:"name"`
	AccessToken  string         `json:"access_token"`
	RefreshToken string         `json:"refresh_token"`
	TokenExpiry  sql.NullString `json:"token_expiry"`
	Scopes       string         `json:"scopes"`
	CachedUntil  sql.NullString `json:"cached_until"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
	OwnerHash    string         `json:"owner_hash"`
	Tags         string         `json:"tags"`
	LinkState    string         `json:"link_state"`
	LinkStateAt  sql.NullString `json:"link_state_at"`
}

type CharacterCorporation struct {
	CharacterID   int64  `json:"character_id"`
	CorporationID int64  `json:"corporation_id"`
	UpdatedAt     string `json:"updated_at"`
}

type CharacterSnapshot struct {
	CharacterID int64          `json:"character_id"`
	Kind        string         `json:"kind"`
	Payload     string         `json:"payload"`
	FetchedAt   string         `json:"fetched_at"`
	CachedUntil sql.NullString `json:"cached_until"`
}

type ContractDetail struct {
	ContractID  int64  `json:"contract_id"`
	CharacterID int64  `json:"character_id"`
	Payload     string `json:"payload"`
	FetchedAt   string `json:"fetched_at"`
}

type CorporationRecord struct {
	CorporationID int64  `json:"corporation_id"`
	Payload       string `json:"payload"`
	State         string `json:"state"`
	FetchedAt     string `json:"fetched_at"`
	Priority      int64  `json:"priority"`
}

type GlobalSnapshot struct {
	Kind        string `json:"kind"`
	Payload     string `json:"payload"`
	FetchedAt   string `json:"fetched_at"`
	CachedUntil string `json:"cached_until"`
}

type GuidePrice struct {
	TypeID        int64   `json:"type_id"`
	AdjustedPrice float64 `json:"adjusted_price"`
	AveragePrice  float64 `json:"average_price"`
}

type GuidePriceWant struct {
	ID       int64  `json:"id"`
	WantedAt string `json:"wanted_at"`
}

type GuidePricesMetum struct {
	ID          int64  `json:"id"`
	FetchedAt   string `json:"fetched_at"`
	CachedUntil string `json:"cached_until"`
}

type ItemName struct {
	ItemID int64  `json:"item_id"`
	Name   string `json:"name"`
}

type KillmailDetail struct {
	KillmailID  int64  `json:"killmail_id"`
	CharacterID int64  `json:"character_id"`
	Hash        string `json:"hash"`
	Payload     string `json:"payload"`
	FetchedAt   string `json:"fetched_at"`
}

type LocalFitting struct {
	ID         int64  `json:"id"`
	UserID     int64  `json:"user_id"`
	Name       string `json:"name"`
	ShipTypeID int64  `json:"ship_type_id"`
	ItemsJson  string `json:"items_json"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
	IsPublic   bool   `json:"is_public"`
	IsDraft    bool   `json:"is_draft"`
}

type MarketFetchState struct {
	Kind        string `json:"kind"`
	State       string `json:"state"`
	Detail      string `json:"detail"`
	AttemptedAt string `json:"attempted_at"`
}

type MarketHistory struct {
	RegionID   int64   `json:"region_id"`
	TypeID     int64   `json:"type_id"`
	Date       string  `json:"date"`
	Average    float64 `json:"average"`
	Highest    float64 `json:"highest"`
	Lowest     float64 `json:"lowest"`
	Volume     int64   `json:"volume"`
	OrderCount int64   `json:"order_count"`
}

type MarketHistoryWant struct {
	RegionID        int64  `json:"region_id"`
	TypeID          int64  `json:"type_id"`
	LastRequestedAt string `json:"last_requested_at"`
}

type MarketRegionStat struct {
	RegionID       int64   `json:"region_id"`
	TypeID         int64   `json:"type_id"`
	BestSell       float64 `json:"best_sell"`
	TypicalSell    float64 `json:"typical_sell"`
	SellBand       float64 `json:"sell_band"`
	BestBuy        float64 `json:"best_buy"`
	TypicalBuy     float64 `json:"typical_buy"`
	BuyBand        float64 `json:"buy_band"`
	SellOrders     int64   `json:"sell_orders"`
	BuyOrders      int64   `json:"buy_orders"`
	SellVolume     int64   `json:"sell_volume"`
	BuyVolume      int64   `json:"buy_volume"`
	UpdatedAt      string  `json:"updated_at"`
	AvgDailyVolume float64 `json:"avg_daily_volume"`
}

type MarketRegionStatsDaily struct {
	RegionID    int64   `json:"region_id"`
	TypeID      int64   `json:"type_id"`
	Day         string  `json:"day"`
	BestSell    float64 `json:"best_sell"`
	TypicalSell float64 `json:"typical_sell"`
	SellBand    float64 `json:"sell_band"`
	BestBuy     float64 `json:"best_buy"`
	TypicalBuy  float64 `json:"typical_buy"`
	BuyBand     float64 `json:"buy_band"`
	SellOrders  int64   `json:"sell_orders"`
	BuyOrders   int64   `json:"buy_orders"`
	SellVolume  int64   `json:"sell_volume"`
	BuyVolume   int64   `json:"buy_volume"`
}

type MarketStationLeaderboard struct {
	RegionID   int64   `json:"region_id"`
	LocationID int64   `json:"location_id"`
	SellOrders int64   `json:"sell_orders"`
	BuyOrders  int64   `json:"buy_orders"`
	SellValue  float64 `json:"sell_value"`
	BuyValue   float64 `json:"buy_value"`
	UpdatedAt  string  `json:"updated_at"`
}

type MarketStationStat struct {
	LocationID int64   `json:"location_id"`
	RegionID   int64   `json:"region_id"`
	TypeID     int64   `json:"type_id"`
	BestSell   float64 `json:"best_sell"`
	BestBuy    float64 `json:"best_buy"`
	SellOrders int64   `json:"sell_orders"`
	BuyOrders  int64   `json:"buy_orders"`
	SellVolume int64   `json:"sell_volume"`
	BuyVolume  int64   `json:"buy_volume"`
	UpdatedAt  string  `json:"updated_at"`
}

type MarketSweepOrder struct {
	RegionID     int64   `json:"region_id"`
	TypeID       int64   `json:"type_id"`
	IsBuyOrder   int64   `json:"is_buy_order"`
	Price        float64 `json:"price"`
	VolumeRemain int64   `json:"volume_remain"`
	LocationID   int64   `json:"location_id"`
}

type MarketSweepState struct {
	RegionID   int64  `json:"region_id"`
	NextPage   int64  `json:"next_page"`
	PagesTotal int64  `json:"pages_total"`
	StartedAt  string `json:"started_at"`
	UpdatedAt  string `json:"updated_at"`
}

type MarketWatchlist struct {
	UserID       int64   `json:"user_id"`
	TypeID       int64   `json:"type_id"`
	RegionID     int64   `json:"region_id"`
	ThresholdPct float64 `json:"threshold_pct"`
	CreatedAt    string  `json:"created_at"`
}

type OrderHealth struct {
	CharacterID int64   `json:"character_id"`
	OrderID     int64   `json:"order_id"`
	TypeID      int64   `json:"type_id"`
	RegionID    int64   `json:"region_id"`
	LocationID  int64   `json:"location_id"`
	MyPrice     float64 `json:"my_price"`
	StationBest float64 `json:"station_best"`
	RegionBest  float64 `json:"region_best"`
	Status      string  `json:"status"`
	ComputedAt  string  `json:"computed_at"`
}

type OrderLifecycle struct {
	ID               sql.NullInt64 `json:"id"`
	CharacterID      int64         `json:"character_id"`
	OrderID          int64         `json:"order_id"`
	TypeID           int64         `json:"type_id"`
	LocationID       int64         `json:"location_id"`
	RegionID         int64         `json:"region_id"`
	IsBuyOrder       int64         `json:"is_buy_order"`
	ListedPrice      float64       `json:"listed_price"`
	VolumeTotal      int64         `json:"volume_total"`
	VolumeRemainLast int64         `json:"volume_remain_last"`
	FirstSeenAt      string        `json:"first_seen_at"`
	LastSeenAt       string        `json:"last_seen_at"`
	ClosedAt         string        `json:"closed_at"`
	CloseKind        string        `json:"close_kind"`
	OutbidEvents     int64         `json:"outbid_events"`
	BeatenNow        int64         `json:"beaten_now"`
}

type PilotNameWant struct {
	NormalizedName string `json:"normalized_name"`
	DisplayName    string `json:"display_name"`
	State          string `json:"state"`
	CharacterID    int64  `json:"character_id"`
	RequestedAt    string `json:"requested_at"`
	ResolvedAt     string `json:"resolved_at"`
	NextTryAt      string `json:"next_try_at"`
	Attempts       int64  `json:"attempts"`
}

type PilotRecord struct {
	CharacterID int64  `json:"character_id"`
	Payload     string `json:"payload"`
	State       string `json:"state"`
	FetchedAt   string `json:"fetched_at"`
	Priority    int64  `json:"priority"`
}

type PlanetName struct {
	PlanetID   int64  `json:"planet_id"`
	Name       string `json:"name"`
	State      string `json:"state"`
	ResolvedAt string `json:"resolved_at"`
}

type SdeAttributeType struct {
	AttributeID  int64   `json:"attribute_id"`
	Name         string  `json:"name"`
	Stackable    int64   `json:"stackable"`
	HighIsGood   int64   `json:"high_is_good"`
	UnitID       int64   `json:"unit_id"`
	DefaultValue float64 `json:"default_value"`
}

type SdeBlueprint struct {
	BlueprintTypeID          int64 `json:"blueprint_type_id"`
	ProductTypeID            int64 `json:"product_type_id"`
	ProductQuantity          int64 `json:"product_quantity"`
	MaxProductionLimit       int64 `json:"max_production_limit"`
	ManufacturingTimeSeconds int64 `json:"manufacturing_time_seconds"`
}

type SdeBlueprintMaterial struct {
	BlueprintTypeID int64 `json:"blueprint_type_id"`
	MaterialTypeID  int64 `json:"material_type_id"`
	Quantity        int64 `json:"quantity"`
}

type SdeBlueprintSkill struct {
	BlueprintTypeID int64 `json:"blueprint_type_id"`
	SkillTypeID     int64 `json:"skill_type_id"`
	Level           int64 `json:"level"`
}

type SdeCategory struct {
	CategoryID int64  `json:"category_id"`
	Name       string `json:"name"`
}

type SdeEffect struct {
	EffectID int64  `json:"effect_id"`
	Name     string `json:"name"`
	Category int64  `json:"category"`
}

type SdeEffectModifier struct {
	EffectID      int64  `json:"effect_id"`
	Domain        string `json:"domain"`
	Func          string `json:"func"`
	ModifiedAttr  int64  `json:"modified_attr"`
	ModifyingAttr int64  `json:"modifying_attr"`
	Operation     int64  `json:"operation"`
	GroupID       int64  `json:"group_id"`
	SkillTypeID   int64  `json:"skill_type_id"`
}

type SdeGroup struct {
	GroupID    int64  `json:"group_id"`
	Name       string `json:"name"`
	CategoryID int64  `json:"category_id"`
}

type SdeMarketGroup struct {
	MarketGroupID int64  `json:"market_group_id"`
	ParentGroupID int64  `json:"parent_group_id"`
	Name          string `json:"name"`
	IconID        int64  `json:"icon_id"`
	HasTypes      int64  `json:"has_types"`
}

type SdeMetum struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SdeRegion struct {
	RegionID int64  `json:"region_id"`
	Name     string `json:"name"`
}

type SdeRequirement struct {
	TypeID      int64 `json:"type_id"`
	SkillTypeID int64 `json:"skill_type_id"`
	Level       int64 `json:"level"`
}

type SdeSkillMetum struct {
	TypeID        int64   `json:"type_id"`
	Rank          float64 `json:"rank"`
	PrimaryAttr   int64   `json:"primary_attr"`
	SecondaryAttr int64   `json:"secondary_attr"`
}

type SdeStation struct {
	StationID int64  `json:"station_id"`
	Name      string `json:"name"`
	SystemID  int64  `json:"system_id"`
}

type SdeSystem struct {
	SystemID int64   `json:"system_id"`
	Name     string  `json:"name"`
	RegionID int64   `json:"region_id"`
	Security float64 `json:"security"`
}

type SdeType struct {
	TypeID        int64  `json:"type_id"`
	Name          string `json:"name"`
	GroupID       int64  `json:"group_id"`
	MarketGroupID int64  `json:"market_group_id"`
	Published     int64  `json:"published"`
	Description   string `json:"description"`
}

type SdeTypeAttribute struct {
	TypeID      int64   `json:"type_id"`
	AttributeID int64   `json:"attribute_id"`
	Value       float64 `json:"value"`
}

type SdeTypeEffect struct {
	TypeID    int64 `json:"type_id"`
	EffectID  int64 `json:"effect_id"`
	IsDefault int64 `json:"is_default"`
}

type SdeTypePhysic struct {
	TypeID   int64   `json:"type_id"`
	Mass     float64 `json:"mass"`
	Volume   float64 `json:"volume"`
	Capacity float64 `json:"capacity"`
}

type Session struct {
	Token  string    `json:"token"`
	Data   []byte    `json:"data"`
	Expiry time.Time `json:"expiry"`
}

type SkillPlan struct {
	ID          int64  `json:"id"`
	UserID      int64  `json:"user_id"`
	CharacterID int64  `json:"character_id"`
	Name        string `json:"name"`
	CreatedAt   string `json:"created_at"`
}

type SkillPlanItem struct {
	PlanID      int64 `json:"plan_id"`
	SkillTypeID int64 `json:"skill_type_id"`
	TargetLevel int64 `json:"target_level"`
	Position    int64 `json:"position"`
}

type SnapshotFetchState struct {
	CharacterID int64  `json:"character_id"`
	Kind        string `json:"kind"`
	State       string `json:"state"`
	Detail      string `json:"detail"`
	AttemptedAt string `json:"attempted_at"`
}

type StructureContext struct {
	StructureID        int64  `json:"structure_id"`
	OwnerCorporationID int64  `json:"owner_corporation_id"`
	SystemID           int64  `json:"system_id"`
	TypeID             int64  `json:"type_id"`
	UpdatedAt          string `json:"updated_at"`
}

type StructureName struct {
	StructureID int64  `json:"structure_id"`
	Name        string `json:"name"`
	State       string `json:"state"`
	ResolvedAt  string `json:"resolved_at"`
	Source      string `json:"source"`
}

type TypeDetail struct {
	TypeID      int64  `json:"type_id"`
	Description string `json:"description"`
	FetchedAt   string `json:"fetched_at"`
}

type TypeName struct {
	TypeID int64  `json:"type_id"`
	Name   string `json:"name"`
}

type User struct {
	ID             int64  `json:"id"`
	CreatedAt      string `json:"created_at"`
	HomeLayout     string `json:"home_layout"`
	LastBriefingAt string `json:"last_briefing_at"`
}

type WalletHistory struct {
	UserID      int64           `json:"user_id"`
	CharacterID int64           `json:"character_id"`
	Day         string          `json:"day"`
	Balance     float64         `json:"balance"`
	NetWorth    sql.NullFloat64 `json:"net_worth"`
	SampledAt   string          `json:"sampled_at"`
}

type WarDetail struct {
	WarID     int64  `json:"war_id"`
	Payload   string `json:"payload"`
	FetchedAt string `json:"fetched_at"`
}

type WidgetConfig struct {
	UserID    int64  `json:"user_id"`
	WidgetID  string `json:"widget_id"`
	Config    string `json:"config"`
	UpdatedAt string `json:"updated_at"`
}
