// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Character struct {
	CharacterID  int64          `json:"character_id"`
	UserID       int64          `json:"user_id"`
	Name         string         `json:"name"`
	AccessToken  string         `json:"access_token"`
	RefreshToken string         `json:"refresh_token"`
	TokenExpiry  sql.NullString `json:"token_expiry"`
	Scopes       string         `json:"scopes"`
	CachedUntil  sql.NullString `json:"cached_until"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
	OwnerHash    string         `json:"owner_hash"`
	Tags         string         `json:"tags"`
	LinkState    string         `json:"link_state"`
	LinkStateAt  sql.NullString `json:"link_state_at"`
}

type CharacterCorporation struct {
	CharacterID   int64  `json:"character_id"`
	CorporationID int64  `json:"corporation_id"`
	UpdatedAt     string `json:"updated_at"`
}

type CharacterSnapshot struct {
	CharacterID int64          `json:"character_id"`
	Kind        string         `json:"kind"`
	Payload     string         `json:"payload"`
	FetchedAt   string         `json:"fetched_at"`
	CachedUntil sql.NullString `json:"cached_until"`
}

type ContractDetail struct {
	ContractID  int64  `json:"contract_id"`
	CharacterID int64  `json:"character_id"`
	Payload     string `json:"payload"`
	FetchedAt   string `json:"fetched_at"`
}

type GlobalSnapshot struct {
	Kind        string `json:"kind"`
	Payload     string `json:"payload"`
	FetchedAt   string `json:"fetched_at"`
	CachedUntil string `json:"cached_until"`
}

type ItemName struct {
	ItemID int64  `json:"item_id"`
	Name   string `json:"name"`
}

type KillmailDetail struct {
	KillmailID  int64  `json:"killmail_id"`
	CharacterID int64  `json:"character_id"`
	Hash        string `json:"hash"`
	Payload     string `json:"payload"`
	FetchedAt   string `json:"fetched_at"`
}

type MarketFetchState struct {
	Kind        string `json:"kind"`
	State       string `json:"state"`
	Detail      string `json:"detail"`
	AttemptedAt string `json:"attempted_at"`
}

type MarketHistory struct {
	RegionID   int64   `json:"region_id"`
	TypeID     int64   `json:"type_id"`
	Date       string  `json:"date"`
	Average    float64 `json:"average"`
	Highest    float64 `json:"highest"`
	Lowest     float64 `json:"lowest"`
	Volume     int64   `json:"volume"`
	OrderCount int64   `json:"order_count"`
}

type MarketHistoryWant struct {
	RegionID        int64  `json:"region_id"`
	TypeID          int64  `json:"type_id"`
	LastRequestedAt string `json:"last_requested_at"`
}

type MarketWatchlist struct {
	UserID       int64   `json:"user_id"`
	TypeID       int64   `json:"type_id"`
	RegionID     int64   `json:"region_id"`
	ThresholdPct float64 `json:"threshold_pct"`
	CreatedAt    string  `json:"created_at"`
}

type OrderHealth struct {
	CharacterID int64   `json:"character_id"`
	OrderID     int64   `json:"order_id"`
	TypeID      int64   `json:"type_id"`
	RegionID    int64   `json:"region_id"`
	LocationID  int64   `json:"location_id"`
	MyPrice     float64 `json:"my_price"`
	StationBest float64 `json:"station_best"`
	RegionBest  float64 `json:"region_best"`
	Status      string  `json:"status"`
	ComputedAt  string  `json:"computed_at"`
}

type PilotRecord struct {
	CharacterID int64  `json:"character_id"`
	Payload     string `json:"payload"`
	State       string `json:"state"`
	FetchedAt   string `json:"fetched_at"`
}

type SdeBlueprint struct {
	BlueprintTypeID          int64 `json:"blueprint_type_id"`
	ProductTypeID            int64 `json:"product_type_id"`
	ProductQuantity          int64 `json:"product_quantity"`
	MaxProductionLimit       int64 `json:"max_production_limit"`
	ManufacturingTimeSeconds int64 `json:"manufacturing_time_seconds"`
}

type SdeBlueprintMaterial struct {
	BlueprintTypeID int64 `json:"blueprint_type_id"`
	MaterialTypeID  int64 `json:"material_type_id"`
	Quantity        int64 `json:"quantity"`
}

type SdeBlueprintSkill struct {
	BlueprintTypeID int64 `json:"blueprint_type_id"`
	SkillTypeID     int64 `json:"skill_type_id"`
	Level           int64 `json:"level"`
}

type SdeCategory struct {
	CategoryID int64  `json:"category_id"`
	Name       string `json:"name"`
}

type SdeGroup struct {
	GroupID    int64  `json:"group_id"`
	Name       string `json:"name"`
	CategoryID int64  `json:"category_id"`
}

type SdeMetum struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SdeRegion struct {
	RegionID int64  `json:"region_id"`
	Name     string `json:"name"`
}

type SdeRequirement struct {
	TypeID      int64 `json:"type_id"`
	SkillTypeID int64 `json:"skill_type_id"`
	Level       int64 `json:"level"`
}

type SdeSkillMetum struct {
	TypeID        int64   `json:"type_id"`
	Rank          float64 `json:"rank"`
	PrimaryAttr   int64   `json:"primary_attr"`
	SecondaryAttr int64   `json:"secondary_attr"`
}

type SdeStation struct {
	StationID int64  `json:"station_id"`
	Name      string `json:"name"`
	SystemID  int64  `json:"system_id"`
}

type SdeSystem struct {
	SystemID int64   `json:"system_id"`
	Name     string  `json:"name"`
	RegionID int64   `json:"region_id"`
	Security float64 `json:"security"`
}

type SdeType struct {
	TypeID        int64  `json:"type_id"`
	Name          string `json:"name"`
	GroupID       int64  `json:"group_id"`
	MarketGroupID int64  `json:"market_group_id"`
	Published     int64  `json:"published"`
}

type SkillPlan struct {
	ID          int64  `json:"id"`
	UserID      int64  `json:"user_id"`
	CharacterID int64  `json:"character_id"`
	Name        string `json:"name"`
	CreatedAt   string `json:"created_at"`
}

type SkillPlanItem struct {
	PlanID      int64 `json:"plan_id"`
	SkillTypeID int64 `json:"skill_type_id"`
	TargetLevel int64 `json:"target_level"`
	Position    int64 `json:"position"`
}

type SnapshotFetchState struct {
	CharacterID int64  `json:"character_id"`
	Kind        string `json:"kind"`
	State       string `json:"state"`
	Detail      string `json:"detail"`
	AttemptedAt string `json:"attempted_at"`
}

type StructureName struct {
	StructureID int64  `json:"structure_id"`
	Name        string `json:"name"`
	State       string `json:"state"`
	ResolvedAt  string `json:"resolved_at"`
}

type TypeDetail struct {
	TypeID      int64  `json:"type_id"`
	Description string `json:"description"`
	FetchedAt   string `json:"fetched_at"`
}

type TypeName struct {
	TypeID int64  `json:"type_id"`
	Name   string `json:"name"`
}

type User struct {
	ID         int64  `json:"id"`
	CreatedAt  string `json:"created_at"`
	HomeLayout string `json:"home_layout"`
}

type WarDetail struct {
	WarID     int64  `json:"war_id"`
	Payload   string `json:"payload"`
	FetchedAt string `json:"fetched_at"`
}
