// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Character struct {
	CharacterID  int64          `json:"character_id"`
	UserID       int64          `json:"user_id"`
	Name         string         `json:"name"`
	AccessToken  string         `json:"access_token"`
	RefreshToken string         `json:"refresh_token"`
	TokenExpiry  sql.NullString `json:"token_expiry"`
	Scopes       string         `json:"scopes"`
	CachedUntil  sql.NullString `json:"cached_until"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
	OwnerHash    string         `json:"owner_hash"`
	Tags         string         `json:"tags"`
	LinkState    string         `json:"link_state"`
	LinkStateAt  sql.NullString `json:"link_state_at"`
}

type CharacterCorporation struct {
	CharacterID   int64  `json:"character_id"`
	CorporationID int64  `json:"corporation_id"`
	UpdatedAt     string `json:"updated_at"`
}

type CharacterSnapshot struct {
	CharacterID int64          `json:"character_id"`
	Kind        string         `json:"kind"`
	Payload     string         `json:"payload"`
	FetchedAt   string         `json:"fetched_at"`
	CachedUntil sql.NullString `json:"cached_until"`
}

type ContractDetail struct {
	ContractID  int64  `json:"contract_id"`
	CharacterID int64  `json:"character_id"`
	Payload     string `json:"payload"`
	FetchedAt   string `json:"fetched_at"`
}

type GlobalSnapshot struct {
	Kind        string `json:"kind"`
	Payload     string `json:"payload"`
	FetchedAt   string `json:"fetched_at"`
	CachedUntil string `json:"cached_until"`
}

type ItemName struct {
	ItemID int64  `json:"item_id"`
	Name   string `json:"name"`
}

type KillmailDetail struct {
	KillmailID  int64  `json:"killmail_id"`
	CharacterID int64  `json:"character_id"`
	Hash        string `json:"hash"`
	Payload     string `json:"payload"`
	FetchedAt   string `json:"fetched_at"`
}

type SdeCategory struct {
	CategoryID int64  `json:"category_id"`
	Name       string `json:"name"`
}

type SdeGroup struct {
	GroupID    int64  `json:"group_id"`
	Name       string `json:"name"`
	CategoryID int64  `json:"category_id"`
}

type SdeMetum struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SdeRegion struct {
	RegionID int64  `json:"region_id"`
	Name     string `json:"name"`
}

type SdeStation struct {
	StationID int64  `json:"station_id"`
	Name      string `json:"name"`
	SystemID  int64  `json:"system_id"`
}

type SdeSystem struct {
	SystemID int64   `json:"system_id"`
	Name     string  `json:"name"`
	RegionID int64   `json:"region_id"`
	Security float64 `json:"security"`
}

type SdeType struct {
	TypeID        int64  `json:"type_id"`
	Name          string `json:"name"`
	GroupID       int64  `json:"group_id"`
	MarketGroupID int64  `json:"market_group_id"`
	Published     int64  `json:"published"`
}

type SnapshotFetchState struct {
	CharacterID int64  `json:"character_id"`
	Kind        string `json:"kind"`
	State       string `json:"state"`
	Detail      string `json:"detail"`
	AttemptedAt string `json:"attempted_at"`
}

type TypeName struct {
	TypeID int64  `json:"type_id"`
	Name   string `json:"name"`
}

type User struct {
	ID         int64  `json:"id"`
	CreatedAt  string `json:"created_at"`
	HomeLayout string `json:"home_layout"`
}

type WarDetail struct {
	WarID     int64  `json:"war_id"`
	Payload   string `json:"payload"`
	FetchedAt string `json:"fetched_at"`
}
