// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_foresight.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const addForesightTarget = `-- name: AddForesightTarget :execrows

INSERT INTO foresight_targets (user_id, character_id, event_kind, event_key, target_kind, subject_id, region_id, detail, view_key, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT DO NOTHING
`

type AddForesightTargetParams struct {
	UserID      int64     `json:"user_id"`
	CharacterID int64     `json:"character_id"`
	EventKind   string    `json:"event_kind"`
	EventKey    string    `json:"event_key"`
	TargetKind  string    `json:"target_kind"`
	SubjectID   int64     `json:"subject_id"`
	RegionID    int64     `json:"region_id"`
	Detail      string    `json:"detail"`
	ViewKey     string    `json:"view_key"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
}

// ---------------------------------------------------------------------
// Foresight (schema 027): data warmed because of a game event.
// ---------------------------------------------------------------------
// An event is acted on once: the same target for the same event adds
// nothing.
func (q *Queries) AddForesightTarget(ctx context.Context, arg AddForesightTargetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addForesightTarget,
		arg.UserID,
		arg.CharacterID,
		arg.EventKind,
		arg.EventKey,
		arg.TargetKind,
		arg.SubjectID,
		arg.RegionID,
		arg.Detail,
		arg.ViewKey,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countForesightLive = `-- name: CountForesightLive :one
SELECT COUNT(*)::bigint FROM foresight_targets WHERE opened_at IS NULL AND expires_at > $1
`

func (q *Queries) CountForesightLive(ctx context.Context, now time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countForesightLive, now)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listForesightPending = `-- name: ListForesightPending :many
SELECT id, user_id, character_id, event_kind, event_key, target_kind, subject_id, region_id, detail, view_key, created_at, expires_at, warmed_at, calls, opened_at FROM foresight_targets
WHERE warmed_at IS NULL AND expires_at > $1
ORDER BY created_at, id
LIMIT $2::bigint
`

type ListForesightPendingParams struct {
	Now      time.Time `json:"now"`
	RowLimit int64     `json:"row_limit"`
}

func (q *Queries) ListForesightPending(ctx context.Context, arg ListForesightPendingParams) ([]ForesightTarget, error) {
	rows, err := q.db.QueryContext(ctx, listForesightPending, arg.Now, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForesightTarget
	for rows.Next() {
		var i ForesightTarget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CharacterID,
			&i.EventKind,
			&i.EventKey,
			&i.TargetKind,
			&i.SubjectID,
			&i.RegionID,
			&i.Detail,
			&i.ViewKey,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.WarmedAt,
			&i.Calls,
			&i.OpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForesightRates = `-- name: ListForesightRates :many
SELECT event_kind, COUNT(*)::bigint AS resolved, COUNT(opened_at)::bigint AS opened
FROM foresight_targets
WHERE created_at >= $1 AND (opened_at IS NOT NULL OR expires_at <= $2)
GROUP BY event_kind
`

type ListForesightRatesParams struct {
	Since time.Time `json:"since"`
	Now   time.Time `json:"now"`
}

type ListForesightRatesRow struct {
	EventKind string `json:"event_kind"`
	Resolved  int64  `json:"resolved"`
	Opened    int64  `json:"opened"`
}

// How targets that have run their course turned out, by kind of event:
// what the chances are learned from.
func (q *Queries) ListForesightRates(ctx context.Context, arg ListForesightRatesParams) ([]ListForesightRatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listForesightRates, arg.Since, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListForesightRatesRow
	for rows.Next() {
		var i ListForesightRatesRow
		if err := rows.Scan(&i.EventKind, &i.Resolved, &i.Opened); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForesightSummary = `-- name: ListForesightSummary :many
SELECT event_kind,
       COUNT(DISTINCT (user_id, event_key))::bigint AS events,
       COUNT(*)::bigint AS targets,
       COALESCE(SUM(calls), 0)::bigint AS calls,
       COUNT(opened_at)::bigint AS opened,
       COUNT(*) FILTER (WHERE opened_at IS NOT NULL AND warmed_at IS NOT NULL AND warmed_at <= opened_at)::bigint AS opened_warm,
       COUNT(*) FILTER (WHERE opened_at IS NOT NULL OR expires_at <= $1)::bigint AS resolved
FROM foresight_targets
WHERE created_at >= $2
GROUP BY event_kind
ORDER BY event_kind
`

type ListForesightSummaryParams struct {
	Now   time.Time `json:"now"`
	Since time.Time `json:"since"`
}

type ListForesightSummaryRow struct {
	EventKind  string `json:"event_kind"`
	Events     int64  `json:"events"`
	Targets    int64  `json:"targets"`
	Calls      int64  `json:"calls"`
	Opened     int64  `json:"opened"`
	OpenedWarm int64  `json:"opened_warm"`
	Resolved   int64  `json:"resolved"`
}

// The Sync page's table.
func (q *Queries) ListForesightSummary(ctx context.Context, arg ListForesightSummaryParams) ([]ListForesightSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, listForesightSummary, arg.Now, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListForesightSummaryRow
	for rows.Next() {
		var i ListForesightSummaryRow
		if err := rows.Scan(
			&i.EventKind,
			&i.Events,
			&i.Targets,
			&i.Calls,
			&i.Opened,
			&i.OpenedWarm,
			&i.Resolved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForesightUserRates = `-- name: ListForesightUserRates :many
SELECT user_id, event_kind, COUNT(*)::bigint AS resolved, COUNT(opened_at)::bigint AS opened
FROM foresight_targets
WHERE user_id = ANY($1::bigint[])
  AND created_at >= $2 AND (opened_at IS NOT NULL OR expires_at <= $3)
GROUP BY user_id, event_kind
`

type ListForesightUserRatesParams struct {
	UserIds []int64   `json:"user_ids"`
	Since   time.Time `json:"since"`
	Now     time.Time `json:"now"`
}

type ListForesightUserRatesRow struct {
	UserID    int64  `json:"user_id"`
	EventKind string `json:"event_kind"`
	Resolved  int64  `json:"resolved"`
	Opened    int64  `json:"opened"`
}

// The same for some accounts, each on its own.
func (q *Queries) ListForesightUserRates(ctx context.Context, arg ListForesightUserRatesParams) ([]ListForesightUserRatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listForesightUserRates, pq.Array(arg.UserIds), arg.Since, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListForesightUserRatesRow
	for rows.Next() {
		var i ListForesightUserRatesRow
		if err := rows.Scan(
			&i.UserID,
			&i.EventKind,
			&i.Resolved,
			&i.Opened,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersInCorporations = `-- name: ListUsersInCorporations :many
SELECT DISTINCT c.user_id, cc.corporation_id
FROM characters c
JOIN character_corporations cc ON cc.character_id = c.character_id
WHERE cc.corporation_id = ANY($1::bigint[])
`

type ListUsersInCorporationsRow struct {
	UserID        int64 `json:"user_id"`
	CorporationID int64 `json:"corporation_id"`
}

// The accounts with a character in one of some corporations.
func (q *Queries) ListUsersInCorporations(ctx context.Context, corporationIds []int64) ([]ListUsersInCorporationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersInCorporations, pq.Array(corporationIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersInCorporationsRow
	for rows.Next() {
		var i ListUsersInCorporationsRow
		if err := rows.Scan(&i.UserID, &i.CorporationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarsDeclaredSince = `-- name: ListWarsDeclaredSince :many
SELECT war_id, payload FROM war_details
WHERE (payload::jsonb ->> 'declared')::timestamptz >= $1::timestamptz
ORDER BY war_id DESC
LIMIT $2::bigint
`

type ListWarsDeclaredSinceParams struct {
	Since    time.Time `json:"since"`
	RowLimit int64     `json:"row_limit"`
}

type ListWarsDeclaredSinceRow struct {
	WarID   int64  `json:"war_id"`
	Payload string `json:"payload"`
}

// Wars declared since a date, as stored.
func (q *Queries) ListWarsDeclaredSince(ctx context.Context, arg ListWarsDeclaredSinceParams) ([]ListWarsDeclaredSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listWarsDeclaredSince, arg.Since, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWarsDeclaredSinceRow
	for rows.Next() {
		var i ListWarsDeclaredSinceRow
		if err := rows.Scan(&i.WarID, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markForesightOpened = `-- name: MarkForesightOpened :execrows
UPDATE foresight_targets SET opened_at = $1
WHERE user_id = $2 AND view_key = $3
  AND opened_at IS NULL AND expires_at > $1
`

type MarkForesightOpenedParams struct {
	OpenedAt sql.NullTime `json:"opened_at"`
	UserID   int64        `json:"user_id"`
	ViewKey  string       `json:"view_key"`
}

// The account opened the page a target was warmed for.
func (q *Queries) MarkForesightOpened(ctx context.Context, arg MarkForesightOpenedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markForesightOpened, arg.OpenedAt, arg.UserID, arg.ViewKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markForesightWarmed = `-- name: MarkForesightWarmed :exec
UPDATE foresight_targets SET warmed_at = $1, calls = $2 WHERE id = $3
`

type MarkForesightWarmedParams struct {
	WarmedAt sql.NullTime `json:"warmed_at"`
	Calls    int64        `json:"calls"`
	ID       int64        `json:"id"`
}

func (q *Queries) MarkForesightWarmed(ctx context.Context, arg MarkForesightWarmedParams) error {
	_, err := q.db.ExecContext(ctx, markForesightWarmed, arg.WarmedAt, arg.Calls, arg.ID)
	return err
}

const pruneForesightTargets = `-- name: PruneForesightTargets :exec
DELETE FROM foresight_targets WHERE created_at < $1
`

func (q *Queries) PruneForesightTargets(ctx context.Context, before time.Time) error {
	_, err := q.db.ExecContext(ctx, pruneForesightTargets, before)
	return err
}
