// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const countSDECategories = `-- name: CountSDECategories :one
SELECT COUNT(*) FROM sde_categories
`

func (q *Queries) CountSDECategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSDECategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSDEGroups = `-- name: CountSDEGroups :one
SELECT COUNT(*) FROM sde_groups
`

func (q *Queries) CountSDEGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSDEGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSDERegions = `-- name: CountSDERegions :one
SELECT COUNT(*) FROM sde_regions
`

func (q *Queries) CountSDERegions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSDERegions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSDEStations = `-- name: CountSDEStations :one
SELECT COUNT(*) FROM sde_stations
`

func (q *Queries) CountSDEStations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSDEStations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSDESystems = `-- name: CountSDESystems :one
SELECT COUNT(*) FROM sde_systems
`

func (q *Queries) CountSDESystems(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSDESystems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSDETypes = `-- name: CountSDETypes :one
SELECT COUNT(*) FROM sde_types
`

func (q *Queries) CountSDETypes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSDETypes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSDETypesInGroupFiltered = `-- name: CountSDETypesInGroupFiltered :one
SELECT COUNT(*) FROM sde_types
WHERE group_id = ? AND instr(lower(name), lower(?)) > 0
`

type CountSDETypesInGroupFilteredParams struct {
	GroupID int64  `json:"group_id"`
	LOWER   string `json:"LOWER"`
}

func (q *Queries) CountSDETypesInGroupFiltered(ctx context.Context, arg CountSDETypesInGroupFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSDETypesInGroupFiltered, arg.GroupID, arg.LOWER)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWarDetails = `-- name: CountWarDetails :one
SELECT COUNT(*) FROM war_details
`

func (q *Queries) CountWarDetails(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWarDetails)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (created_at)
VALUES (datetime('now'))
RETURNING id, created_at, home_layout
`

func (q *Queries) CreateUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser)
	var i User
	err := row.Scan(&i.ID, &i.CreatedAt, &i.HomeLayout)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters
WHERE character_id = ? AND user_id = ?
`

type DeleteCharacterParams struct {
	CharacterID int64 `json:"character_id"`
	UserID      int64 `json:"user_id"`
}

func (q *Queries) DeleteCharacter(ctx context.Context, arg DeleteCharacterParams) error {
	_, err := q.db.ExecContext(ctx, deleteCharacter, arg.CharacterID, arg.UserID)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT character_id, user_id, name, access_token, refresh_token, token_expiry, scopes, cached_until, created_at, updated_at, owner_hash, tags, link_state, link_state_at FROM characters
WHERE character_id = ?
`

func (q *Queries) GetCharacter(ctx context.Context, characterID int64) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, characterID)
	var i Character
	err := row.Scan(
		&i.CharacterID,
		&i.UserID,
		&i.Name,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.Scopes,
		&i.CachedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerHash,
		&i.Tags,
		&i.LinkState,
		&i.LinkStateAt,
	)
	return i, err
}

const getCharacterCorporation = `-- name: GetCharacterCorporation :one
SELECT character_id, corporation_id, updated_at FROM character_corporations
WHERE character_id = ?
`

func (q *Queries) GetCharacterCorporation(ctx context.Context, characterID int64) (CharacterCorporation, error) {
	row := q.db.QueryRowContext(ctx, getCharacterCorporation, characterID)
	var i CharacterCorporation
	err := row.Scan(&i.CharacterID, &i.CorporationID, &i.UpdatedAt)
	return i, err
}

const getContractDetail = `-- name: GetContractDetail :one

SELECT contract_id, character_id, payload, fetched_at FROM contract_details
WHERE contract_id = ?
`

// ---------------------------------------------------------------------
// Module sweep, cluster 3 (schema 006): contract detail store. The
// worker warms contract item lists from the contracts snapshot;
// pages only read here.
// ---------------------------------------------------------------------
func (q *Queries) GetContractDetail(ctx context.Context, contractID int64) (ContractDetail, error) {
	row := q.db.QueryRowContext(ctx, getContractDetail, contractID)
	var i ContractDetail
	err := row.Scan(
		&i.ContractID,
		&i.CharacterID,
		&i.Payload,
		&i.FetchedAt,
	)
	return i, err
}

const getGlobalSnapshot = `-- name: GetGlobalSnapshot :one

SELECT kind, payload, fetched_at, cached_until FROM global_snapshots
WHERE kind = ?
`

// ---------------------------------------------------------------------
// Module sweep, cluster 4 (schema 007): intel public-data store.
// Global snapshots are the public-data counterpart of
// character_snapshots; war details mirror killmail_details.
// ---------------------------------------------------------------------
func (q *Queries) GetGlobalSnapshot(ctx context.Context, kind string) (GlobalSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getGlobalSnapshot, kind)
	var i GlobalSnapshot
	err := row.Scan(
		&i.Kind,
		&i.Payload,
		&i.FetchedAt,
		&i.CachedUntil,
	)
	return i, err
}

const getItemName = `-- name: GetItemName :one
SELECT name FROM item_names
WHERE item_id = ?
`

func (q *Queries) GetItemName(ctx context.Context, itemID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getItemName, itemID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getKillmailDetail = `-- name: GetKillmailDetail :one

SELECT killmail_id, character_id, hash, payload, fetched_at FROM killmail_details
WHERE killmail_id = ?
`

// ---------------------------------------------------------------------
// Module sweep (schema 004): killmail detail store. The worker warms
// details from the recent-killmails snapshot; pages only read here.
// ---------------------------------------------------------------------
func (q *Queries) GetKillmailDetail(ctx context.Context, killmailID int64) (KillmailDetail, error) {
	row := q.db.QueryRowContext(ctx, getKillmailDetail, killmailID)
	var i KillmailDetail
	err := row.Scan(
		&i.KillmailID,
		&i.CharacterID,
		&i.Hash,
		&i.Payload,
		&i.FetchedAt,
	)
	return i, err
}

const getSDECategory = `-- name: GetSDECategory :one
SELECT category_id, name FROM sde_categories
WHERE category_id = ?
`

func (q *Queries) GetSDECategory(ctx context.Context, categoryID int64) (SdeCategory, error) {
	row := q.db.QueryRowContext(ctx, getSDECategory, categoryID)
	var i SdeCategory
	err := row.Scan(&i.CategoryID, &i.Name)
	return i, err
}

const getSDEGroup = `-- name: GetSDEGroup :one
SELECT group_id, name, category_id FROM sde_groups
WHERE group_id = ?
`

func (q *Queries) GetSDEGroup(ctx context.Context, groupID int64) (SdeGroup, error) {
	row := q.db.QueryRowContext(ctx, getSDEGroup, groupID)
	var i SdeGroup
	err := row.Scan(&i.GroupID, &i.Name, &i.CategoryID)
	return i, err
}

const getSDEMeta = `-- name: GetSDEMeta :one
SELECT value FROM sde_meta
WHERE key = ?
`

func (q *Queries) GetSDEMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSDEMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getSDERegion = `-- name: GetSDERegion :one
SELECT region_id, name FROM sde_regions
WHERE region_id = ?
`

func (q *Queries) GetSDERegion(ctx context.Context, regionID int64) (SdeRegion, error) {
	row := q.db.QueryRowContext(ctx, getSDERegion, regionID)
	var i SdeRegion
	err := row.Scan(&i.RegionID, &i.Name)
	return i, err
}

const getSDEStation = `-- name: GetSDEStation :one
SELECT station_id, name, system_id FROM sde_stations
WHERE station_id = ?
`

func (q *Queries) GetSDEStation(ctx context.Context, stationID int64) (SdeStation, error) {
	row := q.db.QueryRowContext(ctx, getSDEStation, stationID)
	var i SdeStation
	err := row.Scan(&i.StationID, &i.Name, &i.SystemID)
	return i, err
}

const getSDESystem = `-- name: GetSDESystem :one
SELECT system_id, name, region_id, security FROM sde_systems
WHERE system_id = ?
`

func (q *Queries) GetSDESystem(ctx context.Context, systemID int64) (SdeSystem, error) {
	row := q.db.QueryRowContext(ctx, getSDESystem, systemID)
	var i SdeSystem
	err := row.Scan(
		&i.SystemID,
		&i.Name,
		&i.RegionID,
		&i.Security,
	)
	return i, err
}

const getSDEType = `-- name: GetSDEType :one

SELECT type_id, name, group_id, market_group_id, published FROM sde_types
WHERE type_id = ?
`

// ---------------------------------------------------------------------
// SDE static data (schema 003): lookup getters, search, counts, meta.
// Bulk import inserts are hand-rolled prepared statements inside one
// transaction in the importer (internal/app/sde.go); reads stay sqlc.
// ---------------------------------------------------------------------
func (q *Queries) GetSDEType(ctx context.Context, typeID int64) (SdeType, error) {
	row := q.db.QueryRowContext(ctx, getSDEType, typeID)
	var i SdeType
	err := row.Scan(
		&i.TypeID,
		&i.Name,
		&i.GroupID,
		&i.MarketGroupID,
		&i.Published,
	)
	return i, err
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT character_id, kind, payload, fetched_at, cached_until FROM character_snapshots
WHERE character_id = ? AND kind = ?
`

type GetSnapshotParams struct {
	CharacterID int64  `json:"character_id"`
	Kind        string `json:"kind"`
}

func (q *Queries) GetSnapshot(ctx context.Context, arg GetSnapshotParams) (CharacterSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshot, arg.CharacterID, arg.Kind)
	var i CharacterSnapshot
	err := row.Scan(
		&i.CharacterID,
		&i.Kind,
		&i.Payload,
		&i.FetchedAt,
		&i.CachedUntil,
	)
	return i, err
}

const getSnapshotFetchState = `-- name: GetSnapshotFetchState :one

SELECT character_id, kind, state, detail, attempted_at FROM snapshot_fetch_state
WHERE character_id = ? AND kind = ?
`

type GetSnapshotFetchStateParams struct {
	CharacterID int64  `json:"character_id"`
	Kind        string `json:"kind"`
}

// ---------------------------------------------------------------------
// Module sweep, cluster 2 (schema 005): corporation support.
// Fetch-outcome log (role-missing state), character-to-corporation
// map, and player-given item names.
// ---------------------------------------------------------------------
func (q *Queries) GetSnapshotFetchState(ctx context.Context, arg GetSnapshotFetchStateParams) (SnapshotFetchState, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotFetchState, arg.CharacterID, arg.Kind)
	var i SnapshotFetchState
	err := row.Scan(
		&i.CharacterID,
		&i.Kind,
		&i.State,
		&i.Detail,
		&i.AttemptedAt,
	)
	return i, err
}

const getTypeName = `-- name: GetTypeName :one
SELECT name FROM type_names
WHERE type_id = ?
`

func (q *Queries) GetTypeName(ctx context.Context, typeID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getTypeName, typeID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, home_layout FROM users
WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.CreatedAt, &i.HomeLayout)
	return i, err
}

const getUserHomeLayout = `-- name: GetUserHomeLayout :one

SELECT home_layout FROM users
WHERE id = ?
`

// ---------------------------------------------------------------------
// Phase 1B home overview (schema 010): per-account widget layout and
// the one batched snapshot read every widget renders from.
// ---------------------------------------------------------------------
func (q *Queries) GetUserHomeLayout(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserHomeLayout, id)
	var home_layout string
	err := row.Scan(&home_layout)
	return home_layout, err
}

const getWarDetail = `-- name: GetWarDetail :one
SELECT war_id, payload, fetched_at FROM war_details
WHERE war_id = ?
`

func (q *Queries) GetWarDetail(ctx context.Context, warID int64) (WarDetail, error) {
	row := q.db.QueryRowContext(ctx, getWarDetail, warID)
	var i WarDetail
	err := row.Scan(&i.WarID, &i.Payload, &i.FetchedAt)
	return i, err
}

const listAllCharacters = `-- name: ListAllCharacters :many
SELECT character_id, user_id, name, access_token, refresh_token, token_expiry, scopes, cached_until, created_at, updated_at, owner_hash, tags, link_state, link_state_at FROM characters
ORDER BY user_id, name
`

func (q *Queries) ListAllCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listAllCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.CharacterID,
			&i.UserID,
			&i.Name,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiry,
			&i.Scopes,
			&i.CachedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerHash,
			&i.Tags,
			&i.LinkState,
			&i.LinkStateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCorporationIDs = `-- name: ListAllCorporationIDs :many
SELECT DISTINCT corporation_id FROM character_corporations
ORDER BY corporation_id
`

func (q *Queries) ListAllCorporationIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listAllCorporationIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var corporation_id int64
		if err := rows.Scan(&corporation_id); err != nil {
			return nil, err
		}
		items = append(items, corporation_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTypeNames = `-- name: ListAllTypeNames :many
SELECT type_id, name FROM type_names
ORDER BY type_id
`

func (q *Queries) ListAllTypeNames(ctx context.Context) ([]TypeName, error) {
	rows, err := q.db.QueryContext(ctx, listAllTypeNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TypeName
	for rows.Next() {
		var i TypeName
		if err := rows.Scan(&i.TypeID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersByUser = `-- name: ListCharactersByUser :many
SELECT character_id, user_id, name, access_token, refresh_token, token_expiry, scopes, cached_until, created_at, updated_at, owner_hash, tags, link_state, link_state_at FROM characters
WHERE user_id = ?
ORDER BY name
`

func (q *Queries) ListCharactersByUser(ctx context.Context, userID int64) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listCharactersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.CharacterID,
			&i.UserID,
			&i.Name,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiry,
			&i.Scopes,
			&i.CachedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerHash,
			&i.Tags,
			&i.LinkState,
			&i.LinkStateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractDetailIDsByCharacter = `-- name: ListContractDetailIDsByCharacter :many
SELECT contract_id FROM contract_details
WHERE character_id = ?
ORDER BY contract_id
`

func (q *Queries) ListContractDetailIDsByCharacter(ctx context.Context, characterID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listContractDetailIDsByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var contract_id int64
		if err := rows.Scan(&contract_id); err != nil {
			return nil, err
		}
		items = append(items, contract_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalSnapshots = `-- name: ListGlobalSnapshots :many
SELECT kind, payload, fetched_at, cached_until FROM global_snapshots
ORDER BY kind
`

func (q *Queries) ListGlobalSnapshots(ctx context.Context) ([]GlobalSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalSnapshot
	for rows.Next() {
		var i GlobalSnapshot
		if err := rows.Scan(
			&i.Kind,
			&i.Payload,
			&i.FetchedAt,
			&i.CachedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemNames = `-- name: ListItemNames :many
SELECT item_id, name FROM item_names
ORDER BY item_id
`

func (q *Queries) ListItemNames(ctx context.Context) ([]ItemName, error) {
	rows, err := q.db.QueryContext(ctx, listItemNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemName
	for rows.Next() {
		var i ItemName
		if err := rows.Scan(&i.ItemID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKillmailDetailIDsByCharacter = `-- name: ListKillmailDetailIDsByCharacter :many
SELECT killmail_id FROM killmail_details
WHERE character_id = ?
ORDER BY killmail_id
`

func (q *Queries) ListKillmailDetailIDsByCharacter(ctx context.Context, characterID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listKillmailDetailIDsByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var killmail_id int64
		if err := rows.Scan(&killmail_id); err != nil {
			return nil, err
		}
		items = append(items, killmail_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKillmailDetailsByCharacter = `-- name: ListKillmailDetailsByCharacter :many
SELECT killmail_id, character_id, hash, payload, fetched_at FROM killmail_details
WHERE character_id = ?
ORDER BY killmail_id
`

func (q *Queries) ListKillmailDetailsByCharacter(ctx context.Context, characterID int64) ([]KillmailDetail, error) {
	rows, err := q.db.QueryContext(ctx, listKillmailDetailsByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KillmailDetail
	for rows.Next() {
		var i KillmailDetail
		if err := rows.Scan(
			&i.KillmailID,
			&i.CharacterID,
			&i.Hash,
			&i.Payload,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanetLayoutsForUser = `-- name: ListPlanetLayoutsForUser :many
SELECT s.character_id, s.kind, s.payload, s.fetched_at
FROM character_snapshots s
JOIN characters c ON c.character_id = s.character_id
WHERE c.user_id = ? AND instr(s.kind, 'planet_layout_') = 1
ORDER BY s.character_id, s.kind
`

type ListPlanetLayoutsForUserRow struct {
	CharacterID int64  `json:"character_id"`
	Kind        string `json:"kind"`
	Payload     string `json:"payload"`
	FetchedAt   string `json:"fetched_at"`
}

func (q *Queries) ListPlanetLayoutsForUser(ctx context.Context, userID int64) ([]ListPlanetLayoutsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlanetLayoutsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlanetLayoutsForUserRow
	for rows.Next() {
		var i ListPlanetLayoutsForUserRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.Kind,
			&i.Payload,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSDECategoriesWithCounts = `-- name: ListSDECategoriesWithCounts :many
SELECT c.category_id, c.name, COUNT(t.type_id) AS type_count
FROM sde_categories c
LEFT JOIN sde_groups g ON g.category_id = c.category_id
LEFT JOIN sde_types t ON t.group_id = g.group_id
GROUP BY c.category_id, c.name
ORDER BY c.name
`

type ListSDECategoriesWithCountsRow struct {
	CategoryID int64  `json:"category_id"`
	Name       string `json:"name"`
	TypeCount  int64  `json:"type_count"`
}

func (q *Queries) ListSDECategoriesWithCounts(ctx context.Context) ([]ListSDECategoriesWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSDECategoriesWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSDECategoriesWithCountsRow
	for rows.Next() {
		var i ListSDECategoriesWithCountsRow
		if err := rows.Scan(&i.CategoryID, &i.Name, &i.TypeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSDEGroupsInCategory = `-- name: ListSDEGroupsInCategory :many
SELECT g.group_id, g.name, COUNT(t.type_id) AS type_count
FROM sde_groups g
LEFT JOIN sde_types t ON t.group_id = g.group_id
WHERE g.category_id = ?
GROUP BY g.group_id, g.name
ORDER BY g.name
`

type ListSDEGroupsInCategoryRow struct {
	GroupID   int64  `json:"group_id"`
	Name      string `json:"name"`
	TypeCount int64  `json:"type_count"`
}

func (q *Queries) ListSDEGroupsInCategory(ctx context.Context, categoryID int64) ([]ListSDEGroupsInCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listSDEGroupsInCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSDEGroupsInCategoryRow
	for rows.Next() {
		var i ListSDEGroupsInCategoryRow
		if err := rows.Scan(&i.GroupID, &i.Name, &i.TypeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSDETypeIDs = `-- name: ListSDETypeIDs :many
SELECT type_id FROM sde_types
ORDER BY type_id
`

func (q *Queries) ListSDETypeIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listSDETypeIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var type_id int64
		if err := rows.Scan(&type_id); err != nil {
			return nil, err
		}
		items = append(items, type_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSDETypesInGroup = `-- name: ListSDETypesInGroup :many
SELECT type_id, name, market_group_id FROM sde_types
WHERE group_id = ? AND instr(lower(name), lower(?)) > 0
ORDER BY name
LIMIT ? OFFSET ?
`

type ListSDETypesInGroupParams struct {
	GroupID int64  `json:"group_id"`
	LOWER   string `json:"LOWER"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

type ListSDETypesInGroupRow struct {
	TypeID        int64  `json:"type_id"`
	Name          string `json:"name"`
	MarketGroupID int64  `json:"market_group_id"`
}

func (q *Queries) ListSDETypesInGroup(ctx context.Context, arg ListSDETypesInGroupParams) ([]ListSDETypesInGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, listSDETypesInGroup,
		arg.GroupID,
		arg.LOWER,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSDETypesInGroupRow
	for rows.Next() {
		var i ListSDETypesInGroupRow
		if err := rows.Scan(&i.TypeID, &i.Name, &i.MarketGroupID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotFetchStatesByCharacter = `-- name: ListSnapshotFetchStatesByCharacter :many
SELECT character_id, kind, state, detail, attempted_at FROM snapshot_fetch_state
WHERE character_id = ?
ORDER BY kind
`

func (q *Queries) ListSnapshotFetchStatesByCharacter(ctx context.Context, characterID int64) ([]SnapshotFetchState, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotFetchStatesByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotFetchState
	for rows.Next() {
		var i SnapshotFetchState
		if err := rows.Scan(
			&i.CharacterID,
			&i.Kind,
			&i.State,
			&i.Detail,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByCharacter = `-- name: ListSnapshotsByCharacter :many
SELECT character_id, kind, payload, fetched_at, cached_until FROM character_snapshots
WHERE character_id = ?
ORDER BY kind
`

func (q *Queries) ListSnapshotsByCharacter(ctx context.Context, characterID int64) ([]CharacterSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterSnapshot
	for rows.Next() {
		var i CharacterSnapshot
		if err := rows.Scan(
			&i.CharacterID,
			&i.Kind,
			&i.Payload,
			&i.FetchedAt,
			&i.CachedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsForUser = `-- name: ListSnapshotsForUser :many
SELECT s.character_id, s.kind, s.payload, s.fetched_at, s.cached_until
FROM character_snapshots s
JOIN characters c ON c.character_id = s.character_id
WHERE c.user_id = ? AND s.kind IN (/*SLICE:kinds*/?)
ORDER BY s.character_id, s.kind
`

type ListSnapshotsForUserParams struct {
	UserID int64    `json:"user_id"`
	Kinds  []string `json:"kinds"`
}

func (q *Queries) ListSnapshotsForUser(ctx context.Context, arg ListSnapshotsForUserParams) ([]CharacterSnapshot, error) {
	query := listSnapshotsForUser
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.Kinds) > 0 {
		for _, v := range arg.Kinds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:kinds*/?", strings.Repeat(",?", len(arg.Kinds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:kinds*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterSnapshot
	for rows.Next() {
		var i CharacterSnapshot
		if err := rows.Scan(
			&i.CharacterID,
			&i.Kind,
			&i.Payload,
			&i.FetchedAt,
			&i.CachedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, created_at, home_layout FROM users
ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.HomeLayout); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSDETypes = `-- name: SearchSDETypes :many
SELECT type_id, name FROM sde_types
WHERE name LIKE ?
ORDER BY name
LIMIT 20
`

type SearchSDETypesRow struct {
	TypeID int64  `json:"type_id"`
	Name   string `json:"name"`
}

func (q *Queries) SearchSDETypes(ctx context.Context, name string) ([]SearchSDETypesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchSDETypes, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSDETypesRow
	for rows.Next() {
		var i SearchSDETypesRow
		if err := rows.Scan(&i.TypeID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTypeNames = `-- name: SearchTypeNames :many
SELECT type_id, name FROM type_names
WHERE name LIKE ?
ORDER BY name
LIMIT 20
`

func (q *Queries) SearchTypeNames(ctx context.Context, name string) ([]TypeName, error) {
	rows, err := q.db.QueryContext(ctx, searchTypeNames, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TypeName
	for rows.Next() {
		var i TypeName
		if err := rows.Scan(&i.TypeID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCharacterLinkState = `-- name: SetCharacterLinkState :exec
UPDATE characters
SET link_state = ?, link_state_at = ?, updated_at = datetime('now')
WHERE character_id = ?
`

type SetCharacterLinkStateParams struct {
	LinkState   string         `json:"link_state"`
	LinkStateAt sql.NullString `json:"link_state_at"`
	CharacterID int64          `json:"character_id"`
}

func (q *Queries) SetCharacterLinkState(ctx context.Context, arg SetCharacterLinkStateParams) error {
	_, err := q.db.ExecContext(ctx, setCharacterLinkState, arg.LinkState, arg.LinkStateAt, arg.CharacterID)
	return err
}

const setCharacterTags = `-- name: SetCharacterTags :exec
UPDATE characters
SET tags = ?, updated_at = datetime('now')
WHERE character_id = ? AND user_id = ?
`

type SetCharacterTagsParams struct {
	Tags        string `json:"tags"`
	CharacterID int64  `json:"character_id"`
	UserID      int64  `json:"user_id"`
}

func (q *Queries) SetCharacterTags(ctx context.Context, arg SetCharacterTagsParams) error {
	_, err := q.db.ExecContext(ctx, setCharacterTags, arg.Tags, arg.CharacterID, arg.UserID)
	return err
}

const setUserHomeLayout = `-- name: SetUserHomeLayout :exec
UPDATE users
SET home_layout = ?
WHERE id = ?
`

type SetUserHomeLayoutParams struct {
	HomeLayout string `json:"home_layout"`
	ID         int64  `json:"id"`
}

func (q *Queries) SetUserHomeLayout(ctx context.Context, arg SetUserHomeLayoutParams) error {
	_, err := q.db.ExecContext(ctx, setUserHomeLayout, arg.HomeLayout, arg.ID)
	return err
}

const suggestSDETypes = `-- name: SuggestSDETypes :many

SELECT type_id, name FROM sde_types
WHERE market_group_id > 0 AND published = 1
  AND instr(lower(name), lower(?1)) > 0
ORDER BY CASE WHEN instr(lower(name), lower(?1)) = 1 THEN 0 ELSE 1 END, name
LIMIT 10
`

type SuggestSDETypesRow struct {
	TypeID int64  `json:"type_id"`
	Name   string `json:"name"`
}

// ---------------------------------------------------------------------
// Layout + market toolkit (schema 008): live market suggestions and
// the item database explorer. All local SDE reads. Matching uses
// instr() rather than LIKE: case-insensitive substring positions
// (1 = a prefix match), no wildcard escaping to worry about.
// ---------------------------------------------------------------------
func (q *Queries) SuggestSDETypes(ctx context.Context, lower string) ([]SuggestSDETypesRow, error) {
	rows, err := q.db.QueryContext(ctx, suggestSDETypes, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestSDETypesRow
	for rows.Next() {
		var i SuggestSDETypesRow
		if err := rows.Scan(&i.TypeID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacterTokens = `-- name: UpdateCharacterTokens :exec
UPDATE characters
SET access_token = ?, refresh_token = ?, token_expiry = ?, updated_at = datetime('now')
WHERE character_id = ?
`

type UpdateCharacterTokensParams struct {
	AccessToken  string         `json:"access_token"`
	RefreshToken string         `json:"refresh_token"`
	TokenExpiry  sql.NullString `json:"token_expiry"`
	CharacterID  int64          `json:"character_id"`
}

func (q *Queries) UpdateCharacterTokens(ctx context.Context, arg UpdateCharacterTokensParams) error {
	_, err := q.db.ExecContext(ctx, updateCharacterTokens,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
		arg.CharacterID,
	)
	return err
}

const upsertCharacter = `-- name: UpsertCharacter :one
INSERT INTO characters (
    character_id, user_id, name,
    access_token, refresh_token, token_expiry,
    scopes, cached_until, owner_hash, link_state, link_state_at,
    updated_at
) VALUES (
    ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?, ?,
    datetime('now')
)
ON CONFLICT (character_id) DO UPDATE SET
    user_id       = excluded.user_id,
    name          = excluded.name,
    access_token  = excluded.access_token,
    refresh_token = excluded.refresh_token,
    token_expiry  = excluded.token_expiry,
    scopes        = excluded.scopes,
    cached_until  = excluded.cached_until,
    owner_hash    = excluded.owner_hash,
    link_state    = excluded.link_state,
    link_state_at = excluded.link_state_at,
    updated_at    = excluded.updated_at
RETURNING character_id, user_id, name, access_token, refresh_token, token_expiry, scopes, cached_until, created_at, updated_at, owner_hash, tags, link_state, link_state_at
`

type UpsertCharacterParams struct {
	CharacterID  int64          `json:"character_id"`
	UserID       int64          `json:"user_id"`
	Name         string         `json:"name"`
	AccessToken  string         `json:"access_token"`
	RefreshToken string         `json:"refresh_token"`
	TokenExpiry  sql.NullString `json:"token_expiry"`
	Scopes       string         `json:"scopes"`
	CachedUntil  sql.NullString `json:"cached_until"`
	OwnerHash    string         `json:"owner_hash"`
	LinkState    string         `json:"link_state"`
	LinkStateAt  sql.NullString `json:"link_state_at"`
}

func (q *Queries) UpsertCharacter(ctx context.Context, arg UpsertCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, upsertCharacter,
		arg.CharacterID,
		arg.UserID,
		arg.Name,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
		arg.Scopes,
		arg.CachedUntil,
		arg.OwnerHash,
		arg.LinkState,
		arg.LinkStateAt,
	)
	var i Character
	err := row.Scan(
		&i.CharacterID,
		&i.UserID,
		&i.Name,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.Scopes,
		&i.CachedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerHash,
		&i.Tags,
		&i.LinkState,
		&i.LinkStateAt,
	)
	return i, err
}

const upsertCharacterCorporation = `-- name: UpsertCharacterCorporation :exec
INSERT INTO character_corporations (character_id, corporation_id, updated_at)
VALUES (?, ?, ?)
ON CONFLICT (character_id) DO UPDATE SET
    corporation_id = excluded.corporation_id,
    updated_at     = excluded.updated_at
`

type UpsertCharacterCorporationParams struct {
	CharacterID   int64  `json:"character_id"`
	CorporationID int64  `json:"corporation_id"`
	UpdatedAt     string `json:"updated_at"`
}

func (q *Queries) UpsertCharacterCorporation(ctx context.Context, arg UpsertCharacterCorporationParams) error {
	_, err := q.db.ExecContext(ctx, upsertCharacterCorporation, arg.CharacterID, arg.CorporationID, arg.UpdatedAt)
	return err
}

const upsertContractDetail = `-- name: UpsertContractDetail :exec
INSERT INTO contract_details (contract_id, character_id, payload, fetched_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (contract_id) DO UPDATE SET
    character_id = excluded.character_id,
    payload      = excluded.payload,
    fetched_at   = excluded.fetched_at
`

type UpsertContractDetailParams struct {
	ContractID  int64  `json:"contract_id"`
	CharacterID int64  `json:"character_id"`
	Payload     string `json:"payload"`
	FetchedAt   string `json:"fetched_at"`
}

func (q *Queries) UpsertContractDetail(ctx context.Context, arg UpsertContractDetailParams) error {
	_, err := q.db.ExecContext(ctx, upsertContractDetail,
		arg.ContractID,
		arg.CharacterID,
		arg.Payload,
		arg.FetchedAt,
	)
	return err
}

const upsertGlobalSnapshot = `-- name: UpsertGlobalSnapshot :exec
INSERT INTO global_snapshots (kind, payload, fetched_at, cached_until)
VALUES (?, ?, ?, ?)
ON CONFLICT (kind) DO UPDATE SET
    payload      = excluded.payload,
    fetched_at   = excluded.fetched_at,
    cached_until = excluded.cached_until
`

type UpsertGlobalSnapshotParams struct {
	Kind        string `json:"kind"`
	Payload     string `json:"payload"`
	FetchedAt   string `json:"fetched_at"`
	CachedUntil string `json:"cached_until"`
}

func (q *Queries) UpsertGlobalSnapshot(ctx context.Context, arg UpsertGlobalSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertGlobalSnapshot,
		arg.Kind,
		arg.Payload,
		arg.FetchedAt,
		arg.CachedUntil,
	)
	return err
}

const upsertItemName = `-- name: UpsertItemName :exec
INSERT INTO item_names (item_id, name)
VALUES (?, ?)
ON CONFLICT (item_id) DO UPDATE SET
    name = excluded.name
`

type UpsertItemNameParams struct {
	ItemID int64  `json:"item_id"`
	Name   string `json:"name"`
}

func (q *Queries) UpsertItemName(ctx context.Context, arg UpsertItemNameParams) error {
	_, err := q.db.ExecContext(ctx, upsertItemName, arg.ItemID, arg.Name)
	return err
}

const upsertKillmailDetail = `-- name: UpsertKillmailDetail :exec
INSERT INTO killmail_details (killmail_id, character_id, hash, payload, fetched_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (killmail_id) DO UPDATE SET
    character_id = excluded.character_id,
    hash         = excluded.hash,
    payload      = excluded.payload,
    fetched_at   = excluded.fetched_at
`

type UpsertKillmailDetailParams struct {
	KillmailID  int64  `json:"killmail_id"`
	CharacterID int64  `json:"character_id"`
	Hash        string `json:"hash"`
	Payload     string `json:"payload"`
	FetchedAt   string `json:"fetched_at"`
}

func (q *Queries) UpsertKillmailDetail(ctx context.Context, arg UpsertKillmailDetailParams) error {
	_, err := q.db.ExecContext(ctx, upsertKillmailDetail,
		arg.KillmailID,
		arg.CharacterID,
		arg.Hash,
		arg.Payload,
		arg.FetchedAt,
	)
	return err
}

const upsertSDEMeta = `-- name: UpsertSDEMeta :exec
INSERT INTO sde_meta (key, value)
VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET
    value = excluded.value
`

type UpsertSDEMetaParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSDEMeta(ctx context.Context, arg UpsertSDEMetaParams) error {
	_, err := q.db.ExecContext(ctx, upsertSDEMeta, arg.Key, arg.Value)
	return err
}

const upsertSnapshot = `-- name: UpsertSnapshot :exec
INSERT INTO character_snapshots (character_id, kind, payload, fetched_at, cached_until)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (character_id, kind) DO UPDATE SET
    payload      = excluded.payload,
    fetched_at   = excluded.fetched_at,
    cached_until = excluded.cached_until
`

type UpsertSnapshotParams struct {
	CharacterID int64          `json:"character_id"`
	Kind        string         `json:"kind"`
	Payload     string         `json:"payload"`
	FetchedAt   string         `json:"fetched_at"`
	CachedUntil sql.NullString `json:"cached_until"`
}

func (q *Queries) UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertSnapshot,
		arg.CharacterID,
		arg.Kind,
		arg.Payload,
		arg.FetchedAt,
		arg.CachedUntil,
	)
	return err
}

const upsertSnapshotFetchState = `-- name: UpsertSnapshotFetchState :exec
INSERT INTO snapshot_fetch_state (character_id, kind, state, detail, attempted_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (character_id, kind) DO UPDATE SET
    state        = excluded.state,
    detail       = excluded.detail,
    attempted_at = excluded.attempted_at
`

type UpsertSnapshotFetchStateParams struct {
	CharacterID int64  `json:"character_id"`
	Kind        string `json:"kind"`
	State       string `json:"state"`
	Detail      string `json:"detail"`
	AttemptedAt string `json:"attempted_at"`
}

func (q *Queries) UpsertSnapshotFetchState(ctx context.Context, arg UpsertSnapshotFetchStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertSnapshotFetchState,
		arg.CharacterID,
		arg.Kind,
		arg.State,
		arg.Detail,
		arg.AttemptedAt,
	)
	return err
}

const upsertTypeName = `-- name: UpsertTypeName :exec
INSERT INTO type_names (type_id, name)
VALUES (?, ?)
ON CONFLICT (type_id) DO UPDATE SET
    name = excluded.name
`

type UpsertTypeNameParams struct {
	TypeID int64  `json:"type_id"`
	Name   string `json:"name"`
}

func (q *Queries) UpsertTypeName(ctx context.Context, arg UpsertTypeNameParams) error {
	_, err := q.db.ExecContext(ctx, upsertTypeName, arg.TypeID, arg.Name)
	return err
}

const upsertWarDetail = `-- name: UpsertWarDetail :exec
INSERT INTO war_details (war_id, payload, fetched_at)
VALUES (?, ?, ?)
ON CONFLICT (war_id) DO UPDATE SET
    payload    = excluded.payload,
    fetched_at = excluded.fetched_at
`

type UpsertWarDetailParams struct {
	WarID     int64  `json:"war_id"`
	Payload   string `json:"payload"`
	FetchedAt string `json:"fetched_at"`
}

func (q *Queries) UpsertWarDetail(ctx context.Context, arg UpsertWarDetailParams) error {
	_, err := q.db.ExecContext(ctx, upsertWarDetail, arg.WarID, arg.Payload, arg.FetchedAt)
	return err
}
