// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_doctrines.sql

package db

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const addDoctrineFit = `-- name: AddDoctrineFit :one
INSERT INTO doctrine_fits (doctrine_id, name, ship_type_id, items_json, fleet_role, note, added_by, added_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type AddDoctrineFitParams struct {
	DoctrineID int64     `json:"doctrine_id"`
	Name       string    `json:"name"`
	ShipTypeID int64     `json:"ship_type_id"`
	ItemsJson  string    `json:"items_json"`
	FleetRole  string    `json:"fleet_role"`
	Note       string    `json:"note"`
	AddedBy    int64     `json:"added_by"`
	AddedAt    time.Time `json:"added_at"`
}

func (q *Queries) AddDoctrineFit(ctx context.Context, arg AddDoctrineFitParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addDoctrineFit,
		arg.DoctrineID,
		arg.Name,
		arg.ShipTypeID,
		arg.ItemsJson,
		arg.FleetRole,
		arg.Note,
		arg.AddedBy,
		arg.AddedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const countDoctrineFits = `-- name: CountDoctrineFits :one
SELECT COUNT(*)::bigint FROM doctrine_fits WHERE doctrine_id = $1
`

func (q *Queries) CountDoctrineFits(ctx context.Context, doctrineID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDoctrineFits, doctrineID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createDoctrine = `-- name: CreateDoctrine :one

INSERT INTO doctrines (corporation_id, name, category, description, tags, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
ON CONFLICT (corporation_id, lower(name)) DO NOTHING
RETURNING id
`

type CreateDoctrineParams struct {
	CorporationID int64     `json:"corporation_id"`
	Name          string    `json:"name"`
	Category      string    `json:"category"`
	Description   string    `json:"description"`
	Tags          string    `json:"tags"`
	CreatedBy     int64     `json:"created_by"`
	CreatedAt     time.Time `json:"created_at"`
}

// ---------------------------------------------------------------------
// Doctrines (schema 026).
// ---------------------------------------------------------------------
func (q *Queries) CreateDoctrine(ctx context.Context, arg CreateDoctrineParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDoctrine,
		arg.CorporationID,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.Tags,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteDoctrine = `-- name: DeleteDoctrine :exec
DELETE FROM doctrines WHERE id = $1
`

func (q *Queries) DeleteDoctrine(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDoctrine, id)
	return err
}

const deleteDoctrineFit = `-- name: DeleteDoctrineFit :exec
DELETE FROM doctrine_fits WHERE id = $1 AND doctrine_id = $2
`

type DeleteDoctrineFitParams struct {
	ID         int64 `json:"id"`
	DoctrineID int64 `json:"doctrine_id"`
}

func (q *Queries) DeleteDoctrineFit(ctx context.Context, arg DeleteDoctrineFitParams) error {
	_, err := q.db.ExecContext(ctx, deleteDoctrineFit, arg.ID, arg.DoctrineID)
	return err
}

const doctrineHasShip = `-- name: DoctrineHasShip :one
SELECT EXISTS (SELECT 1 FROM doctrine_fits WHERE doctrine_id = $1 AND ship_type_id = $2)
`

type DoctrineHasShipParams struct {
	DoctrineID int64 `json:"doctrine_id"`
	ShipTypeID int64 `json:"ship_type_id"`
}

func (q *Queries) DoctrineHasShip(ctx context.Context, arg DoctrineHasShipParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, doctrineHasShip, arg.DoctrineID, arg.ShipTypeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDoctrine = `-- name: GetDoctrine :one
SELECT id, corporation_id, name, category, description, tags, created_by, created_at, updated_at FROM doctrines WHERE id = $1
`

func (q *Queries) GetDoctrine(ctx context.Context, id int64) (Doctrine, error) {
	row := q.db.QueryRowContext(ctx, getDoctrine, id)
	var i Doctrine
	err := row.Scan(
		&i.ID,
		&i.CorporationID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Tags,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDoctrineFit = `-- name: GetDoctrineFit :one
SELECT f.id, f.doctrine_id, f.name, f.ship_type_id, f.items_json, f.fleet_role, f.note, f.added_by, f.added_at, d.corporation_id, d.name AS doctrine_name
FROM doctrine_fits f JOIN doctrines d ON d.id = f.doctrine_id
WHERE f.id = $1
`

type GetDoctrineFitRow struct {
	ID            int64     `json:"id"`
	DoctrineID    int64     `json:"doctrine_id"`
	Name          string    `json:"name"`
	ShipTypeID    int64     `json:"ship_type_id"`
	ItemsJson     string    `json:"items_json"`
	FleetRole     string    `json:"fleet_role"`
	Note          string    `json:"note"`
	AddedBy       int64     `json:"added_by"`
	AddedAt       time.Time `json:"added_at"`
	CorporationID int64     `json:"corporation_id"`
	DoctrineName  string    `json:"doctrine_name"`
}

func (q *Queries) GetDoctrineFit(ctx context.Context, id int64) (GetDoctrineFitRow, error) {
	row := q.db.QueryRowContext(ctx, getDoctrineFit, id)
	var i GetDoctrineFitRow
	err := row.Scan(
		&i.ID,
		&i.DoctrineID,
		&i.Name,
		&i.ShipTypeID,
		&i.ItemsJson,
		&i.FleetRole,
		&i.Note,
		&i.AddedBy,
		&i.AddedAt,
		&i.CorporationID,
		&i.DoctrineName,
	)
	return i, err
}

const listDoctrineFits = `-- name: ListDoctrineFits :many
SELECT id, doctrine_id, name, ship_type_id, items_json, fleet_role, note, added_by, added_at FROM doctrine_fits
WHERE doctrine_id = ANY($1::bigint[])
ORDER BY doctrine_id, id
`

// The fits of several doctrines, in the order they were added.
func (q *Queries) ListDoctrineFits(ctx context.Context, doctrineIds []int64) ([]DoctrineFit, error) {
	rows, err := q.db.QueryContext(ctx, listDoctrineFits, pq.Array(doctrineIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DoctrineFit
	for rows.Next() {
		var i DoctrineFit
		if err := rows.Scan(
			&i.ID,
			&i.DoctrineID,
			&i.Name,
			&i.ShipTypeID,
			&i.ItemsJson,
			&i.FleetRole,
			&i.Note,
			&i.AddedBy,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoctrinesForCorporations = `-- name: ListDoctrinesForCorporations :many
SELECT id, corporation_id, name, category, description, tags, created_by, created_at, updated_at FROM doctrines
WHERE corporation_id = ANY($1::bigint[])
ORDER BY corporation_id, lower(category), lower(name)
`

func (q *Queries) ListDoctrinesForCorporations(ctx context.Context, corporationIds []int64) ([]Doctrine, error) {
	rows, err := q.db.QueryContext(ctx, listDoctrinesForCorporations, pq.Array(corporationIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Doctrine
	for rows.Next() {
		var i Doctrine
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Tags,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDoctrine = `-- name: UpdateDoctrine :execrows
UPDATE doctrines d SET
    name        = $1,
    category    = $2,
    description = $3,
    tags        = $4,
    updated_at  = $5
WHERE d.id = $6
  AND NOT EXISTS (SELECT 1 FROM doctrines o
                  WHERE o.corporation_id = d.corporation_id AND lower(o.name) = lower($1) AND o.id <> d.id)
`

type UpdateDoctrineParams struct {
	Name        string    `json:"name"`
	Category    string    `json:"category"`
	Description string    `json:"description"`
	Tags        string    `json:"tags"`
	UpdatedAt   time.Time `json:"updated_at"`
	ID          int64     `json:"id"`
}

func (q *Queries) UpdateDoctrine(ctx context.Context, arg UpdateDoctrineParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDoctrine,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.Tags,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
