// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_discord.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deleteDiscordLink = `-- name: DeleteDiscordLink :exec
DELETE FROM discord_links WHERE user_id = $1
`

func (q *Queries) DeleteDiscordLink(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDiscordLink, userID)
	return err
}

const deleteOtherDiscordLinks = `-- name: DeleteOtherDiscordLinks :exec
DELETE FROM discord_links
WHERE discord_id = $1 AND user_id <> $2
`

type DeleteOtherDiscordLinksParams struct {
	DiscordID string `json:"discord_id"`
	UserID    int64  `json:"user_id"`
}

// A Discord account belongs to whoever connected it last: any other
// account's link to it is dropped first (in the same transaction).
func (q *Queries) DeleteOtherDiscordLinks(ctx context.Context, arg DeleteOtherDiscordLinksParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherDiscordLinks, arg.DiscordID, arg.UserID)
	return err
}

const getDiscordLink = `-- name: GetDiscordLink :one

SELECT user_id, discord_id, username, linked_at, dm_notifications, roles_applied, roles_synced_at FROM discord_links WHERE user_id = $1
`

// ---------------------------------------------------------------------
// Discord links (schema 016): which Discord account an EveSynapse
// account has connected.
// ---------------------------------------------------------------------
func (q *Queries) GetDiscordLink(ctx context.Context, userID int64) (DiscordLink, error) {
	row := q.db.QueryRowContext(ctx, getDiscordLink, userID)
	var i DiscordLink
	err := row.Scan(
		&i.UserID,
		&i.DiscordID,
		&i.Username,
		&i.LinkedAt,
		&i.DmNotifications,
		&i.RolesApplied,
		&i.RolesSyncedAt,
	)
	return i, err
}

const listDiscordLinks = `-- name: ListDiscordLinks :many
SELECT user_id, discord_id, username, linked_at, dm_notifications, roles_applied, roles_synced_at FROM discord_links ORDER BY user_id
`

func (q *Queries) ListDiscordLinks(ctx context.Context) ([]DiscordLink, error) {
	rows, err := q.db.QueryContext(ctx, listDiscordLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscordLink
	for rows.Next() {
		var i DiscordLink
		if err := rows.Scan(
			&i.UserID,
			&i.DiscordID,
			&i.Username,
			&i.LinkedAt,
			&i.DmNotifications,
			&i.RolesApplied,
			&i.RolesSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkedCorporationsByUser = `-- name: ListLinkedCorporationsByUser :many
SELECT DISTINCT cc.corporation_id
FROM characters c
JOIN character_corporations cc ON cc.character_id = c.character_id
WHERE c.user_id = $1 AND c.link_state = 'ok'
ORDER BY cc.corporation_id
`

// The corporations of an account's characters whose link to EVE is in
// good standing: what its Discord roles are worked out from.
func (q *Queries) ListLinkedCorporationsByUser(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listLinkedCorporationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var corporation_id int64
		if err := rows.Scan(&corporation_id); err != nil {
			return nil, err
		}
		items = append(items, corporation_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpsToAnnounceOnDiscord = `-- name: ListOpsToAnnounceOnDiscord :many
SELECT id, corporation_id, title, description, starts_at, duration_minutes, doctrine, form_up, fc_character_id, created_by_character, created_at, cancelled_at, capture_status, capture_checked_at, discord_announced_at FROM ops
WHERE discord_announced_at IS NULL
  AND cancelled_at IS NULL
  AND starts_at > $1
  AND created_at >= $2
ORDER BY id
`

type ListOpsToAnnounceOnDiscordParams struct {
	Now          time.Time `json:"now"`
	CreatedAfter time.Time `json:"created_after"`
}

// Ops not yet posted to Discord: planned recently, still ahead, not
// cancelled. The age limit keeps an install that turns the bot on from
// posting its whole calendar at once.
func (q *Queries) ListOpsToAnnounceOnDiscord(ctx context.Context, arg ListOpsToAnnounceOnDiscordParams) ([]Op, error) {
	rows, err := q.db.QueryContext(ctx, listOpsToAnnounceOnDiscord, arg.Now, arg.CreatedAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Op
	for rows.Next() {
		var i Op
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.DurationMinutes,
			&i.Doctrine,
			&i.FormUp,
			&i.FcCharacterID,
			&i.CreatedByCharacter,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.CaptureStatus,
			&i.CaptureCheckedAt,
			&i.DiscordAnnouncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDiscordDMNotifications = `-- name: SetDiscordDMNotifications :exec
UPDATE discord_links SET dm_notifications = $1 WHERE user_id = $2
`

type SetDiscordDMNotificationsParams struct {
	DmNotifications bool  `json:"dm_notifications"`
	UserID          int64 `json:"user_id"`
}

func (q *Queries) SetDiscordDMNotifications(ctx context.Context, arg SetDiscordDMNotificationsParams) error {
	_, err := q.db.ExecContext(ctx, setDiscordDMNotifications, arg.DmNotifications, arg.UserID)
	return err
}

const setDiscordRolesApplied = `-- name: SetDiscordRolesApplied :exec
UPDATE discord_links
SET roles_applied = $1, roles_synced_at = $2
WHERE user_id = $3
`

type SetDiscordRolesAppliedParams struct {
	RolesApplied  string       `json:"roles_applied"`
	RolesSyncedAt sql.NullTime `json:"roles_synced_at"`
	UserID        int64        `json:"user_id"`
}

func (q *Queries) SetDiscordRolesApplied(ctx context.Context, arg SetDiscordRolesAppliedParams) error {
	_, err := q.db.ExecContext(ctx, setDiscordRolesApplied, arg.RolesApplied, arg.RolesSyncedAt, arg.UserID)
	return err
}

const setOpDiscordAnnounced = `-- name: SetOpDiscordAnnounced :exec
UPDATE ops SET discord_announced_at = $1 WHERE id = $2
`

type SetOpDiscordAnnouncedParams struct {
	AnnouncedAt sql.NullTime `json:"announced_at"`
	ID          int64        `json:"id"`
}

func (q *Queries) SetOpDiscordAnnounced(ctx context.Context, arg SetOpDiscordAnnouncedParams) error {
	_, err := q.db.ExecContext(ctx, setOpDiscordAnnounced, arg.AnnouncedAt, arg.ID)
	return err
}

const upsertDiscordLink = `-- name: UpsertDiscordLink :exec
INSERT INTO discord_links (user_id, discord_id, username, linked_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    username = excluded.username,
    linked_at = CASE WHEN discord_links.discord_id = excluded.discord_id THEN discord_links.linked_at ELSE excluded.linked_at END,
    roles_applied = CASE WHEN discord_links.discord_id = excluded.discord_id THEN discord_links.roles_applied ELSE '' END,
    roles_synced_at = CASE WHEN discord_links.discord_id = excluded.discord_id THEN discord_links.roles_synced_at ELSE NULL END,
    discord_id = excluded.discord_id
`

type UpsertDiscordLinkParams struct {
	UserID    int64     `json:"user_id"`
	DiscordID string    `json:"discord_id"`
	Username  string    `json:"username"`
	LinkedAt  time.Time `json:"linked_at"`
}

// Connecting a different Discord account starts its roles afresh.
func (q *Queries) UpsertDiscordLink(ctx context.Context, arg UpsertDiscordLinkParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscordLink,
		arg.UserID,
		arg.DiscordID,
		arg.Username,
		arg.LinkedAt,
	)
	return err
}
