// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_notify.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const forgetNotificationSeenExcept = `-- name: ForgetNotificationSeenExcept :exec
DELETE FROM notification_seen
WHERE user_id = $1
  AND event_key LIKE $2
  AND NOT (event_key = ANY($3::text[]))
`

type ForgetNotificationSeenExceptParams struct {
	UserID     int64    `json:"user_id"`
	KeyPattern string   `json:"key_pattern"`
	KeepKeys   []string `json:"keep_keys"`
}

// A state that has cleared is forgotten, so it is announced again
// the next time it holds.
func (q *Queries) ForgetNotificationSeenExcept(ctx context.Context, arg ForgetNotificationSeenExceptParams) error {
	_, err := q.db.ExecContext(ctx, forgetNotificationSeenExcept, arg.UserID, arg.KeyPattern, pq.Array(arg.KeepKeys))
	return err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (user_id, character_id, kind, title, url, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertNotificationParams struct {
	UserID      int64     `json:"user_id"`
	CharacterID int64     `json:"character_id"`
	Kind        string    `json:"kind"`
	Title       string    `json:"title"`
	Url         string    `json:"url"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertNotification,
		arg.UserID,
		arg.CharacterID,
		arg.Kind,
		arg.Title,
		arg.Url,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertNotificationSeen = `-- name: InsertNotificationSeen :exec
INSERT INTO notification_seen (user_id, event_key, seen_at)
SELECT $1, unnest($2::text[]), $3
ON CONFLICT DO NOTHING
`

type InsertNotificationSeenParams struct {
	UserID    int64     `json:"user_id"`
	EventKeys []string  `json:"event_keys"`
	SeenAt    time.Time `json:"seen_at"`
}

func (q *Queries) InsertNotificationSeen(ctx context.Context, arg InsertNotificationSeenParams) error {
	_, err := q.db.ExecContext(ctx, insertNotificationSeen, arg.UserID, pq.Array(arg.EventKeys), arg.SeenAt)
	return err
}

const listNotificationSeenKeys = `-- name: ListNotificationSeenKeys :many

SELECT event_key FROM notification_seen
WHERE user_id = $1 AND event_key = ANY($2::text[])
`

type ListNotificationSeenKeysParams struct {
	UserID    int64    `json:"user_id"`
	EventKeys []string `json:"event_keys"`
}

// ---------------------------------------------------------------------
// Notifications (schema 012). The worker writes; pages read and mark
// read. notification_seen is the worker's memory of the events it
// has already considered.
// ---------------------------------------------------------------------
func (q *Queries) ListNotificationSeenKeys(ctx context.Context, arg ListNotificationSeenKeysParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationSeenKeys, arg.UserID, pq.Array(arg.EventKeys))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var event_key string
		if err := rows.Scan(&event_key); err != nil {
			return nil, err
		}
		items = append(items, event_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, character_id, kind, title, url, created_at, read_at FROM notifications
WHERE user_id = $1
ORDER BY id DESC
LIMIT $2
`

type ListNotificationsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CharacterID,
			&i.Kind,
			&i.Title,
			&i.Url,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotificationSummary = `-- name: ListUnreadNotificationSummary :many
SELECT DISTINCT ON (kind) kind, title, url,
       (COUNT(*) OVER (PARTITION BY kind))::bigint AS unread
FROM notifications
WHERE user_id = $1 AND read_at IS NULL
ORDER BY kind, id DESC
`

type ListUnreadNotificationSummaryRow struct {
	Kind   string `json:"kind"`
	Title  string `json:"title"`
	Url    string `json:"url"`
	Unread int64  `json:"unread"`
}

// One row per kind with something unread: how many, and the newest
// one's text and address. This is the top-bar icon's whole read.
func (q *Queries) ListUnreadNotificationSummary(ctx context.Context, userID int64) ([]ListUnreadNotificationSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadNotificationSummary, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnreadNotificationSummaryRow
	for rows.Next() {
		var i ListUnreadNotificationSummaryRow
		if err := rows.Scan(
			&i.Kind,
			&i.Title,
			&i.Url,
			&i.Unread,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications SET read_at = $1
WHERE user_id = $2 AND read_at IS NULL
`

type MarkNotificationsReadParams struct {
	ReadAt sql.NullTime `json:"read_at"`
	UserID int64        `json:"user_id"`
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationsRead, arg.ReadAt, arg.UserID)
	return err
}

const markNotificationsReadByKind = `-- name: MarkNotificationsReadByKind :exec
UPDATE notifications SET read_at = $1
WHERE user_id = $2 AND kind = $3 AND read_at IS NULL
`

type MarkNotificationsReadByKindParams struct {
	ReadAt sql.NullTime `json:"read_at"`
	UserID int64        `json:"user_id"`
	Kind   string       `json:"kind"`
}

func (q *Queries) MarkNotificationsReadByKind(ctx context.Context, arg MarkNotificationsReadByKindParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationsReadByKind, arg.ReadAt, arg.UserID, arg.Kind)
	return err
}

const pruneNotificationSeen = `-- name: PruneNotificationSeen :exec
DELETE FROM notification_seen WHERE seen_at < $1
`

func (q *Queries) PruneNotificationSeen(ctx context.Context, seenBefore time.Time) error {
	_, err := q.db.ExecContext(ctx, pruneNotificationSeen, seenBefore)
	return err
}

const pruneNotifications = `-- name: PruneNotifications :exec
DELETE FROM notifications
WHERE (read_at IS NOT NULL AND read_at < $1)
   OR created_at < $2
`

type PruneNotificationsParams struct {
	ReadBefore    sql.NullTime `json:"read_before"`
	CreatedBefore time.Time    `json:"created_before"`
}

// Read ones go after a while; unread ones are kept longer but not
// for ever.
func (q *Queries) PruneNotifications(ctx context.Context, arg PruneNotificationsParams) error {
	_, err := q.db.ExecContext(ctx, pruneNotifications, arg.ReadBefore, arg.CreatedBefore)
	return err
}

const touchNotificationSeen = `-- name: TouchNotificationSeen :exec
UPDATE notification_seen SET seen_at = $1
WHERE user_id = $2
  AND event_key = ANY($3::text[])
  AND seen_at < $4
`

type TouchNotificationSeenParams struct {
	SeenAt      time.Time `json:"seen_at"`
	UserID      int64     `json:"user_id"`
	EventKeys   []string  `json:"event_keys"`
	StaleBefore time.Time `json:"stale_before"`
}

// Keys still current are kept alive; touched at most once a day each.
func (q *Queries) TouchNotificationSeen(ctx context.Context, arg TouchNotificationSeenParams) error {
	_, err := q.db.ExecContext(ctx, touchNotificationSeen,
		arg.SeenAt,
		arg.UserID,
		pq.Array(arg.EventKeys),
		arg.StaleBefore,
	)
	return err
}
