// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_market.sql

package db

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const clearGuidePriceWant = `-- name: ClearGuidePriceWant :exec
DELETE FROM guide_price_wants
WHERE id = 1
`

func (q *Queries) ClearGuidePriceWant(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearGuidePriceWant)
	return err
}

const closeOrderLifecycle = `-- name: CloseOrderLifecycle :exec
UPDATE order_lifecycle
SET closed_at = $1::timestamptz, close_kind = $2, beaten_now = 0
WHERE character_id = $3 AND order_id = $4 AND closed_at IS NULL
`

type CloseOrderLifecycleParams struct {
	ClosedAt    time.Time `json:"closed_at"`
	CloseKind   string    `json:"close_kind"`
	CharacterID int64     `json:"character_id"`
	OrderID     int64     `json:"order_id"`
}

func (q *Queries) CloseOrderLifecycle(ctx context.Context, arg CloseOrderLifecycleParams) error {
	_, err := q.db.ExecContext(ctx, closeOrderLifecycle,
		arg.ClosedAt,
		arg.CloseKind,
		arg.CharacterID,
		arg.OrderID,
	)
	return err
}

const deleteGuidePrices = `-- name: DeleteGuidePrices :exec
DELETE FROM guide_prices
`

func (q *Queries) DeleteGuidePrices(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteGuidePrices)
	return err
}

const deleteMarketRegionStatsByRegion = `-- name: DeleteMarketRegionStatsByRegion :exec
DELETE FROM market_region_stats
WHERE region_id = $1
`

// P1 region stats (schema 031): worker-written per-(region,
// type) book statistics. A completed sweep replaces a region's
// rows inside one transaction: delete the region, then upsert
// the fresh measures type by type. The daily table keeps one
// snapshot row per (region, type, day) for trend work.
func (q *Queries) DeleteMarketRegionStatsByRegion(ctx context.Context, regionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMarketRegionStatsByRegion, regionID)
	return err
}

const deleteMarketStationLeaderboardByRegion = `-- name: DeleteMarketStationLeaderboardByRegion :exec
DELETE FROM market_station_leaderboard
WHERE region_id = $1
`

func (q *Queries) DeleteMarketStationLeaderboardByRegion(ctx context.Context, regionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMarketStationLeaderboardByRegion, regionID)
	return err
}

const deleteMarketStationStatsByRegion = `-- name: DeleteMarketStationStatsByRegion :exec
DELETE FROM market_station_stats
WHERE region_id = $1
`

// ---------------------------------------------------------------------
// P2 station stats (schema 032): per-(station, type) book
// statistics written by the same whole-region sweeps as the
// region stats above. A completed sweep replaces the region's
// station rows inside the sweep transaction: delete the region,
// then upsert the fresh measures station by station. The
// spread scanner page reads only these rows.
// ---------------------------------------------------------------------
func (q *Queries) DeleteMarketStationStatsByRegion(ctx context.Context, regionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMarketStationStatsByRegion, regionID)
	return err
}

const deleteMarketSweepOrdersByRegion = `-- name: DeleteMarketSweepOrdersByRegion :exec
DELETE FROM market_sweep_orders
WHERE region_id = $1
`

func (q *Queries) DeleteMarketSweepOrdersByRegion(ctx context.Context, regionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMarketSweepOrdersByRegion, regionID)
	return err
}

const deleteMarketSweepState = `-- name: DeleteMarketSweepState :exec
DELETE FROM market_sweep_state
WHERE region_id = $1
`

func (q *Queries) DeleteMarketSweepState(ctx context.Context, regionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMarketSweepState, regionID)
	return err
}

const deleteOrderHealthEntry = `-- name: DeleteOrderHealthEntry :exec
DELETE FROM order_health
WHERE character_id = $1 AND order_id = $2
`

type DeleteOrderHealthEntryParams struct {
	CharacterID int64 `json:"character_id"`
	OrderID     int64 `json:"order_id"`
}

func (q *Queries) DeleteOrderHealthEntry(ctx context.Context, arg DeleteOrderHealthEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteOrderHealthEntry, arg.CharacterID, arg.OrderID)
	return err
}

const deleteOrderHealthForCharacter = `-- name: DeleteOrderHealthForCharacter :exec
DELETE FROM order_health
WHERE character_id = $1
`

func (q *Queries) DeleteOrderHealthForCharacter(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrderHealthForCharacter, characterID)
	return err
}

const deleteRestockTarget = `-- name: DeleteRestockTarget :exec
DELETE FROM restock_targets
WHERE user_id = $1 AND type_id = $2
`

type DeleteRestockTargetParams struct {
	UserID int64 `json:"user_id"`
	TypeID int64 `json:"type_id"`
}

func (q *Queries) DeleteRestockTarget(ctx context.Context, arg DeleteRestockTargetParams) error {
	_, err := q.db.ExecContext(ctx, deleteRestockTarget, arg.UserID, arg.TypeID)
	return err
}

const deleteWatchlistEntry = `-- name: DeleteWatchlistEntry :exec
DELETE FROM market_watchlist
WHERE user_id = $1 AND type_id = $2 AND region_id = $3
`

type DeleteWatchlistEntryParams struct {
	UserID   int64 `json:"user_id"`
	TypeID   int64 `json:"type_id"`
	RegionID int64 `json:"region_id"`
}

func (q *Queries) DeleteWatchlistEntry(ctx context.Context, arg DeleteWatchlistEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteWatchlistEntry, arg.UserID, arg.TypeID, arg.RegionID)
	return err
}

const getAllianceRecord = `-- name: GetAllianceRecord :one
SELECT alliance_id, payload, state, fetched_at, priority
FROM alliance_records
WHERE alliance_id = $1
`

func (q *Queries) GetAllianceRecord(ctx context.Context, allianceID int64) (AllianceRecord, error) {
	row := q.db.QueryRowContext(ctx, getAllianceRecord, allianceID)
	var i AllianceRecord
	err := row.Scan(
		&i.AllianceID,
		&i.Payload,
		&i.State,
		&i.FetchedAt,
		&i.Priority,
	)
	return i, err
}

const getCorporationRecord = `-- name: GetCorporationRecord :one
SELECT corporation_id, payload, state, fetched_at, priority
FROM corporation_records
WHERE corporation_id = $1
`

// ---------------------------------------------------------------------
// Public corporation & alliance records (schema 026): the queues
// behind /corporation/ and /alliance/. Same posture as pilot
// records: pending rows are always due, ready rows re-check past
// the stale cutoff, missing rows settle for good.
// ---------------------------------------------------------------------
func (q *Queries) GetCorporationRecord(ctx context.Context, corporationID int64) (CorporationRecord, error) {
	row := q.db.QueryRowContext(ctx, getCorporationRecord, corporationID)
	var i CorporationRecord
	err := row.Scan(
		&i.CorporationID,
		&i.Payload,
		&i.State,
		&i.FetchedAt,
		&i.Priority,
	)
	return i, err
}

const getGuidePriceWant = `-- name: GetGuidePriceWant :one
SELECT id, wanted_at FROM guide_price_wants
WHERE id = 1
`

func (q *Queries) GetGuidePriceWant(ctx context.Context) (GuidePriceWant, error) {
	row := q.db.QueryRowContext(ctx, getGuidePriceWant)
	var i GuidePriceWant
	err := row.Scan(&i.ID, &i.WantedAt)
	return i, err
}

const getGuidePricesMeta = `-- name: GetGuidePricesMeta :one
SELECT id, fetched_at, cached_until FROM guide_prices_meta
WHERE id = 1
`

func (q *Queries) GetGuidePricesMeta(ctx context.Context) (GuidePricesMetum, error) {
	row := q.db.QueryRowContext(ctx, getGuidePricesMeta)
	var i GuidePricesMetum
	err := row.Scan(&i.ID, &i.FetchedAt, &i.CachedUntil)
	return i, err
}

const getIndustryCostIndex = `-- name: GetIndustryCostIndex :one
SELECT solar_system_id, activity, cost_index, fetched_at
FROM industry_cost_indices
WHERE solar_system_id = $1 AND activity = $2
`

type GetIndustryCostIndexParams struct {
	SolarSystemID int64  `json:"solar_system_id"`
	Activity      string `json:"activity"`
}

func (q *Queries) GetIndustryCostIndex(ctx context.Context, arg GetIndustryCostIndexParams) (IndustryCostIndex, error) {
	row := q.db.QueryRowContext(ctx, getIndustryCostIndex, arg.SolarSystemID, arg.Activity)
	var i IndustryCostIndex
	err := row.Scan(
		&i.SolarSystemID,
		&i.Activity,
		&i.CostIndex,
		&i.FetchedAt,
	)
	return i, err
}

const getMarketFetchState = `-- name: GetMarketFetchState :one
SELECT kind, state, detail, attempted_at
FROM market_fetch_state
WHERE kind = $1
`

func (q *Queries) GetMarketFetchState(ctx context.Context, kind string) (MarketFetchState, error) {
	row := q.db.QueryRowContext(ctx, getMarketFetchState, kind)
	var i MarketFetchState
	err := row.Scan(
		&i.Kind,
		&i.State,
		&i.Detail,
		&i.AttemptedAt,
	)
	return i, err
}

const getMarketRegionStatsStamp = `-- name: GetMarketRegionStatsStamp :one
SELECT MAX(updated_at) AS stamp, COUNT(*) AS row_count
FROM market_region_stats WHERE region_id = $1
`

type GetMarketRegionStatsStampRow struct {
	Stamp    interface{} `json:"stamp"`
	RowCount int64       `json:"row_count"`
}

// The freshest region-stat write for a region: the tradefinder
// page's "figures last gathered" stamp without pulling rows.
func (q *Queries) GetMarketRegionStatsStamp(ctx context.Context, regionID int64) (GetMarketRegionStatsStampRow, error) {
	row := q.db.QueryRowContext(ctx, getMarketRegionStatsStamp, regionID)
	var i GetMarketRegionStatsStampRow
	err := row.Scan(&i.Stamp, &i.RowCount)
	return i, err
}

const getMarketStationLeaderboardStamp = `-- name: GetMarketStationLeaderboardStamp :one
SELECT MAX(updated_at) AS stamp
FROM market_station_leaderboard
WHERE ($1::bigint = 0 OR region_id = $1::bigint)
`

func (q *Queries) GetMarketStationLeaderboardStamp(ctx context.Context, dollar_1 int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMarketStationLeaderboardStamp, dollar_1)
	var stamp interface{}
	err := row.Scan(&stamp)
	return stamp, err
}

const getMarketStationStatsStamp = `-- name: GetMarketStationStatsStamp :one
SELECT MAX(updated_at) AS stamp, COUNT(*) AS row_count
FROM market_station_stats WHERE region_id = $1
`

type GetMarketStationStatsStampRow struct {
	Stamp    interface{} `json:"stamp"`
	RowCount int64       `json:"row_count"`
}

// The freshest station-stat write for a region: the scanner
// page's "prices as of" stamp without pulling the rows.
func (q *Queries) GetMarketStationStatsStamp(ctx context.Context, regionID int64) (GetMarketStationStatsStampRow, error) {
	row := q.db.QueryRowContext(ctx, getMarketStationStatsStamp, regionID)
	var i GetMarketStationStatsStampRow
	err := row.Scan(&i.Stamp, &i.RowCount)
	return i, err
}

const getMarketSweepState = `-- name: GetMarketSweepState :one
SELECT region_id, next_page, pages_total, started_at, updated_at
FROM market_sweep_state
WHERE region_id = $1
`

// ---------------------------------------------------------------------
// P1 sweep staging (schema 034): disk-staged whole-region
// sweeps. A market_sweep_state row means a sweep is in progress
// for that region and next_page is its resume cursor; each
// fetched page's orders land in market_sweep_orders in the same
// transaction that advances the cursor. At completion the
// staged book is distilled into the region/station stats above
// and the staging rows are deleted in that same transaction.
// ---------------------------------------------------------------------
func (q *Queries) GetMarketSweepState(ctx context.Context, regionID int64) (MarketSweepState, error) {
	row := q.db.QueryRowContext(ctx, getMarketSweepState, regionID)
	var i MarketSweepState
	err := row.Scan(
		&i.RegionID,
		&i.NextPage,
		&i.PagesTotal,
		&i.StartedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarketTypePrice = `-- name: GetMarketTypePrice :one
SELECT region_id, type_id, buy_price, sell_price, buy_volume, sell_volume, fetched_at
FROM market_type_prices
WHERE region_id = $1 AND type_id = $2
`

type GetMarketTypePriceParams struct {
	RegionID int64 `json:"region_id"`
	TypeID   int64 `json:"type_id"`
}

func (q *Queries) GetMarketTypePrice(ctx context.Context, arg GetMarketTypePriceParams) (MarketTypePrice, error) {
	row := q.db.QueryRowContext(ctx, getMarketTypePrice, arg.RegionID, arg.TypeID)
	var i MarketTypePrice
	err := row.Scan(
		&i.RegionID,
		&i.TypeID,
		&i.BuyPrice,
		&i.SellPrice,
		&i.BuyVolume,
		&i.SellVolume,
		&i.FetchedAt,
	)
	return i, err
}

const getOrderLifecycle = `-- name: GetOrderLifecycle :one
SELECT id, character_id, order_id, type_id, location_id, region_id, is_buy_order, listed_price, volume_total, volume_remain_last, first_seen_at, last_seen_at, closed_at, close_kind, outbid_events, beaten_now
FROM order_lifecycle
WHERE character_id = $1 AND order_id = $2
`

type GetOrderLifecycleParams struct {
	CharacterID int64 `json:"character_id"`
	OrderID     int64 `json:"order_id"`
}

// ---------------------------------------------------------------------
// P4 order lifecycle (schema 033): append-only per-order history
// distilled from order snapshots. The worker upserts open orders,
// closes rows whose order has left the snapshot, and prunes old
// closed rows; the Orders page reads only these rows.
// ---------------------------------------------------------------------
func (q *Queries) GetOrderLifecycle(ctx context.Context, arg GetOrderLifecycleParams) (OrderLifecycle, error) {
	row := q.db.QueryRowContext(ctx, getOrderLifecycle, arg.CharacterID, arg.OrderID)
	var i OrderLifecycle
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.OrderID,
		&i.TypeID,
		&i.LocationID,
		&i.RegionID,
		&i.IsBuyOrder,
		&i.ListedPrice,
		&i.VolumeTotal,
		&i.VolumeRemainLast,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ClosedAt,
		&i.CloseKind,
		&i.OutbidEvents,
		&i.BeatenNow,
	)
	return i, err
}

const getPilotNameWant = `-- name: GetPilotNameWant :one
SELECT normalized_name, display_name, state, character_id, requested_at, resolved_at, next_try_at, attempts
FROM pilot_name_wants
WHERE normalized_name = $1
`

// Pilot name-resolution wants (schema 022): a topbar search for
// a pilot name no local tier knows notes the name once; the
// worker resolves due rows through ESI's public name lookup.
// 'missing' and 'ready' are settled states; 'error' rows wait
// for next_try_at so a failing lookup is not re-asked per search.
func (q *Queries) GetPilotNameWant(ctx context.Context, normalizedName string) (PilotNameWant, error) {
	row := q.db.QueryRowContext(ctx, getPilotNameWant, normalizedName)
	var i PilotNameWant
	err := row.Scan(
		&i.NormalizedName,
		&i.DisplayName,
		&i.State,
		&i.CharacterID,
		&i.RequestedAt,
		&i.ResolvedAt,
		&i.NextTryAt,
		&i.Attempts,
	)
	return i, err
}

const getPilotRecord = `-- name: GetPilotRecord :one
SELECT character_id, payload, state, fetched_at
FROM pilot_records
WHERE character_id = $1
`

type GetPilotRecordRow struct {
	CharacterID int64  `json:"character_id"`
	Payload     string `json:"payload"`
	State       string `json:"state"`
	FetchedAt   string `json:"fetched_at"`
}

// ---------------------------------------------------------------------
// Public pilot records (schema 015): the queue behind /pilot/.
// Pending rows are always due; ready rows re-check once their
// fetched_at passes the stale cutoff; missing rows (ESI 404)
// settle for good. The item details page enqueues type
// descriptions the same way: a type_details row with an empty
// fetched_at is a want.
// ---------------------------------------------------------------------
func (q *Queries) GetPilotRecord(ctx context.Context, characterID int64) (GetPilotRecordRow, error) {
	row := q.db.QueryRowContext(ctx, getPilotRecord, characterID)
	var i GetPilotRecordRow
	err := row.Scan(
		&i.CharacterID,
		&i.Payload,
		&i.State,
		&i.FetchedAt,
	)
	return i, err
}

const getPlanetName = `-- name: GetPlanetName :one
SELECT planet_id, name, state, resolved_at
FROM planet_names
WHERE planet_id = $1
`

// ---------------------------------------------------------------------
// Planet names (schema 025): queued when a PI surface meets an
// unresolved planet id, resolved in the background through the
// public GET /universe/planets/{id}/ (no token). 'resolved' rows
// re-check after a long window (planet names never change);
// 'missing' rows (404: not a planet) re-check after days;
// 'pending' rows are always due.
// ---------------------------------------------------------------------
func (q *Queries) GetPlanetName(ctx context.Context, planetID int64) (PlanetName, error) {
	row := q.db.QueryRowContext(ctx, getPlanetName, planetID)
	var i PlanetName
	err := row.Scan(
		&i.PlanetID,
		&i.Name,
		&i.State,
		&i.ResolvedAt,
	)
	return i, err
}

const getStructureContext = `-- name: GetStructureContext :one
SELECT structure_id, owner_corporation_id, system_id, type_id, updated_at
FROM structure_context
WHERE structure_id = $1
`

// ---------------------------------------------------------------------
// Structure context (schema 028): owner/system/type facts the
// corporation structure snapshots report, persisted as the
// snapshots are processed so the structure page renders from one
// small row. Latest snapshot wins; names are NOT stored here (they
// live in structure_names under provenance rules).
// ---------------------------------------------------------------------
func (q *Queries) GetStructureContext(ctx context.Context, structureID int64) (StructureContext, error) {
	row := q.db.QueryRowContext(ctx, getStructureContext, structureID)
	var i StructureContext
	err := row.Scan(
		&i.StructureID,
		&i.OwnerCorporationID,
		&i.SystemID,
		&i.TypeID,
		&i.UpdatedAt,
	)
	return i, err
}

const getStructureName = `-- name: GetStructureName :one
SELECT structure_id, name, state, resolved_at, source
FROM structure_names
WHERE structure_id = $1
`

// ---------------------------------------------------------------------
// Player structure names (schema 014): queued when a worker-computed
// view or the market book view meets an unresolved structure id,
// resolved in the background via any linked character holding
// esi-universe.read_structures.v1 (the lookup endpoint is
// authenticated-only). 'resolved' rows re-check after 30 days
// (structures can be renamed); 'missing' rows (403/404: private or
// gone) re-check after 24 hours; 'pending' rows are always due.
// The worker tries every eligible linked character before a
// negative answer is cached, and 'source' (schema 023) records the
// name's provenance so ESI truth outranks any lower-trust tier.
// ---------------------------------------------------------------------
func (q *Queries) GetStructureName(ctx context.Context, structureID int64) (StructureName, error) {
	row := q.db.QueryRowContext(ctx, getStructureName, structureID)
	var i StructureName
	err := row.Scan(
		&i.StructureID,
		&i.Name,
		&i.State,
		&i.ResolvedAt,
		&i.Source,
	)
	return i, err
}

const getWatchlistEntry = `-- name: GetWatchlistEntry :one
SELECT user_id, type_id, region_id, threshold_pct, created_at
FROM market_watchlist
WHERE user_id = $1 AND type_id = $2 AND region_id = $3
`

type GetWatchlistEntryParams struct {
	UserID   int64 `json:"user_id"`
	TypeID   int64 `json:"type_id"`
	RegionID int64 `json:"region_id"`
}

func (q *Queries) GetWatchlistEntry(ctx context.Context, arg GetWatchlistEntryParams) (MarketWatchlist, error) {
	row := q.db.QueryRowContext(ctx, getWatchlistEntry, arg.UserID, arg.TypeID, arg.RegionID)
	var i MarketWatchlist
	err := row.Scan(
		&i.UserID,
		&i.TypeID,
		&i.RegionID,
		&i.ThresholdPct,
		&i.CreatedAt,
	)
	return i, err
}

const insertMarketSweepOrder = `-- name: InsertMarketSweepOrder :exec
INSERT INTO market_sweep_orders (region_id, type_id, is_buy_order, price, volume_remain, location_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertMarketSweepOrderParams struct {
	RegionID     int64   `json:"region_id"`
	TypeID       int64   `json:"type_id"`
	IsBuyOrder   int64   `json:"is_buy_order"`
	Price        float64 `json:"price"`
	VolumeRemain int64   `json:"volume_remain"`
	LocationID   int64   `json:"location_id"`
}

func (q *Queries) InsertMarketSweepOrder(ctx context.Context, arg InsertMarketSweepOrderParams) error {
	_, err := q.db.ExecContext(ctx, insertMarketSweepOrder,
		arg.RegionID,
		arg.TypeID,
		arg.IsBuyOrder,
		arg.Price,
		arg.VolumeRemain,
		arg.LocationID,
	)
	return err
}

const insertMarketSweepState = `-- name: InsertMarketSweepState :exec
INSERT INTO market_sweep_state (region_id, next_page, pages_total, started_at, updated_at)
VALUES ($1, 1, 0, $2, $3)
`

type InsertMarketSweepStateParams struct {
	RegionID  int64     `json:"region_id"`
	StartedAt time.Time `json:"started_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) InsertMarketSweepState(ctx context.Context, arg InsertMarketSweepStateParams) error {
	_, err := q.db.ExecContext(ctx, insertMarketSweepState, arg.RegionID, arg.StartedAt, arg.UpdatedAt)
	return err
}

const insertPilotOrbitWant = `-- name: InsertPilotOrbitWant :exec
INSERT INTO pilot_records (character_id, priority)
VALUES ($1, 0)
ON CONFLICT DO NOTHING
`

func (q *Queries) InsertPilotOrbitWant(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, insertPilotOrbitWant, characterID)
	return err
}

const listAllWatchlistEntries = `-- name: ListAllWatchlistEntries :many
SELECT user_id, type_id, region_id, threshold_pct, created_at
FROM market_watchlist
ORDER BY type_id, region_id
`

func (q *Queries) ListAllWatchlistEntries(ctx context.Context) ([]MarketWatchlist, error) {
	rows, err := q.db.QueryContext(ctx, listAllWatchlistEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketWatchlist
	for rows.Next() {
		var i MarketWatchlist
		if err := rows.Scan(
			&i.UserID,
			&i.TypeID,
			&i.RegionID,
			&i.ThresholdPct,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllianceDrains = `-- name: ListAllianceDrains :many
SELECT alliance_id
FROM alliance_records
WHERE state = 'pending'
   OR (state = 'ready' AND fetched_at < $1)
ORDER BY CASE state WHEN 'pending' THEN 0 ELSE 1 END, priority DESC, fetched_at
LIMIT $2::bigint
`

type ListAllianceDrainsParams struct {
	StaleCutoff string `json:"stale_cutoff"`
	DrainLimit  int64  `json:"drain_limit"`
}

func (q *Queries) ListAllianceDrains(ctx context.Context, arg ListAllianceDrainsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listAllianceDrains, arg.StaleCutoff, arg.DrainLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var alliance_id int64
		if err := rows.Scan(&alliance_id); err != nil {
			return nil, err
		}
		items = append(items, alliance_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBestBuyStations = `-- name: ListBestBuyStations :many
SELECT DISTINCT ON (type_id) type_id, location_id, best_buy
FROM market_station_stats
WHERE region_id = $1 AND type_id = ANY($2::bigint[]) AND best_buy > 0
ORDER BY type_id, best_buy DESC, location_id
`

type ListBestBuyStationsParams struct {
	RegionID int64   `json:"region_id"`
	TypeIds  []int64 `json:"type_ids"`
}

type ListBestBuyStationsRow struct {
	TypeID     int64   `json:"type_id"`
	LocationID int64   `json:"location_id"`
	BestBuy    float64 `json:"best_buy"`
}

// Per-type highest-buy station rows for a bounded type list:
// the tradefinder's "best buyer at" hints without pulling the
// region's whole station grain.
func (q *Queries) ListBestBuyStations(ctx context.Context, arg ListBestBuyStationsParams) ([]ListBestBuyStationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBestBuyStations, arg.RegionID, pq.Array(arg.TypeIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBestBuyStationsRow
	for rows.Next() {
		var i ListBestBuyStationsRow
		if err := rows.Scan(&i.TypeID, &i.LocationID, &i.BestBuy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheapestSellStations = `-- name: ListCheapestSellStations :many
SELECT DISTINCT ON (type_id) type_id, location_id, best_sell
FROM market_station_stats
WHERE region_id = $1 AND type_id = ANY($2::bigint[]) AND best_sell > 0
ORDER BY type_id, best_sell, location_id
`

type ListCheapestSellStationsParams struct {
	RegionID int64   `json:"region_id"`
	TypeIds  []int64 `json:"type_ids"`
}

type ListCheapestSellStationsRow struct {
	TypeID     int64   `json:"type_id"`
	LocationID int64   `json:"location_id"`
	BestSell   float64 `json:"best_sell"`
}

// Per-type cheapest-sell station rows for a bounded type list:
// the tradefinder's "cheapest at" hints without pulling the
// region's whole station grain.
func (q *Queries) ListCheapestSellStations(ctx context.Context, arg ListCheapestSellStationsParams) ([]ListCheapestSellStationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCheapestSellStations, arg.RegionID, pq.Array(arg.TypeIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCheapestSellStationsRow
	for rows.Next() {
		var i ListCheapestSellStationsRow
		if err := rows.Scan(&i.TypeID, &i.LocationID, &i.BestSell); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClosedOrderLifecycleByCharacter = `-- name: ListClosedOrderLifecycleByCharacter :many
SELECT id, character_id, order_id, type_id, location_id, region_id, is_buy_order, listed_price, volume_total, volume_remain_last, first_seen_at, last_seen_at, closed_at, close_kind, outbid_events, beaten_now
FROM order_lifecycle
WHERE character_id = $1 AND closed_at IS NOT NULL
ORDER BY closed_at DESC, order_id DESC
LIMIT $2::bigint
`

type ListClosedOrderLifecycleByCharacterParams struct {
	CharacterID int64 `json:"character_id"`
	RowLimit    int64 `json:"row_limit"`
}

func (q *Queries) ListClosedOrderLifecycleByCharacter(ctx context.Context, arg ListClosedOrderLifecycleByCharacterParams) ([]OrderLifecycle, error) {
	rows, err := q.db.QueryContext(ctx, listClosedOrderLifecycleByCharacter, arg.CharacterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderLifecycle
	for rows.Next() {
		var i OrderLifecycle
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.OrderID,
			&i.TypeID,
			&i.LocationID,
			&i.RegionID,
			&i.IsBuyOrder,
			&i.ListedPrice,
			&i.VolumeTotal,
			&i.VolumeRemainLast,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ClosedAt,
			&i.CloseKind,
			&i.OutbidEvents,
			&i.BeatenNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCorporationDrains = `-- name: ListCorporationDrains :many
SELECT corporation_id
FROM corporation_records
WHERE state = 'pending'
   OR (state = 'ready' AND fetched_at < $1)
ORDER BY CASE state WHEN 'pending' THEN 0 ELSE 1 END, priority DESC, fetched_at
LIMIT $2::bigint
`

type ListCorporationDrainsParams struct {
	StaleCutoff string `json:"stale_cutoff"`
	DrainLimit  int64  `json:"drain_limit"`
}

func (q *Queries) ListCorporationDrains(ctx context.Context, arg ListCorporationDrainsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listCorporationDrains, arg.StaleCutoff, arg.DrainLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var corporation_id int64
		if err := rows.Scan(&corporation_id); err != nil {
			return nil, err
		}
		items = append(items, corporation_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuePilotNameWants = `-- name: ListDuePilotNameWants :many
SELECT normalized_name, display_name, state, character_id, requested_at, resolved_at, next_try_at, attempts
FROM pilot_name_wants
WHERE (state = 'pending' OR state = 'error')
  AND (next_try_at = '' OR next_try_at <= $1)
ORDER BY requested_at
LIMIT $2::bigint
`

type ListDuePilotNameWantsParams struct {
	Now string `json:"now"`
	Lim int64  `json:"lim"`
}

func (q *Queries) ListDuePilotNameWants(ctx context.Context, arg ListDuePilotNameWantsParams) ([]PilotNameWant, error) {
	rows, err := q.db.QueryContext(ctx, listDuePilotNameWants, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PilotNameWant
	for rows.Next() {
		var i PilotNameWant
		if err := rows.Scan(
			&i.NormalizedName,
			&i.DisplayName,
			&i.State,
			&i.CharacterID,
			&i.RequestedAt,
			&i.ResolvedAt,
			&i.NextTryAt,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuidePrices = `-- name: ListGuidePrices :many
SELECT type_id, adjusted_price, average_price FROM guide_prices
ORDER BY type_id
`

func (q *Queries) ListGuidePrices(ctx context.Context) ([]GuidePrice, error) {
	rows, err := q.db.QueryContext(ctx, listGuidePrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuidePrice
	for rows.Next() {
		var i GuidePrice
		if err := rows.Scan(&i.TypeID, &i.AdjustedPrice, &i.AveragePrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndustryCostIndices = `-- name: ListIndustryCostIndices :many
SELECT solar_system_id, activity, cost_index, fetched_at
FROM industry_cost_indices
ORDER BY activity, cost_index ASC
`

func (q *Queries) ListIndustryCostIndices(ctx context.Context) ([]IndustryCostIndex, error) {
	rows, err := q.db.QueryContext(ctx, listIndustryCostIndices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IndustryCostIndex
	for rows.Next() {
		var i IndustryCostIndex
		if err := rows.Scan(
			&i.SolarSystemID,
			&i.Activity,
			&i.CostIndex,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketAvgDailyVolumes = `-- name: ListMarketAvgDailyVolumes :many
SELECT h.type_id AS type_id, CAST(AVG(h.volume) AS DOUBLE PRECISION) AS avg_daily_volume
FROM market_history h
WHERE h.region_id = $1
  AND h.date >= (
      SELECT to_char(MAX(m.date)::date - INTERVAL '6 days', 'YYYY-MM-DD')
      FROM market_history m
      WHERE m.region_id = h.region_id AND m.type_id = h.type_id
  )
GROUP BY h.type_id
ORDER BY h.type_id
`

type ListMarketAvgDailyVolumesRow struct {
	TypeID         int64   `json:"type_id"`
	AvgDailyVolume float64 `json:"avg_daily_volume"`
}

// The sold-per-day figure the sweep stores on each region stat:
// the mean recorded daily volume over the seven calendar days
// ending on the type's newest recorded day (the newest day and
// the six before it), which is exactly what historyWindow(rows,
// 7) averages at render time. One pass over the region's whole
// history at sweep completion; types with no recorded history
// have no row here and read as 0.
func (q *Queries) ListMarketAvgDailyVolumes(ctx context.Context, regionID int64) ([]ListMarketAvgDailyVolumesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMarketAvgDailyVolumes, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarketAvgDailyVolumesRow
	for rows.Next() {
		var i ListMarketAvgDailyVolumesRow
		if err := rows.Scan(&i.TypeID, &i.AvgDailyVolume); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketHistory = `-- name: ListMarketHistory :many
SELECT region_id, type_id, date, average, highest, lowest, volume, order_count
FROM market_history
WHERE region_id = $1 AND type_id = $2
ORDER BY date DESC
LIMIT $3::bigint
`

type ListMarketHistoryParams struct {
	RegionID int64 `json:"region_id"`
	TypeID   int64 `json:"type_id"`
	RowLimit int64 `json:"row_limit"`
}

// The history window is a row count, not a calendar span: the
// chart and change math read the newest N rows of recorded
// trades, newest first, so a sparse item's stored trades are
// never hidden by an arbitrary date cutoff.
func (q *Queries) ListMarketHistory(ctx context.Context, arg ListMarketHistoryParams) ([]MarketHistory, error) {
	rows, err := q.db.QueryContext(ctx, listMarketHistory, arg.RegionID, arg.TypeID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketHistory
	for rows.Next() {
		var i MarketHistory
		if err := rows.Scan(
			&i.RegionID,
			&i.TypeID,
			&i.Date,
			&i.Average,
			&i.Highest,
			&i.Lowest,
			&i.Volume,
			&i.OrderCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketHistoryWants = `-- name: ListMarketHistoryWants :many
SELECT region_id, type_id, last_requested_at
FROM market_history_wants
WHERE last_requested_at >= $1
ORDER BY region_id, type_id
`

func (q *Queries) ListMarketHistoryWants(ctx context.Context, lastRequestedAt time.Time) ([]MarketHistoryWant, error) {
	rows, err := q.db.QueryContext(ctx, listMarketHistoryWants, lastRequestedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketHistoryWant
	for rows.Next() {
		var i MarketHistoryWant
		if err := rows.Scan(&i.RegionID, &i.TypeID, &i.LastRequestedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketRegionStatsByRegion = `-- name: ListMarketRegionStatsByRegion :many
SELECT region_id, type_id, best_sell, typical_sell, sell_band, best_buy, typical_buy, buy_band, sell_orders, buy_orders, sell_volume, buy_volume, updated_at, avg_daily_volume
FROM market_region_stats
WHERE region_id = $1
ORDER BY type_id
`

func (q *Queries) ListMarketRegionStatsByRegion(ctx context.Context, regionID int64) ([]MarketRegionStat, error) {
	rows, err := q.db.QueryContext(ctx, listMarketRegionStatsByRegion, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketRegionStat
	for rows.Next() {
		var i MarketRegionStat
		if err := rows.Scan(
			&i.RegionID,
			&i.TypeID,
			&i.BestSell,
			&i.TypicalSell,
			&i.SellBand,
			&i.BestBuy,
			&i.TypicalBuy,
			&i.BuyBand,
			&i.SellOrders,
			&i.BuyOrders,
			&i.SellVolume,
			&i.BuyVolume,
			&i.UpdatedAt,
			&i.AvgDailyVolume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketRegionStatsByType = `-- name: ListMarketRegionStatsByType :many
SELECT region_id, type_id, best_sell, typical_sell, sell_band, best_buy, typical_buy, buy_band, sell_orders, buy_orders, sell_volume, buy_volume, updated_at, avg_daily_volume
FROM market_region_stats
WHERE type_id = $1
ORDER BY region_id
`

func (q *Queries) ListMarketRegionStatsByType(ctx context.Context, typeID int64) ([]MarketRegionStat, error) {
	rows, err := q.db.QueryContext(ctx, listMarketRegionStatsByType, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketRegionStat
	for rows.Next() {
		var i MarketRegionStat
		if err := rows.Scan(
			&i.RegionID,
			&i.TypeID,
			&i.BestSell,
			&i.TypicalSell,
			&i.SellBand,
			&i.BestBuy,
			&i.TypicalBuy,
			&i.BuyBand,
			&i.SellOrders,
			&i.BuyOrders,
			&i.SellVolume,
			&i.BuyVolume,
			&i.UpdatedAt,
			&i.AvgDailyVolume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketRegionStatsDaily = `-- name: ListMarketRegionStatsDaily :many
SELECT region_id, type_id, day, best_sell, typical_sell, sell_band, best_buy, typical_buy, buy_band, sell_orders, buy_orders, sell_volume, buy_volume
FROM market_region_stats_daily
WHERE region_id = $1 AND type_id = $2
ORDER BY day
`

type ListMarketRegionStatsDailyParams struct {
	RegionID int64 `json:"region_id"`
	TypeID   int64 `json:"type_id"`
}

func (q *Queries) ListMarketRegionStatsDaily(ctx context.Context, arg ListMarketRegionStatsDailyParams) ([]MarketRegionStatsDaily, error) {
	rows, err := q.db.QueryContext(ctx, listMarketRegionStatsDaily, arg.RegionID, arg.TypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketRegionStatsDaily
	for rows.Next() {
		var i MarketRegionStatsDaily
		if err := rows.Scan(
			&i.RegionID,
			&i.TypeID,
			&i.Day,
			&i.BestSell,
			&i.TypicalSell,
			&i.SellBand,
			&i.BestBuy,
			&i.TypicalBuy,
			&i.BuyBand,
			&i.SellOrders,
			&i.BuyOrders,
			&i.SellVolume,
			&i.BuyVolume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketStationLeaderboard = `-- name: ListMarketStationLeaderboard :many
SELECT region_id, location_id, sell_orders, buy_orders, sell_value, buy_value, updated_at
FROM market_station_leaderboard
WHERE ($1::bigint = 0 OR region_id = $1::bigint)
ORDER BY region_id, location_id
`

func (q *Queries) ListMarketStationLeaderboard(ctx context.Context, dollar_1 int64) ([]MarketStationLeaderboard, error) {
	rows, err := q.db.QueryContext(ctx, listMarketStationLeaderboard, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketStationLeaderboard
	for rows.Next() {
		var i MarketStationLeaderboard
		if err := rows.Scan(
			&i.RegionID,
			&i.LocationID,
			&i.SellOrders,
			&i.BuyOrders,
			&i.SellValue,
			&i.BuyValue,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketStationStatsByRegion = `-- name: ListMarketStationStatsByRegion :many
SELECT location_id, region_id, type_id, best_sell, best_buy, sell_orders, buy_orders, sell_volume, buy_volume, updated_at
FROM market_station_stats
WHERE region_id = $1
ORDER BY location_id, type_id
`

func (q *Queries) ListMarketStationStatsByRegion(ctx context.Context, regionID int64) ([]MarketStationStat, error) {
	rows, err := q.db.QueryContext(ctx, listMarketStationStatsByRegion, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketStationStat
	for rows.Next() {
		var i MarketStationStat
		if err := rows.Scan(
			&i.LocationID,
			&i.RegionID,
			&i.TypeID,
			&i.BestSell,
			&i.BestBuy,
			&i.SellOrders,
			&i.BuyOrders,
			&i.SellVolume,
			&i.BuyVolume,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketSweepStationAggregates = `-- name: ListMarketSweepStationAggregates :many
SELECT location_id, type_id, is_buy_order,
       CAST(MIN(price) AS DOUBLE PRECISION) AS min_price, CAST(MAX(price) AS DOUBLE PRECISION) AS max_price,
       COUNT(*) AS order_count, CAST(SUM(volume_remain) AS BIGINT) AS total_volume
FROM market_sweep_orders
WHERE region_id = $1 AND location_id > 0
GROUP BY location_id, type_id, is_buy_order
ORDER BY location_id, type_id, is_buy_order
`

type ListMarketSweepStationAggregatesRow struct {
	LocationID  int64   `json:"location_id"`
	TypeID      int64   `json:"type_id"`
	IsBuyOrder  int64   `json:"is_buy_order"`
	MinPrice    float64 `json:"min_price"`
	MaxPrice    float64 `json:"max_price"`
	OrderCount  int64   `json:"order_count"`
	TotalVolume int64   `json:"total_volume"`
}

func (q *Queries) ListMarketSweepStationAggregates(ctx context.Context, regionID int64) ([]ListMarketSweepStationAggregatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMarketSweepStationAggregates, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarketSweepStationAggregatesRow
	for rows.Next() {
		var i ListMarketSweepStationAggregatesRow
		if err := rows.Scan(
			&i.LocationID,
			&i.TypeID,
			&i.IsBuyOrder,
			&i.MinPrice,
			&i.MaxPrice,
			&i.OrderCount,
			&i.TotalVolume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketSweepStationLeaderboardAggregates = `-- name: ListMarketSweepStationLeaderboardAggregates :many
SELECT location_id, is_buy_order,
       COUNT(*) AS order_count, CAST(SUM(price * volume_remain) AS DOUBLE PRECISION) AS open_value
FROM market_sweep_orders
WHERE region_id = $1 AND location_id > 0
GROUP BY location_id, is_buy_order
ORDER BY location_id, is_buy_order
`

type ListMarketSweepStationLeaderboardAggregatesRow struct {
	LocationID int64   `json:"location_id"`
	IsBuyOrder int64   `json:"is_buy_order"`
	OrderCount int64   `json:"order_count"`
	OpenValue  float64 `json:"open_value"`
}

// ---------------------------------------------------------------------
// P5 station leaderboard (schema_pg 002): per-station open-order
// counts and open ISK value per side, distilled by the same
// whole-region sweeps as the stats above. A completed sweep
// replaces the region's leaderboard rows inside the sweep
// transaction: delete the region, then upsert the fresh measures
// station by station. The aggregates read the staged book like
// the station stats do, but grouped only by place: the open
// value needs price times remaining volume per order, which the
// type-grain aggregates cannot reconstruct. The leaderboard page
// reads only these rows. A region argument of 0 means every
// region.
// ---------------------------------------------------------------------
func (q *Queries) ListMarketSweepStationLeaderboardAggregates(ctx context.Context, regionID int64) ([]ListMarketSweepStationLeaderboardAggregatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMarketSweepStationLeaderboardAggregates, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarketSweepStationLeaderboardAggregatesRow
	for rows.Next() {
		var i ListMarketSweepStationLeaderboardAggregatesRow
		if err := rows.Scan(
			&i.LocationID,
			&i.IsBuyOrder,
			&i.OrderCount,
			&i.OpenValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketSweepTypeIDs = `-- name: ListMarketSweepTypeIDs :many
SELECT DISTINCT type_id
FROM market_sweep_orders
WHERE region_id = $1
ORDER BY type_id
`

func (q *Queries) ListMarketSweepTypeIDs(ctx context.Context, regionID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listMarketSweepTypeIDs, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var type_id int64
		if err := rows.Scan(&type_id); err != nil {
			return nil, err
		}
		items = append(items, type_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketSweepTypeOrders = `-- name: ListMarketSweepTypeOrders :many
SELECT is_buy_order, price, volume_remain
FROM market_sweep_orders
WHERE region_id = $1 AND type_id = $2
ORDER BY is_buy_order, price
`

type ListMarketSweepTypeOrdersParams struct {
	RegionID int64 `json:"region_id"`
	TypeID   int64 `json:"type_id"`
}

type ListMarketSweepTypeOrdersRow struct {
	IsBuyOrder   int64   `json:"is_buy_order"`
	Price        float64 `json:"price"`
	VolumeRemain int64   `json:"volume_remain"`
}

func (q *Queries) ListMarketSweepTypeOrders(ctx context.Context, arg ListMarketSweepTypeOrdersParams) ([]ListMarketSweepTypeOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMarketSweepTypeOrders, arg.RegionID, arg.TypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarketSweepTypeOrdersRow
	for rows.Next() {
		var i ListMarketSweepTypeOrdersRow
		if err := rows.Scan(&i.IsBuyOrder, &i.Price, &i.VolumeRemain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketTypePricesForTypes = `-- name: ListMarketTypePricesForTypes :many
SELECT region_id, type_id, buy_price, sell_price, buy_volume, sell_volume, fetched_at
FROM market_type_prices
WHERE region_id = $1 AND type_id = ANY($2::bigint[])
`

type ListMarketTypePricesForTypesParams struct {
	RegionID int64   `json:"region_id"`
	Column2  []int64 `json:"column_2"`
}

func (q *Queries) ListMarketTypePricesForTypes(ctx context.Context, arg ListMarketTypePricesForTypesParams) ([]MarketTypePrice, error) {
	rows, err := q.db.QueryContext(ctx, listMarketTypePricesForTypes, arg.RegionID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketTypePrice
	for rows.Next() {
		var i MarketTypePrice
		if err := rows.Scan(
			&i.RegionID,
			&i.TypeID,
			&i.BuyPrice,
			&i.SellPrice,
			&i.BuyVolume,
			&i.SellVolume,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenOrderLifecycleByCharacter = `-- name: ListOpenOrderLifecycleByCharacter :many
SELECT id, character_id, order_id, type_id, location_id, region_id, is_buy_order, listed_price, volume_total, volume_remain_last, first_seen_at, last_seen_at, closed_at, close_kind, outbid_events, beaten_now
FROM order_lifecycle
WHERE character_id = $1 AND closed_at IS NULL
ORDER BY order_id
`

func (q *Queries) ListOpenOrderLifecycleByCharacter(ctx context.Context, characterID int64) ([]OrderLifecycle, error) {
	rows, err := q.db.QueryContext(ctx, listOpenOrderLifecycleByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderLifecycle
	for rows.Next() {
		var i OrderLifecycle
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.OrderID,
			&i.TypeID,
			&i.LocationID,
			&i.RegionID,
			&i.IsBuyOrder,
			&i.ListedPrice,
			&i.VolumeTotal,
			&i.VolumeRemainLast,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ClosedAt,
			&i.CloseKind,
			&i.OutbidEvents,
			&i.BeatenNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderHealthByCharacter = `-- name: ListOrderHealthByCharacter :many
SELECT character_id, order_id, type_id, region_id, location_id, my_price, station_best, region_best, status, computed_at
FROM order_health
WHERE character_id = $1
ORDER BY type_id, order_id
`

func (q *Queries) ListOrderHealthByCharacter(ctx context.Context, characterID int64) ([]OrderHealth, error) {
	rows, err := q.db.QueryContext(ctx, listOrderHealthByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderHealth
	for rows.Next() {
		var i OrderHealth
		if err := rows.Scan(
			&i.CharacterID,
			&i.OrderID,
			&i.TypeID,
			&i.RegionID,
			&i.LocationID,
			&i.MyPrice,
			&i.StationBest,
			&i.RegionBest,
			&i.Status,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderHealthByUser = `-- name: ListOrderHealthByUser :many
SELECT oh.character_id, oh.order_id, oh.type_id, oh.region_id, oh.location_id, oh.my_price, oh.station_best, oh.region_best, oh.status, oh.computed_at
FROM order_health oh
JOIN characters c ON c.character_id = oh.character_id
WHERE c.user_id = $1
ORDER BY c.name, oh.type_id, oh.order_id
`

func (q *Queries) ListOrderHealthByUser(ctx context.Context, userID int64) ([]OrderHealth, error) {
	rows, err := q.db.QueryContext(ctx, listOrderHealthByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderHealth
	for rows.Next() {
		var i OrderHealth
		if err := rows.Scan(
			&i.CharacterID,
			&i.OrderID,
			&i.TypeID,
			&i.RegionID,
			&i.LocationID,
			&i.MyPrice,
			&i.StationBest,
			&i.RegionBest,
			&i.Status,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderLifecycleByCharacter = `-- name: ListOrderLifecycleByCharacter :many
SELECT id, character_id, order_id, type_id, location_id, region_id, is_buy_order, listed_price, volume_total, volume_remain_last, first_seen_at, last_seen_at, closed_at, close_kind, outbid_events, beaten_now
FROM order_lifecycle
WHERE character_id = $1
ORDER BY first_seen_at DESC, order_id DESC
`

func (q *Queries) ListOrderLifecycleByCharacter(ctx context.Context, characterID int64) ([]OrderLifecycle, error) {
	rows, err := q.db.QueryContext(ctx, listOrderLifecycleByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderLifecycle
	for rows.Next() {
		var i OrderLifecycle
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.OrderID,
			&i.TypeID,
			&i.LocationID,
			&i.RegionID,
			&i.IsBuyOrder,
			&i.ListedPrice,
			&i.VolumeTotal,
			&i.VolumeRemainLast,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ClosedAt,
			&i.CloseKind,
			&i.OutbidEvents,
			&i.BeatenNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderLifecycleByUser = `-- name: ListOrderLifecycleByUser :many
SELECT ol.id, ol.character_id, ol.order_id, ol.type_id, ol.location_id, ol.region_id, ol.is_buy_order, ol.listed_price, ol.volume_total, ol.volume_remain_last, ol.first_seen_at, ol.last_seen_at, ol.closed_at, ol.close_kind, ol.outbid_events, ol.beaten_now
FROM order_lifecycle ol
JOIN characters c ON c.character_id = ol.character_id
WHERE c.user_id = $1
ORDER BY ol.closed_at DESC NULLS LAST, ol.first_seen_at DESC, ol.order_id DESC
`

func (q *Queries) ListOrderLifecycleByUser(ctx context.Context, userID int64) ([]OrderLifecycle, error) {
	rows, err := q.db.QueryContext(ctx, listOrderLifecycleByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderLifecycle
	for rows.Next() {
		var i OrderLifecycle
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.OrderID,
			&i.TypeID,
			&i.LocationID,
			&i.RegionID,
			&i.IsBuyOrder,
			&i.ListedPrice,
			&i.VolumeTotal,
			&i.VolumeRemainLast,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ClosedAt,
			&i.CloseKind,
			&i.OutbidEvents,
			&i.BeatenNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPilotDrains = `-- name: ListPilotDrains :many
SELECT character_id
FROM pilot_records
WHERE state = 'pending'
   OR (state = 'ready' AND fetched_at < $1)
ORDER BY CASE state WHEN 'pending' THEN 0 ELSE 1 END, priority DESC, fetched_at
LIMIT $2::bigint
`

type ListPilotDrainsParams struct {
	StaleCutoff string `json:"stale_cutoff"`
	DrainLimit  int64  `json:"drain_limit"`
}

func (q *Queries) ListPilotDrains(ctx context.Context, arg ListPilotDrainsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPilotDrains, arg.StaleCutoff, arg.DrainLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var character_id int64
		if err := rows.Scan(&character_id); err != nil {
			return nil, err
		}
		items = append(items, character_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPilotRecordIDs = `-- name: ListPilotRecordIDs :many
SELECT character_id
FROM pilot_records
`

func (q *Queries) ListPilotRecordIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPilotRecordIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var character_id int64
		if err := rows.Scan(&character_id); err != nil {
			return nil, err
		}
		items = append(items, character_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanetResolutions = `-- name: ListPlanetResolutions :many
SELECT planet_id
FROM planet_names
WHERE state = 'pending'
   OR (state = 'resolved' AND resolved_at < $1)
   OR (state = 'missing' AND resolved_at < $2)
ORDER BY CASE state WHEN 'pending' THEN 0 ELSE 1 END, planet_id
LIMIT $3::bigint
`

type ListPlanetResolutionsParams struct {
	ResolvedCutoff  string `json:"resolved_cutoff"`
	MissingCutoff   string `json:"missing_cutoff"`
	ResolutionLimit int64  `json:"resolution_limit"`
}

func (q *Queries) ListPlanetResolutions(ctx context.Context, arg ListPlanetResolutionsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPlanetResolutions, arg.ResolvedCutoff, arg.MissingCutoff, arg.ResolutionLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var planet_id int64
		if err := rows.Scan(&planet_id); err != nil {
			return nil, err
		}
		items = append(items, planet_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestockTargets = `-- name: ListRestockTargets :many
SELECT user_id, type_id, target_qty, min_margin_pct, updated_at
FROM restock_targets
WHERE user_id = $1
ORDER BY type_id
`

func (q *Queries) ListRestockTargets(ctx context.Context, userID int64) ([]RestockTarget, error) {
	rows, err := q.db.QueryContext(ctx, listRestockTargets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RestockTarget
	for rows.Next() {
		var i RestockTarget
		if err := rows.Scan(
			&i.UserID,
			&i.TypeID,
			&i.TargetQty,
			&i.MinMarginPct,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScannerOpportunities = `-- name: ListScannerOpportunities :many
SELECT type_id, location_id, best_sell, best_buy, sell_volume, buy_volume, daily_volume
FROM (
    SELECT ss.type_id, ss.location_id, ss.best_sell, ss.best_buy,
           ss.sell_volume, ss.buy_volume,
           COALESCE(rs.avg_daily_volume, 0) AS daily_volume,
           (ss.best_sell - ss.best_buy) * LEAST(COALESCE(rs.avg_daily_volume, 0), ss.sell_volume::double precision, ss.buy_volume::double precision) AS profit
    FROM market_station_stats ss
    LEFT JOIN market_region_stats rs ON rs.region_id = ss.region_id AND rs.type_id = ss.type_id
    WHERE ss.region_id = $1
      AND ss.best_buy > 0
      AND ss.best_sell > ss.best_buy
      AND (ss.best_sell - ss.best_buy) / ss.best_buy * 100 >= $2
      AND COALESCE(rs.avg_daily_volume, 0) >= $3::bigint
      AND LEAST(COALESCE(rs.avg_daily_volume, 0), ss.sell_volume::double precision, ss.buy_volume::double precision) > 0
) ranked
ORDER BY profit DESC, type_id, location_id
LIMIT $4::bigint
`

type ListScannerOpportunitiesParams struct {
	RegionID  int64   `json:"region_id"`
	MinSpread float64 `json:"min_spread"`
	MinVolume int64   `json:"min_volume"`
	RowCap    int64   `json:"row_cap"`
}

type ListScannerOpportunitiesRow struct {
	TypeID      int64   `json:"type_id"`
	LocationID  int64   `json:"location_id"`
	BestSell    float64 `json:"best_sell"`
	BestBuy     float64 `json:"best_buy"`
	SellVolume  int64   `json:"sell_volume"`
	BuyVolume   int64   `json:"buy_volume"`
	DailyVolume float64 `json:"daily_volume"`
}

// The spread scanner's opportunities, computed and ranked in SQL:
// one bounded read of at most scannerRowCap rows instead of
// pulling every stored station row for the region into Go.
// Mirrors the old Go filter exactly: real buy above zero, sell
// above the buy, spread floor, daily-volume floor, and the
// tradeable size as the least of what trades, what sellers
// hold, and what buyers want.
func (q *Queries) ListScannerOpportunities(ctx context.Context, arg ListScannerOpportunitiesParams) ([]ListScannerOpportunitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listScannerOpportunities,
		arg.RegionID,
		arg.MinSpread,
		arg.MinVolume,
		arg.RowCap,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScannerOpportunitiesRow
	for rows.Next() {
		var i ListScannerOpportunitiesRow
		if err := rows.Scan(
			&i.TypeID,
			&i.LocationID,
			&i.BestSell,
			&i.BestBuy,
			&i.SellVolume,
			&i.BuyVolume,
			&i.DailyVolume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleMarketTypePrices = `-- name: ListStaleMarketTypePrices :many
SELECT region_id, type_id
FROM market_type_prices
WHERE fetched_at < now() - ($1::int * INTERVAL '1 second')
ORDER BY fetched_at ASC
LIMIT $2
`

type ListStaleMarketTypePricesParams struct {
	Column1 int32 `json:"column_1"`
	Limit   int32 `json:"limit"`
}

type ListStaleMarketTypePricesRow struct {
	RegionID int64 `json:"region_id"`
	TypeID   int64 `json:"type_id"`
}

func (q *Queries) ListStaleMarketTypePrices(ctx context.Context, arg ListStaleMarketTypePricesParams) ([]ListStaleMarketTypePricesRow, error) {
	rows, err := q.db.QueryContext(ctx, listStaleMarketTypePrices, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleMarketTypePricesRow
	for rows.Next() {
		var i ListStaleMarketTypePricesRow
		if err := rows.Scan(&i.RegionID, &i.TypeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStructureResolutions = `-- name: ListStructureResolutions :many
SELECT structure_id
FROM structure_names
WHERE state = 'pending'
   OR (state = 'resolved' AND resolved_at < $1)
   OR (state = 'missing' AND resolved_at < $2)
ORDER BY CASE state WHEN 'pending' THEN 0 ELSE 1 END, structure_id
LIMIT $3::bigint
`

type ListStructureResolutionsParams struct {
	ResolvedCutoff  string `json:"resolved_cutoff"`
	MissingCutoff   string `json:"missing_cutoff"`
	ResolutionLimit int64  `json:"resolution_limit"`
}

func (q *Queries) ListStructureResolutions(ctx context.Context, arg ListStructureResolutionsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listStructureResolutions, arg.ResolvedCutoff, arg.MissingCutoff, arg.ResolutionLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var structure_id int64
		if err := rows.Scan(&structure_id); err != nil {
			return nil, err
		}
		items = append(items, structure_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradefinderRoutes = `-- name: ListTradefinderRoutes :many
SELECT type_id, origin_typical_buy, dest_typical_sell, dest_daily_volume,
       origin_buy_volume, dest_sell_volume
FROM (
    SELECT o.type_id,
           o.typical_buy AS origin_typical_buy,
           d.typical_sell AS dest_typical_sell,
           d.avg_daily_volume AS dest_daily_volume,
           o.buy_volume AS origin_buy_volume,
           d.sell_volume AS dest_sell_volume,
           (d.typical_sell - o.typical_buy) * LEAST(d.avg_daily_volume, o.buy_volume::double precision, d.sell_volume::double precision) AS profit
    FROM market_region_stats o
    JOIN market_region_stats d ON d.region_id = $1 AND d.type_id = o.type_id
    WHERE o.region_id = $2
      AND o.typical_buy > 0 AND d.typical_sell > 0
      AND d.typical_sell > o.typical_buy
      AND ($3::bigint = 1 OR NOT (o.typical_sell > 0 AND o.typical_buy * 10 < o.typical_sell))
      AND (d.typical_sell - o.typical_buy) / o.typical_buy * 100 >= $4
      AND d.avg_daily_volume >= $5::bigint
      AND LEAST(d.avg_daily_volume, o.buy_volume::double precision, d.sell_volume::double precision) > 0
      AND o.updated_at >= $6 AND d.updated_at >= $6
) ranked
ORDER BY profit DESC, type_id
LIMIT $7::bigint
`

type ListTradefinderRoutesParams struct {
	DestRegion     int64     `json:"dest_region"`
	OriginRegion   int64     `json:"origin_region"`
	IncludeLowball int64     `json:"include_lowball"`
	MinMargin      float64   `json:"min_margin"`
	MinVolume      int64     `json:"min_volume"`
	Cutoff         time.Time `json:"cutoff"`
	RowCap         int64     `json:"row_cap"`
}

type ListTradefinderRoutesRow struct {
	TypeID           int64   `json:"type_id"`
	OriginTypicalBuy float64 `json:"origin_typical_buy"`
	DestTypicalSell  float64 `json:"dest_typical_sell"`
	DestDailyVolume  float64 `json:"dest_daily_volume"`
	OriginBuyVolume  int64   `json:"origin_buy_volume"`
	DestSellVolume   int64   `json:"dest_sell_volume"`
}

// The tradefinder's routes, computed and ranked in SQL: one
// bounded read of at most tradefinderRowCap rows instead of
// pulling both regions' stored stats into Go. Mirrors the old
// Go filter exactly: fresh figures on both sides (3-day rule,
// compared as RFC3339 text), a real typical buy and sell,
// margin above zero, the lowball opt-out, the margin-% floor,
// the sold-per-day floor, and the movable size as the least of
// what trades, the origin's open buy volume, and the
// destination's open sell volume.
func (q *Queries) ListTradefinderRoutes(ctx context.Context, arg ListTradefinderRoutesParams) ([]ListTradefinderRoutesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTradefinderRoutes,
		arg.DestRegion,
		arg.OriginRegion,
		arg.IncludeLowball,
		arg.MinMargin,
		arg.MinVolume,
		arg.Cutoff,
		arg.RowCap,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTradefinderRoutesRow
	for rows.Next() {
		var i ListTradefinderRoutesRow
		if err := rows.Scan(
			&i.TypeID,
			&i.OriginTypicalBuy,
			&i.DestTypicalSell,
			&i.DestDailyVolume,
			&i.OriginBuyVolume,
			&i.DestSellVolume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchlistByUser = `-- name: ListWatchlistByUser :many
SELECT user_id, type_id, region_id, threshold_pct, created_at
FROM market_watchlist
WHERE user_id = $1
ORDER BY type_id, region_id
`

func (q *Queries) ListWatchlistByUser(ctx context.Context, userID int64) ([]MarketWatchlist, error) {
	rows, err := q.db.QueryContext(ctx, listWatchlistByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketWatchlist
	for rows.Next() {
		var i MarketWatchlist
		if err := rows.Scan(
			&i.UserID,
			&i.TypeID,
			&i.RegionID,
			&i.ThresholdPct,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const noteGuidePriceWant = `-- name: NoteGuidePriceWant :exec
INSERT INTO guide_price_wants (id, wanted_at)
VALUES (1, $1)
ON CONFLICT (id) DO UPDATE SET
    wanted_at = excluded.wanted_at
`

// ---------------------------------------------------------------------
// v0.3.14 guide-price wants (schema 027): the durable note a
// kill view leaves when it has no prices to value with. One
// singleton row -- the guide is global, so one want covers every
// viewer -- noted at render time, answered by the worker's
// urgent drain with a guide refresh when ESI's window allows.
// ---------------------------------------------------------------------
func (q *Queries) NoteGuidePriceWant(ctx context.Context, wantedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, noteGuidePriceWant, wantedAt)
	return err
}

const pruneOldOrderLifecycle = `-- name: PruneOldOrderLifecycle :exec
DELETE FROM order_lifecycle
WHERE id IN (
    SELECT ol.id FROM order_lifecycle AS ol
    WHERE ol.closed_at < $1::timestamptz
    ORDER BY ol.closed_at
    LIMIT $2::bigint
)
`

type PruneOldOrderLifecycleParams struct {
	ClosedBefore time.Time `json:"closed_before"`
	RowLimit     int64     `json:"row_limit"`
}

func (q *Queries) PruneOldOrderLifecycle(ctx context.Context, arg PruneOldOrderLifecycleParams) error {
	_, err := q.db.ExecContext(ctx, pruneOldOrderLifecycle, arg.ClosedBefore, arg.RowLimit)
	return err
}

const setAllianceRecord = `-- name: SetAllianceRecord :exec
INSERT INTO alliance_records (alliance_id, payload, state, fetched_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (alliance_id) DO UPDATE SET
    payload    = excluded.payload,
    state      = excluded.state,
    fetched_at = excluded.fetched_at
`

type SetAllianceRecordParams struct {
	AllianceID int64  `json:"alliance_id"`
	Payload    string `json:"payload"`
	State      string `json:"state"`
	FetchedAt  string `json:"fetched_at"`
}

func (q *Queries) SetAllianceRecord(ctx context.Context, arg SetAllianceRecordParams) error {
	_, err := q.db.ExecContext(ctx, setAllianceRecord,
		arg.AllianceID,
		arg.Payload,
		arg.State,
		arg.FetchedAt,
	)
	return err
}

const setCorporationRecord = `-- name: SetCorporationRecord :exec
INSERT INTO corporation_records (corporation_id, payload, state, fetched_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (corporation_id) DO UPDATE SET
    payload    = excluded.payload,
    state      = excluded.state,
    fetched_at = excluded.fetched_at
`

type SetCorporationRecordParams struct {
	CorporationID int64  `json:"corporation_id"`
	Payload       string `json:"payload"`
	State         string `json:"state"`
	FetchedAt     string `json:"fetched_at"`
}

func (q *Queries) SetCorporationRecord(ctx context.Context, arg SetCorporationRecordParams) error {
	_, err := q.db.ExecContext(ctx, setCorporationRecord,
		arg.CorporationID,
		arg.Payload,
		arg.State,
		arg.FetchedAt,
	)
	return err
}

const setPilotNameWantError = `-- name: SetPilotNameWantError :exec
UPDATE pilot_name_wants
SET state = 'error', attempts = attempts + 1, resolved_at = $1, next_try_at = $2
WHERE normalized_name = $3
`

type SetPilotNameWantErrorParams struct {
	ResolvedAt     string `json:"resolved_at"`
	NextTryAt      string `json:"next_try_at"`
	NormalizedName string `json:"normalized_name"`
}

func (q *Queries) SetPilotNameWantError(ctx context.Context, arg SetPilotNameWantErrorParams) error {
	_, err := q.db.ExecContext(ctx, setPilotNameWantError, arg.ResolvedAt, arg.NextTryAt, arg.NormalizedName)
	return err
}

const setPilotNameWantMissing = `-- name: SetPilotNameWantMissing :exec
UPDATE pilot_name_wants
SET state = 'missing', resolved_at = $1, next_try_at = ''
WHERE normalized_name = $2
`

type SetPilotNameWantMissingParams struct {
	ResolvedAt     string `json:"resolved_at"`
	NormalizedName string `json:"normalized_name"`
}

func (q *Queries) SetPilotNameWantMissing(ctx context.Context, arg SetPilotNameWantMissingParams) error {
	_, err := q.db.ExecContext(ctx, setPilotNameWantMissing, arg.ResolvedAt, arg.NormalizedName)
	return err
}

const setPilotNameWantReady = `-- name: SetPilotNameWantReady :exec
UPDATE pilot_name_wants
SET state = 'ready', character_id = $1, resolved_at = $2, next_try_at = ''
WHERE normalized_name = $3
`

type SetPilotNameWantReadyParams struct {
	CharacterID    int64  `json:"character_id"`
	ResolvedAt     string `json:"resolved_at"`
	NormalizedName string `json:"normalized_name"`
}

func (q *Queries) SetPilotNameWantReady(ctx context.Context, arg SetPilotNameWantReadyParams) error {
	_, err := q.db.ExecContext(ctx, setPilotNameWantReady, arg.CharacterID, arg.ResolvedAt, arg.NormalizedName)
	return err
}

const setPilotRecord = `-- name: SetPilotRecord :exec
INSERT INTO pilot_records (character_id, payload, state, fetched_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (character_id) DO UPDATE SET
    payload    = excluded.payload,
    state      = excluded.state,
    fetched_at = excluded.fetched_at
`

type SetPilotRecordParams struct {
	CharacterID int64  `json:"character_id"`
	Payload     string `json:"payload"`
	State       string `json:"state"`
	FetchedAt   string `json:"fetched_at"`
}

func (q *Queries) SetPilotRecord(ctx context.Context, arg SetPilotRecordParams) error {
	_, err := q.db.ExecContext(ctx, setPilotRecord,
		arg.CharacterID,
		arg.Payload,
		arg.State,
		arg.FetchedAt,
	)
	return err
}

const setPlanetName = `-- name: SetPlanetName :exec
INSERT INTO planet_names (planet_id, name, state, resolved_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (planet_id) DO UPDATE SET
    name        = excluded.name,
    state       = excluded.state,
    resolved_at = excluded.resolved_at
`

type SetPlanetNameParams struct {
	PlanetID   int64  `json:"planet_id"`
	Name       string `json:"name"`
	State      string `json:"state"`
	ResolvedAt string `json:"resolved_at"`
}

func (q *Queries) SetPlanetName(ctx context.Context, arg SetPlanetNameParams) error {
	_, err := q.db.ExecContext(ctx, setPlanetName,
		arg.PlanetID,
		arg.Name,
		arg.State,
		arg.ResolvedAt,
	)
	return err
}

const setStructureContext = `-- name: SetStructureContext :exec
INSERT INTO structure_context (structure_id, owner_corporation_id, system_id, type_id, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (structure_id) DO UPDATE SET
    owner_corporation_id = excluded.owner_corporation_id,
    system_id            = excluded.system_id,
    type_id              = excluded.type_id,
    updated_at           = excluded.updated_at
`

type SetStructureContextParams struct {
	StructureID        int64  `json:"structure_id"`
	OwnerCorporationID int64  `json:"owner_corporation_id"`
	SystemID           int64  `json:"system_id"`
	TypeID             int64  `json:"type_id"`
	UpdatedAt          string `json:"updated_at"`
}

func (q *Queries) SetStructureContext(ctx context.Context, arg SetStructureContextParams) error {
	_, err := q.db.ExecContext(ctx, setStructureContext,
		arg.StructureID,
		arg.OwnerCorporationID,
		arg.SystemID,
		arg.TypeID,
		arg.UpdatedAt,
	)
	return err
}

const setStructureName = `-- name: SetStructureName :exec
INSERT INTO structure_names (structure_id, name, state, resolved_at, source)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (structure_id) DO UPDATE SET
    name        = excluded.name,
    state       = excluded.state,
    resolved_at = excluded.resolved_at,
    source      = excluded.source
`

type SetStructureNameParams struct {
	StructureID int64  `json:"structure_id"`
	Name        string `json:"name"`
	State       string `json:"state"`
	ResolvedAt  string `json:"resolved_at"`
	Source      string `json:"source"`
}

func (q *Queries) SetStructureName(ctx context.Context, arg SetStructureNameParams) error {
	_, err := q.db.ExecContext(ctx, setStructureName,
		arg.StructureID,
		arg.Name,
		arg.State,
		arg.ResolvedAt,
		arg.Source,
	)
	return err
}

const updateMarketSweepState = `-- name: UpdateMarketSweepState :exec
UPDATE market_sweep_state
SET next_page = $1, pages_total = $2, updated_at = $3
WHERE region_id = $4
`

type UpdateMarketSweepStateParams struct {
	NextPage   int64     `json:"next_page"`
	PagesTotal int64     `json:"pages_total"`
	UpdatedAt  time.Time `json:"updated_at"`
	RegionID   int64     `json:"region_id"`
}

func (q *Queries) UpdateMarketSweepState(ctx context.Context, arg UpdateMarketSweepStateParams) error {
	_, err := q.db.ExecContext(ctx, updateMarketSweepState,
		arg.NextPage,
		arg.PagesTotal,
		arg.UpdatedAt,
		arg.RegionID,
	)
	return err
}

const updateOrderLifecycleBeaten = `-- name: UpdateOrderLifecycleBeaten :exec
UPDATE order_lifecycle
SET beaten_now = $1, outbid_events = $2
WHERE character_id = $3 AND order_id = $4 AND closed_at IS NULL
`

type UpdateOrderLifecycleBeatenParams struct {
	BeatenNow    int64 `json:"beaten_now"`
	OutbidEvents int64 `json:"outbid_events"`
	CharacterID  int64 `json:"character_id"`
	OrderID      int64 `json:"order_id"`
}

func (q *Queries) UpdateOrderLifecycleBeaten(ctx context.Context, arg UpdateOrderLifecycleBeatenParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderLifecycleBeaten,
		arg.BeatenNow,
		arg.OutbidEvents,
		arg.CharacterID,
		arg.OrderID,
	)
	return err
}

const upsertAllianceWant = `-- name: UpsertAllianceWant :exec
INSERT INTO alliance_records (alliance_id, priority)
VALUES ($1, 1)
ON CONFLICT (alliance_id) DO UPDATE SET priority = GREATEST(alliance_records.priority, 1)
`

func (q *Queries) UpsertAllianceWant(ctx context.Context, allianceID int64) error {
	_, err := q.db.ExecContext(ctx, upsertAllianceWant, allianceID)
	return err
}

const upsertCorporationWant = `-- name: UpsertCorporationWant :exec
INSERT INTO corporation_records (corporation_id, priority)
VALUES ($1, 1)
ON CONFLICT (corporation_id) DO UPDATE SET priority = GREATEST(corporation_records.priority, 1)
`

func (q *Queries) UpsertCorporationWant(ctx context.Context, corporationID int64) error {
	_, err := q.db.ExecContext(ctx, upsertCorporationWant, corporationID)
	return err
}

const upsertGuidePrice = `-- name: UpsertGuidePrice :exec
INSERT INTO guide_prices (type_id, adjusted_price, average_price)
VALUES ($1, $2, $3)
ON CONFLICT (type_id) DO UPDATE SET
    adjusted_price = excluded.adjusted_price,
    average_price  = excluded.average_price
`

type UpsertGuidePriceParams struct {
	TypeID        int64   `json:"type_id"`
	AdjustedPrice float64 `json:"adjusted_price"`
	AveragePrice  float64 `json:"average_price"`
}

func (q *Queries) UpsertGuidePrice(ctx context.Context, arg UpsertGuidePriceParams) error {
	_, err := q.db.ExecContext(ctx, upsertGuidePrice, arg.TypeID, arg.AdjustedPrice, arg.AveragePrice)
	return err
}

const upsertGuidePricesMeta = `-- name: UpsertGuidePricesMeta :exec
INSERT INTO guide_prices_meta (id, fetched_at, cached_until)
VALUES (1, $1, $2)
ON CONFLICT (id) DO UPDATE SET
    fetched_at   = excluded.fetched_at,
    cached_until = excluded.cached_until
`

type UpsertGuidePricesMetaParams struct {
	FetchedAt   time.Time `json:"fetched_at"`
	CachedUntil time.Time `json:"cached_until"`
}

func (q *Queries) UpsertGuidePricesMeta(ctx context.Context, arg UpsertGuidePricesMetaParams) error {
	_, err := q.db.ExecContext(ctx, upsertGuidePricesMeta, arg.FetchedAt, arg.CachedUntil)
	return err
}

const upsertIndustryCostIndex = `-- name: UpsertIndustryCostIndex :exec
INSERT INTO industry_cost_indices (solar_system_id, activity, cost_index, fetched_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (solar_system_id, activity) DO UPDATE SET
    cost_index = excluded.cost_index,
    fetched_at = excluded.fetched_at
`

type UpsertIndustryCostIndexParams struct {
	SolarSystemID int64   `json:"solar_system_id"`
	Activity      string  `json:"activity"`
	CostIndex     float64 `json:"cost_index"`
}

// v0.3.33: industry cost indices per (system, activity).
func (q *Queries) UpsertIndustryCostIndex(ctx context.Context, arg UpsertIndustryCostIndexParams) error {
	_, err := q.db.ExecContext(ctx, upsertIndustryCostIndex, arg.SolarSystemID, arg.Activity, arg.CostIndex)
	return err
}

const upsertMarketFetchState = `-- name: UpsertMarketFetchState :exec
INSERT INTO market_fetch_state (kind, state, detail, attempted_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (kind) DO UPDATE SET
    state        = excluded.state,
    detail       = excluded.detail,
    attempted_at = excluded.attempted_at
`

type UpsertMarketFetchStateParams struct {
	Kind        string    `json:"kind"`
	State       string    `json:"state"`
	Detail      string    `json:"detail"`
	AttemptedAt time.Time `json:"attempted_at"`
}

func (q *Queries) UpsertMarketFetchState(ctx context.Context, arg UpsertMarketFetchStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketFetchState,
		arg.Kind,
		arg.State,
		arg.Detail,
		arg.AttemptedAt,
	)
	return err
}

const upsertMarketHistory = `-- name: UpsertMarketHistory :exec
INSERT INTO market_history (region_id, type_id, date, average, highest, lowest, volume, order_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (region_id, type_id, date) DO UPDATE SET
    average     = excluded.average,
    highest     = excluded.highest,
    lowest      = excluded.lowest,
    volume      = excluded.volume,
    order_count = excluded.order_count
`

type UpsertMarketHistoryParams struct {
	RegionID   int64   `json:"region_id"`
	TypeID     int64   `json:"type_id"`
	Date       string  `json:"date"`
	Average    float64 `json:"average"`
	Highest    float64 `json:"highest"`
	Lowest     float64 `json:"lowest"`
	Volume     int64   `json:"volume"`
	OrderCount int64   `json:"order_count"`
}

// ---------------------------------------------------------------------
// Phase 3 (schema 011): industry build planner reads. Bulk import
// inserts stay hand-rolled in the SDE importer alongside the other
// sde_* tables; only reads live here.
// ---------------------------------------------------------------------
func (q *Queries) UpsertMarketHistory(ctx context.Context, arg UpsertMarketHistoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketHistory,
		arg.RegionID,
		arg.TypeID,
		arg.Date,
		arg.Average,
		arg.Highest,
		arg.Lowest,
		arg.Volume,
		arg.OrderCount,
	)
	return err
}

const upsertMarketHistoryWant = `-- name: UpsertMarketHistoryWant :exec
INSERT INTO market_history_wants (region_id, type_id, last_requested_at)
VALUES ($1, $2, $3)
ON CONFLICT (region_id, type_id) DO UPDATE SET
    last_requested_at = excluded.last_requested_at
`

type UpsertMarketHistoryWantParams struct {
	RegionID        int64     `json:"region_id"`
	TypeID          int64     `json:"type_id"`
	LastRequestedAt time.Time `json:"last_requested_at"`
}

func (q *Queries) UpsertMarketHistoryWant(ctx context.Context, arg UpsertMarketHistoryWantParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketHistoryWant, arg.RegionID, arg.TypeID, arg.LastRequestedAt)
	return err
}

const upsertMarketRegionStat = `-- name: UpsertMarketRegionStat :exec
INSERT INTO market_region_stats (region_id, type_id, best_sell, typical_sell, sell_band, best_buy, typical_buy, buy_band, sell_orders, buy_orders, sell_volume, buy_volume, avg_daily_volume, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (region_id, type_id) DO UPDATE SET
    best_sell    = excluded.best_sell,
    typical_sell = excluded.typical_sell,
    sell_band    = excluded.sell_band,
    best_buy     = excluded.best_buy,
    typical_buy  = excluded.typical_buy,
    buy_band     = excluded.buy_band,
    sell_orders  = excluded.sell_orders,
    buy_orders   = excluded.buy_orders,
    sell_volume  = excluded.sell_volume,
    buy_volume   = excluded.buy_volume,
    avg_daily_volume = excluded.avg_daily_volume,
    updated_at   = excluded.updated_at
`

type UpsertMarketRegionStatParams struct {
	RegionID       int64     `json:"region_id"`
	TypeID         int64     `json:"type_id"`
	BestSell       float64   `json:"best_sell"`
	TypicalSell    float64   `json:"typical_sell"`
	SellBand       float64   `json:"sell_band"`
	BestBuy        float64   `json:"best_buy"`
	TypicalBuy     float64   `json:"typical_buy"`
	BuyBand        float64   `json:"buy_band"`
	SellOrders     int64     `json:"sell_orders"`
	BuyOrders      int64     `json:"buy_orders"`
	SellVolume     int64     `json:"sell_volume"`
	BuyVolume      int64     `json:"buy_volume"`
	AvgDailyVolume float64   `json:"avg_daily_volume"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) UpsertMarketRegionStat(ctx context.Context, arg UpsertMarketRegionStatParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketRegionStat,
		arg.RegionID,
		arg.TypeID,
		arg.BestSell,
		arg.TypicalSell,
		arg.SellBand,
		arg.BestBuy,
		arg.TypicalBuy,
		arg.BuyBand,
		arg.SellOrders,
		arg.BuyOrders,
		arg.SellVolume,
		arg.BuyVolume,
		arg.AvgDailyVolume,
		arg.UpdatedAt,
	)
	return err
}

const upsertMarketRegionStatDaily = `-- name: UpsertMarketRegionStatDaily :exec
INSERT INTO market_region_stats_daily (region_id, type_id, day, best_sell, typical_sell, sell_band, best_buy, typical_buy, buy_band, sell_orders, buy_orders, sell_volume, buy_volume)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (region_id, type_id, day) DO UPDATE SET
    best_sell    = excluded.best_sell,
    typical_sell = excluded.typical_sell,
    sell_band    = excluded.sell_band,
    best_buy     = excluded.best_buy,
    typical_buy  = excluded.typical_buy,
    buy_band     = excluded.buy_band,
    sell_orders  = excluded.sell_orders,
    buy_orders   = excluded.buy_orders,
    sell_volume  = excluded.sell_volume,
    buy_volume   = excluded.buy_volume
`

type UpsertMarketRegionStatDailyParams struct {
	RegionID    int64   `json:"region_id"`
	TypeID      int64   `json:"type_id"`
	Day         string  `json:"day"`
	BestSell    float64 `json:"best_sell"`
	TypicalSell float64 `json:"typical_sell"`
	SellBand    float64 `json:"sell_band"`
	BestBuy     float64 `json:"best_buy"`
	TypicalBuy  float64 `json:"typical_buy"`
	BuyBand     float64 `json:"buy_band"`
	SellOrders  int64   `json:"sell_orders"`
	BuyOrders   int64   `json:"buy_orders"`
	SellVolume  int64   `json:"sell_volume"`
	BuyVolume   int64   `json:"buy_volume"`
}

func (q *Queries) UpsertMarketRegionStatDaily(ctx context.Context, arg UpsertMarketRegionStatDailyParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketRegionStatDaily,
		arg.RegionID,
		arg.TypeID,
		arg.Day,
		arg.BestSell,
		arg.TypicalSell,
		arg.SellBand,
		arg.BestBuy,
		arg.TypicalBuy,
		arg.BuyBand,
		arg.SellOrders,
		arg.BuyOrders,
		arg.SellVolume,
		arg.BuyVolume,
	)
	return err
}

const upsertMarketStationLeaderboard = `-- name: UpsertMarketStationLeaderboard :exec
INSERT INTO market_station_leaderboard (region_id, location_id, sell_orders, buy_orders, sell_value, buy_value, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (region_id, location_id) DO UPDATE SET
    sell_orders = excluded.sell_orders,
    buy_orders  = excluded.buy_orders,
    sell_value  = excluded.sell_value,
    buy_value   = excluded.buy_value,
    updated_at  = excluded.updated_at
`

type UpsertMarketStationLeaderboardParams struct {
	RegionID   int64     `json:"region_id"`
	LocationID int64     `json:"location_id"`
	SellOrders int64     `json:"sell_orders"`
	BuyOrders  int64     `json:"buy_orders"`
	SellValue  float64   `json:"sell_value"`
	BuyValue   float64   `json:"buy_value"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) UpsertMarketStationLeaderboard(ctx context.Context, arg UpsertMarketStationLeaderboardParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketStationLeaderboard,
		arg.RegionID,
		arg.LocationID,
		arg.SellOrders,
		arg.BuyOrders,
		arg.SellValue,
		arg.BuyValue,
		arg.UpdatedAt,
	)
	return err
}

const upsertMarketStationStat = `-- name: UpsertMarketStationStat :exec
INSERT INTO market_station_stats (location_id, region_id, type_id, best_sell, best_buy, sell_orders, buy_orders, sell_volume, buy_volume, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (location_id, type_id) DO UPDATE SET
    region_id   = excluded.region_id,
    best_sell   = excluded.best_sell,
    best_buy    = excluded.best_buy,
    sell_orders = excluded.sell_orders,
    buy_orders  = excluded.buy_orders,
    sell_volume = excluded.sell_volume,
    buy_volume  = excluded.buy_volume,
    updated_at  = excluded.updated_at
`

type UpsertMarketStationStatParams struct {
	LocationID int64     `json:"location_id"`
	RegionID   int64     `json:"region_id"`
	TypeID     int64     `json:"type_id"`
	BestSell   float64   `json:"best_sell"`
	BestBuy    float64   `json:"best_buy"`
	SellOrders int64     `json:"sell_orders"`
	BuyOrders  int64     `json:"buy_orders"`
	SellVolume int64     `json:"sell_volume"`
	BuyVolume  int64     `json:"buy_volume"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) UpsertMarketStationStat(ctx context.Context, arg UpsertMarketStationStatParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketStationStat,
		arg.LocationID,
		arg.RegionID,
		arg.TypeID,
		arg.BestSell,
		arg.BestBuy,
		arg.SellOrders,
		arg.BuyOrders,
		arg.SellVolume,
		arg.BuyVolume,
		arg.UpdatedAt,
	)
	return err
}

const upsertMarketTypePrice = `-- name: UpsertMarketTypePrice :exec
INSERT INTO market_type_prices (region_id, type_id, buy_price, sell_price, buy_volume, sell_volume, fetched_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (region_id, type_id) DO UPDATE SET
    buy_price   = excluded.buy_price,
    sell_price  = excluded.sell_price,
    buy_volume  = excluded.buy_volume,
    sell_volume = excluded.sell_volume,
    fetched_at  = excluded.fetched_at
`

type UpsertMarketTypePriceParams struct {
	RegionID   int64   `json:"region_id"`
	TypeID     int64   `json:"type_id"`
	BuyPrice   float64 `json:"buy_price"`
	SellPrice  float64 `json:"sell_price"`
	BuyVolume  int64   `json:"buy_volume"`
	SellVolume int64   `json:"sell_volume"`
}

// v0.3.33: per-type market price TTL cache. The worker refreshes
// only rows older than the TTL; pages read cache-only.
func (q *Queries) UpsertMarketTypePrice(ctx context.Context, arg UpsertMarketTypePriceParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketTypePrice,
		arg.RegionID,
		arg.TypeID,
		arg.BuyPrice,
		arg.SellPrice,
		arg.BuyVolume,
		arg.SellVolume,
	)
	return err
}

const upsertOrderHealth = `-- name: UpsertOrderHealth :exec
INSERT INTO order_health (character_id, order_id, type_id, region_id, location_id, my_price, station_best, region_best, status, computed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (character_id, order_id) DO UPDATE SET
    type_id      = excluded.type_id,
    region_id    = excluded.region_id,
    location_id  = excluded.location_id,
    my_price     = excluded.my_price,
    station_best = excluded.station_best,
    region_best  = excluded.region_best,
    status       = excluded.status,
    computed_at  = excluded.computed_at
`

type UpsertOrderHealthParams struct {
	CharacterID int64     `json:"character_id"`
	OrderID     int64     `json:"order_id"`
	TypeID      int64     `json:"type_id"`
	RegionID    int64     `json:"region_id"`
	LocationID  int64     `json:"location_id"`
	MyPrice     float64   `json:"my_price"`
	StationBest float64   `json:"station_best"`
	RegionBest  float64   `json:"region_best"`
	Status      string    `json:"status"`
	ComputedAt  time.Time `json:"computed_at"`
}

func (q *Queries) UpsertOrderHealth(ctx context.Context, arg UpsertOrderHealthParams) error {
	_, err := q.db.ExecContext(ctx, upsertOrderHealth,
		arg.CharacterID,
		arg.OrderID,
		arg.TypeID,
		arg.RegionID,
		arg.LocationID,
		arg.MyPrice,
		arg.StationBest,
		arg.RegionBest,
		arg.Status,
		arg.ComputedAt,
	)
	return err
}

const upsertOrderLifecycle = `-- name: UpsertOrderLifecycle :exec
INSERT INTO order_lifecycle (character_id, order_id, type_id, location_id, region_id, is_buy_order, listed_price, volume_total, volume_remain_last, first_seen_at, last_seen_at, closed_at, close_kind, outbid_events, beaten_now)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NULL, '', 0, 0)
ON CONFLICT (character_id, order_id) DO UPDATE SET
    type_id            = excluded.type_id,
    location_id        = excluded.location_id,
    region_id          = excluded.region_id,
    is_buy_order       = excluded.is_buy_order,
    listed_price       = excluded.listed_price,
    volume_total       = excluded.volume_total,
    volume_remain_last = excluded.volume_remain_last,
    last_seen_at       = excluded.last_seen_at
`

type UpsertOrderLifecycleParams struct {
	CharacterID      int64     `json:"character_id"`
	OrderID          int64     `json:"order_id"`
	TypeID           int64     `json:"type_id"`
	LocationID       int64     `json:"location_id"`
	RegionID         int64     `json:"region_id"`
	IsBuyOrder       int64     `json:"is_buy_order"`
	ListedPrice      float64   `json:"listed_price"`
	VolumeTotal      int64     `json:"volume_total"`
	VolumeRemainLast int64     `json:"volume_remain_last"`
	FirstSeenAt      time.Time `json:"first_seen_at"`
	LastSeenAt       time.Time `json:"last_seen_at"`
}

func (q *Queries) UpsertOrderLifecycle(ctx context.Context, arg UpsertOrderLifecycleParams) error {
	_, err := q.db.ExecContext(ctx, upsertOrderLifecycle,
		arg.CharacterID,
		arg.OrderID,
		arg.TypeID,
		arg.LocationID,
		arg.RegionID,
		arg.IsBuyOrder,
		arg.ListedPrice,
		arg.VolumeTotal,
		arg.VolumeRemainLast,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	return err
}

const upsertPilotNameWant = `-- name: UpsertPilotNameWant :exec
INSERT INTO pilot_name_wants (normalized_name, display_name, state, requested_at)
VALUES ($1, $2, 'pending', $3)
ON CONFLICT DO NOTHING
`

type UpsertPilotNameWantParams struct {
	NormalizedName string `json:"normalized_name"`
	DisplayName    string `json:"display_name"`
	RequestedAt    string `json:"requested_at"`
}

func (q *Queries) UpsertPilotNameWant(ctx context.Context, arg UpsertPilotNameWantParams) error {
	_, err := q.db.ExecContext(ctx, upsertPilotNameWant, arg.NormalizedName, arg.DisplayName, arg.RequestedAt)
	return err
}

const upsertPilotWant = `-- name: UpsertPilotWant :exec
INSERT INTO pilot_records (character_id, priority)
VALUES ($1, 1)
ON CONFLICT (character_id) DO UPDATE SET priority = GREATEST(pilot_records.priority, 1)
`

func (q *Queries) UpsertPilotWant(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, upsertPilotWant, characterID)
	return err
}

const upsertPlanetSeen = `-- name: UpsertPlanetSeen :exec
INSERT INTO planet_names (planet_id)
VALUES ($1)
ON CONFLICT DO NOTHING
`

func (q *Queries) UpsertPlanetSeen(ctx context.Context, planetID int64) error {
	_, err := q.db.ExecContext(ctx, upsertPlanetSeen, planetID)
	return err
}

const upsertRestockTarget = `-- name: UpsertRestockTarget :exec
INSERT INTO restock_targets (user_id, type_id, target_qty, min_margin_pct, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id, type_id) DO UPDATE SET
    target_qty     = excluded.target_qty,
    min_margin_pct = excluded.min_margin_pct,
    updated_at     = excluded.updated_at
`

type UpsertRestockTargetParams struct {
	UserID       int64   `json:"user_id"`
	TypeID       int64   `json:"type_id"`
	TargetQty    int64   `json:"target_qty"`
	MinMarginPct float64 `json:"min_margin_pct"`
}

// v0.3.34: restock planner targets.
func (q *Queries) UpsertRestockTarget(ctx context.Context, arg UpsertRestockTargetParams) error {
	_, err := q.db.ExecContext(ctx, upsertRestockTarget,
		arg.UserID,
		arg.TypeID,
		arg.TargetQty,
		arg.MinMarginPct,
	)
	return err
}

const upsertStructureSeen = `-- name: UpsertStructureSeen :exec
INSERT INTO structure_names (structure_id)
VALUES ($1)
ON CONFLICT DO NOTHING
`

func (q *Queries) UpsertStructureSeen(ctx context.Context, structureID int64) error {
	_, err := q.db.ExecContext(ctx, upsertStructureSeen, structureID)
	return err
}

const upsertWatchlistEntry = `-- name: UpsertWatchlistEntry :exec
INSERT INTO market_watchlist (user_id, type_id, region_id, threshold_pct, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, type_id, region_id) DO UPDATE SET
    threshold_pct = excluded.threshold_pct
`

type UpsertWatchlistEntryParams struct {
	UserID       int64     `json:"user_id"`
	TypeID       int64     `json:"type_id"`
	RegionID     int64     `json:"region_id"`
	ThresholdPct float64   `json:"threshold_pct"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) UpsertWatchlistEntry(ctx context.Context, arg UpsertWatchlistEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertWatchlistEntry,
		arg.UserID,
		arg.TypeID,
		arg.RegionID,
		arg.ThresholdPct,
		arg.CreatedAt,
	)
	return err
}
