// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (created_at)
VALUES (datetime('now'))
RETURNING id, created_at
`

func (q *Queries) CreateUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser)
	var i User
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters
WHERE character_id = ? AND user_id = ?
`

type DeleteCharacterParams struct {
	CharacterID int64 `json:"character_id"`
	UserID      int64 `json:"user_id"`
}

func (q *Queries) DeleteCharacter(ctx context.Context, arg DeleteCharacterParams) error {
	_, err := q.db.ExecContext(ctx, deleteCharacter, arg.CharacterID, arg.UserID)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT character_id, user_id, name, access_token, refresh_token, token_expiry, scopes, cached_until, created_at, updated_at FROM characters
WHERE character_id = ?
`

func (q *Queries) GetCharacter(ctx context.Context, characterID int64) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, characterID)
	var i Character
	err := row.Scan(
		&i.CharacterID,
		&i.UserID,
		&i.Name,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.Scopes,
		&i.CachedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at FROM users
WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listCharactersByUser = `-- name: ListCharactersByUser :many
SELECT character_id, user_id, name, access_token, refresh_token, token_expiry, scopes, cached_until, created_at, updated_at FROM characters
WHERE user_id = ?
ORDER BY name
`

func (q *Queries) ListCharactersByUser(ctx context.Context, userID int64) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listCharactersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.CharacterID,
			&i.UserID,
			&i.Name,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiry,
			&i.Scopes,
			&i.CachedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCharacter = `-- name: UpsertCharacter :one
INSERT INTO characters (
    character_id, user_id, name,
    access_token, refresh_token, token_expiry,
    scopes, cached_until, updated_at
) VALUES (
    ?, ?, ?,
    ?, ?, ?,
    ?, ?, datetime('now')
)
ON CONFLICT (character_id) DO UPDATE SET
    user_id       = excluded.user_id,
    name          = excluded.name,
    access_token  = excluded.access_token,
    refresh_token = excluded.refresh_token,
    token_expiry  = excluded.token_expiry,
    scopes        = excluded.scopes,
    cached_until  = excluded.cached_until,
    updated_at    = excluded.updated_at
RETURNING character_id, user_id, name, access_token, refresh_token, token_expiry, scopes, cached_until, created_at, updated_at
`

type UpsertCharacterParams struct {
	CharacterID  int64          `json:"character_id"`
	UserID       int64          `json:"user_id"`
	Name         string         `json:"name"`
	AccessToken  string         `json:"access_token"`
	RefreshToken string         `json:"refresh_token"`
	TokenExpiry  sql.NullString `json:"token_expiry"`
	Scopes       string         `json:"scopes"`
	CachedUntil  sql.NullString `json:"cached_until"`
}

func (q *Queries) UpsertCharacter(ctx context.Context, arg UpsertCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, upsertCharacter,
		arg.CharacterID,
		arg.UserID,
		arg.Name,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
		arg.Scopes,
		arg.CachedUntil,
	)
	var i Character
	err := row.Scan(
		&i.CharacterID,
		&i.UserID,
		&i.Name,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.Scopes,
		&i.CachedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
