// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const countWarDetails = `-- name: CountWarDetails :one
SELECT COUNT(*) FROM war_details
`

func (q *Queries) CountWarDetails(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWarDetails)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocalFitting = `-- name: CreateLocalFitting :one
INSERT INTO local_fittings (user_id, name, ship_type_id, items_json, is_public, is_draft, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, ship_type_id, items_json, is_public, is_draft, created_at, updated_at
`

type CreateLocalFittingParams struct {
	UserID     int64     `json:"user_id"`
	Name       string    `json:"name"`
	ShipTypeID int64     `json:"ship_type_id"`
	ItemsJson  string    `json:"items_json"`
	IsPublic   bool      `json:"is_public"`
	IsDraft    bool      `json:"is_draft"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type CreateLocalFittingRow struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	Name       string    `json:"name"`
	ShipTypeID int64     `json:"ship_type_id"`
	ItemsJson  string    `json:"items_json"`
	IsPublic   bool      `json:"is_public"`
	IsDraft    bool      `json:"is_draft"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// ---------------------------------------------------------------------
// Fitting simulator (schema 030): fits built in the editor, stored
// per user. items_json is the whole fit document (ship, item lines,
// charge choices); reads/writes always scope to the owning user.
// ---------------------------------------------------------------------
func (q *Queries) CreateLocalFitting(ctx context.Context, arg CreateLocalFittingParams) (CreateLocalFittingRow, error) {
	row := q.db.QueryRowContext(ctx, createLocalFitting,
		arg.UserID,
		arg.Name,
		arg.ShipTypeID,
		arg.ItemsJson,
		arg.IsPublic,
		arg.IsDraft,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateLocalFittingRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ShipTypeID,
		&i.ItemsJson,
		&i.IsPublic,
		&i.IsDraft,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSkillPlan = `-- name: CreateSkillPlan :one
INSERT INTO skill_plans (user_id, character_id, name, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, character_id, name, created_at
`

type CreateSkillPlanParams struct {
	UserID      int64     `json:"user_id"`
	CharacterID int64     `json:"character_id"`
	Name        string    `json:"name"`
	CreatedAt   time.Time `json:"created_at"`
}

// ---------------------------------------------------------------------
// v0.3.04 stored market guide (schema 021): the worker mirrors
// GET /markets/prices/ here wholesale (delete + insert inside
// one transaction) so asset valuation never waits on a Market
// page visit. Meta is the single bookkeeping row.
// ---------------------------------------------------------------------
func (q *Queries) CreateSkillPlan(ctx context.Context, arg CreateSkillPlanParams) (SkillPlan, error) {
	row := q.db.QueryRowContext(ctx, createSkillPlan,
		arg.UserID,
		arg.CharacterID,
		arg.Name,
		arg.CreatedAt,
	)
	var i SkillPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CharacterID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (created_at)
VALUES (now())
RETURNING id, created_at, home_layout, last_briefing_at
`

func (q *Queries) CreateUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.HomeLayout,
		&i.LastBriefingAt,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters
WHERE character_id = $1 AND user_id = $2
`

type DeleteCharacterParams struct {
	CharacterID int64 `json:"character_id"`
	UserID      int64 `json:"user_id"`
}

func (q *Queries) DeleteCharacter(ctx context.Context, arg DeleteCharacterParams) error {
	_, err := q.db.ExecContext(ctx, deleteCharacter, arg.CharacterID, arg.UserID)
	return err
}

const deleteCloneName = `-- name: DeleteCloneName :exec
DELETE FROM clone_names
WHERE user_id = $1 AND character_id = $2 AND clone_id = $3
`

type DeleteCloneNameParams struct {
	UserID      int64 `json:"user_id"`
	CharacterID int64 `json:"character_id"`
	CloneID     int64 `json:"clone_id"`
}

func (q *Queries) DeleteCloneName(ctx context.Context, arg DeleteCloneNameParams) error {
	_, err := q.db.ExecContext(ctx, deleteCloneName, arg.UserID, arg.CharacterID, arg.CloneID)
	return err
}

const deleteLocalFitting = `-- name: DeleteLocalFitting :exec
DELETE FROM local_fittings WHERE id = $1 AND user_id = $2
`

type DeleteLocalFittingParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteLocalFitting(ctx context.Context, arg DeleteLocalFittingParams) error {
	_, err := q.db.ExecContext(ctx, deleteLocalFitting, arg.ID, arg.UserID)
	return err
}

const deleteSkillPlan = `-- name: DeleteSkillPlan :exec
DELETE FROM skill_plans WHERE id = $1 AND user_id = $2
`

type DeleteSkillPlanParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteSkillPlan(ctx context.Context, arg DeleteSkillPlanParams) error {
	_, err := q.db.ExecContext(ctx, deleteSkillPlan, arg.ID, arg.UserID)
	return err
}

const deleteSkillPlanItem = `-- name: DeleteSkillPlanItem :exec
DELETE FROM skill_plan_items WHERE plan_id = $1 AND skill_type_id = $2
`

type DeleteSkillPlanItemParams struct {
	PlanID      int64 `json:"plan_id"`
	SkillTypeID int64 `json:"skill_type_id"`
}

func (q *Queries) DeleteSkillPlanItem(ctx context.Context, arg DeleteSkillPlanItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteSkillPlanItem, arg.PlanID, arg.SkillTypeID)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT character_id, user_id, name, access_token, refresh_token, token_expiry, scopes, cached_until, created_at, updated_at, owner_hash, tags, link_state, link_state_at FROM characters
WHERE character_id = $1
`

func (q *Queries) GetCharacter(ctx context.Context, characterID int64) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, characterID)
	var i Character
	err := row.Scan(
		&i.CharacterID,
		&i.UserID,
		&i.Name,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.Scopes,
		&i.CachedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerHash,
		&i.Tags,
		&i.LinkState,
		&i.LinkStateAt,
	)
	return i, err
}

const getCharacterCorporation = `-- name: GetCharacterCorporation :one
SELECT character_id, corporation_id, updated_at FROM character_corporations
WHERE character_id = $1
`

func (q *Queries) GetCharacterCorporation(ctx context.Context, characterID int64) (CharacterCorporation, error) {
	row := q.db.QueryRowContext(ctx, getCharacterCorporation, characterID)
	var i CharacterCorporation
	err := row.Scan(&i.CharacterID, &i.CorporationID, &i.UpdatedAt)
	return i, err
}

const getContractDetail = `-- name: GetContractDetail :one
SELECT contract_id, character_id, payload, fetched_at FROM contract_details
WHERE contract_id = $1
`

// ---------------------------------------------------------------------
// Module sweep, cluster 3 (schema 006): contract detail store. The
// worker warms contract item lists from the contracts snapshot;
// pages only read here.
// ---------------------------------------------------------------------
func (q *Queries) GetContractDetail(ctx context.Context, contractID int64) (ContractDetail, error) {
	row := q.db.QueryRowContext(ctx, getContractDetail, contractID)
	var i ContractDetail
	err := row.Scan(
		&i.ContractID,
		&i.CharacterID,
		&i.Payload,
		&i.FetchedAt,
	)
	return i, err
}

const getGlobalSnapshot = `-- name: GetGlobalSnapshot :one
SELECT kind, payload, fetched_at, cached_until, etag FROM global_snapshots
WHERE kind = $1
`

// ---------------------------------------------------------------------
// Module sweep, cluster 4 (schema 007): intel public-data store.
// Global snapshots are the public-data counterpart of
// character_snapshots; war details mirror killmail_details.
// ---------------------------------------------------------------------
func (q *Queries) GetGlobalSnapshot(ctx context.Context, kind string) (GlobalSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getGlobalSnapshot, kind)
	var i GlobalSnapshot
	err := row.Scan(
		&i.Kind,
		&i.Payload,
		&i.FetchedAt,
		&i.CachedUntil,
		&i.Etag,
	)
	return i, err
}

const getKillmailDetail = `-- name: GetKillmailDetail :one
SELECT killmail_id, character_id, hash, payload, fetched_at FROM killmail_details
WHERE killmail_id = $1
`

func (q *Queries) GetKillmailDetail(ctx context.Context, killmailID int64) (KillmailDetail, error) {
	row := q.db.QueryRowContext(ctx, getKillmailDetail, killmailID)
	var i KillmailDetail
	err := row.Scan(
		&i.KillmailID,
		&i.CharacterID,
		&i.Hash,
		&i.Payload,
		&i.FetchedAt,
	)
	return i, err
}

const getLocalFitting = `-- name: GetLocalFitting :one
SELECT id, user_id, name, ship_type_id, items_json, is_public, is_draft, created_at, updated_at FROM local_fittings
WHERE id = $1 AND user_id = $2
`

type GetLocalFittingParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetLocalFittingRow struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	Name       string    `json:"name"`
	ShipTypeID int64     `json:"ship_type_id"`
	ItemsJson  string    `json:"items_json"`
	IsPublic   bool      `json:"is_public"`
	IsDraft    bool      `json:"is_draft"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) GetLocalFitting(ctx context.Context, arg GetLocalFittingParams) (GetLocalFittingRow, error) {
	row := q.db.QueryRowContext(ctx, getLocalFitting, arg.ID, arg.UserID)
	var i GetLocalFittingRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ShipTypeID,
		&i.ItemsJson,
		&i.IsPublic,
		&i.IsDraft,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicFitting = `-- name: GetPublicFitting :one
SELECT lf.id, lf.user_id, lf.name, lf.ship_type_id, lf.items_json, lf.updated_at,
       COALESCE((SELECT c.name FROM characters c WHERE c.user_id = lf.user_id ORDER BY c.character_id LIMIT 1), '') AS author_name
FROM local_fittings lf
WHERE lf.id = $1 AND lf.is_public AND NOT lf.is_draft
`

type GetPublicFittingRow struct {
	ID         int64       `json:"id"`
	UserID     int64       `json:"user_id"`
	Name       string      `json:"name"`
	ShipTypeID int64       `json:"ship_type_id"`
	ItemsJson  string      `json:"items_json"`
	UpdatedAt  time.Time   `json:"updated_at"`
	AuthorName interface{} `json:"author_name"`
}

func (q *Queries) GetPublicFitting(ctx context.Context, id int64) (GetPublicFittingRow, error) {
	row := q.db.QueryRowContext(ctx, getPublicFitting, id)
	var i GetPublicFittingRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ShipTypeID,
		&i.ItemsJson,
		&i.UpdatedAt,
		&i.AuthorName,
	)
	return i, err
}

const getSkillPlan = `-- name: GetSkillPlan :one
SELECT id, user_id, character_id, name, created_at FROM skill_plans
WHERE id = $1 AND user_id = $2
`

type GetSkillPlanParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetSkillPlan(ctx context.Context, arg GetSkillPlanParams) (SkillPlan, error) {
	row := q.db.QueryRowContext(ctx, getSkillPlan, arg.ID, arg.UserID)
	var i SkillPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CharacterID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT character_id, kind, payload, fetched_at, cached_until, etag FROM character_snapshots
WHERE character_id = $1 AND kind = $2
`

type GetSnapshotParams struct {
	CharacterID int64  `json:"character_id"`
	Kind        string `json:"kind"`
}

func (q *Queries) GetSnapshot(ctx context.Context, arg GetSnapshotParams) (CharacterSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshot, arg.CharacterID, arg.Kind)
	var i CharacterSnapshot
	err := row.Scan(
		&i.CharacterID,
		&i.Kind,
		&i.Payload,
		&i.FetchedAt,
		&i.CachedUntil,
		&i.Etag,
	)
	return i, err
}

const getSnapshotETag = `-- name: GetSnapshotETag :one
SELECT etag FROM character_snapshots
WHERE character_id = $1 AND kind = $2
`

type GetSnapshotETagParams struct {
	CharacterID int64  `json:"character_id"`
	Kind        string `json:"kind"`
}

// The ETag a snapshot was stored with (” when it has none), read
// without its payload: all a conditional refresh needs to send.
func (q *Queries) GetSnapshotETag(ctx context.Context, arg GetSnapshotETagParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotETag, arg.CharacterID, arg.Kind)
	var etag string
	err := row.Scan(&etag)
	return etag, err
}

const getSnapshotFetchState = `-- name: GetSnapshotFetchState :one
SELECT character_id, kind, state, detail, attempted_at FROM snapshot_fetch_state
WHERE character_id = $1 AND kind = $2
`

type GetSnapshotFetchStateParams struct {
	CharacterID int64  `json:"character_id"`
	Kind        string `json:"kind"`
}

// ---------------------------------------------------------------------
// Module sweep, cluster 2 (schema 005): corporation support.
// Fetch-outcome log (role-missing state), character-to-corporation
// map, and player-given item names.
// ---------------------------------------------------------------------
func (q *Queries) GetSnapshotFetchState(ctx context.Context, arg GetSnapshotFetchStateParams) (SnapshotFetchState, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotFetchState, arg.CharacterID, arg.Kind)
	var i SnapshotFetchState
	err := row.Scan(
		&i.CharacterID,
		&i.Kind,
		&i.State,
		&i.Detail,
		&i.AttemptedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, home_layout, last_briefing_at FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.HomeLayout,
		&i.LastBriefingAt,
	)
	return i, err
}

const getUserBriefingAnchor = `-- name: GetUserBriefingAnchor :one
SELECT last_briefing_at FROM users
WHERE id = $1
`

// Phase 6 (schema 017): the Briefing module's window anchor.
func (q *Queries) GetUserBriefingAnchor(ctx context.Context, id int64) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getUserBriefingAnchor, id)
	var last_briefing_at sql.NullTime
	err := row.Scan(&last_briefing_at)
	return last_briefing_at, err
}

const getUserDraftFitting = `-- name: GetUserDraftFitting :one
SELECT id, user_id, name, ship_type_id, items_json, is_public, is_draft, created_at, updated_at FROM local_fittings
WHERE user_id = $1 AND is_draft
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type GetUserDraftFittingRow struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	Name       string    `json:"name"`
	ShipTypeID int64     `json:"ship_type_id"`
	ItemsJson  string    `json:"items_json"`
	IsPublic   bool      `json:"is_public"`
	IsDraft    bool      `json:"is_draft"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) GetUserDraftFitting(ctx context.Context, userID int64) (GetUserDraftFittingRow, error) {
	row := q.db.QueryRowContext(ctx, getUserDraftFitting, userID)
	var i GetUserDraftFittingRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ShipTypeID,
		&i.ItemsJson,
		&i.IsPublic,
		&i.IsDraft,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserHomeLayout = `-- name: GetUserHomeLayout :one
SELECT home_layout FROM users
WHERE id = $1
`

// ---------------------------------------------------------------------
// Phase 1B home overview (schema 010): per-account widget layout and
// the one batched snapshot read every widget renders from.
// ---------------------------------------------------------------------
func (q *Queries) GetUserHomeLayout(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserHomeLayout, id)
	var home_layout string
	err := row.Scan(&home_layout)
	return home_layout, err
}

const getWalletHistorySample = `-- name: GetWalletHistorySample :one
SELECT user_id, character_id, day, balance, net_worth, sampled_at
FROM wallet_history
WHERE user_id = $1 AND character_id = $2 AND day = $3
`

type GetWalletHistorySampleParams struct {
	UserID      int64  `json:"user_id"`
	CharacterID int64  `json:"character_id"`
	Day         string `json:"day"`
}

// ---------------------------------------------------------------------
// Layout + market toolkit (schema 008): live market suggestions and
// the item database explorer. All local SDE reads. Matching uses
// strpos() rather than LIKE: case-insensitive substring positions
// (1 = a prefix match), no wildcard escaping to worry about.
// ---------------------------------------------------------------------
func (q *Queries) GetWalletHistorySample(ctx context.Context, arg GetWalletHistorySampleParams) (WalletHistory, error) {
	row := q.db.QueryRowContext(ctx, getWalletHistorySample, arg.UserID, arg.CharacterID, arg.Day)
	var i WalletHistory
	err := row.Scan(
		&i.UserID,
		&i.CharacterID,
		&i.Day,
		&i.Balance,
		&i.NetWorth,
		&i.SampledAt,
	)
	return i, err
}

const getWarDetail = `-- name: GetWarDetail :one
SELECT war_id, payload, fetched_at FROM war_details
WHERE war_id = $1
`

func (q *Queries) GetWarDetail(ctx context.Context, warID int64) (WarDetail, error) {
	row := q.db.QueryRowContext(ctx, getWarDetail, warID)
	var i WarDetail
	err := row.Scan(&i.WarID, &i.Payload, &i.FetchedAt)
	return i, err
}

const getWidgetConfig = `-- name: GetWidgetConfig :one
SELECT config FROM widget_configs
WHERE user_id = $1 AND widget_id = $2
`

type GetWidgetConfigParams struct {
	UserID   int64  `json:"user_id"`
	WidgetID string `json:"widget_id"`
}

// ---------------------------------------------------------------------
// v0.3.04 widget configuration (schema 020): one JSON blob per
// (user, widget). The layout (schema 010) owns placement; this
// owns behaviour (the orders widget's scope + merge mode first).
// ---------------------------------------------------------------------
func (q *Queries) GetWidgetConfig(ctx context.Context, arg GetWidgetConfigParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getWidgetConfig, arg.UserID, arg.WidgetID)
	var config string
	err := row.Scan(&config)
	return config, err
}

const listAllCharacters = `-- name: ListAllCharacters :many
SELECT character_id, user_id, name, access_token, refresh_token, token_expiry, scopes, cached_until, created_at, updated_at, owner_hash, tags, link_state, link_state_at FROM characters
ORDER BY user_id, name
`

func (q *Queries) ListAllCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listAllCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.CharacterID,
			&i.UserID,
			&i.Name,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiry,
			&i.Scopes,
			&i.CachedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerHash,
			&i.Tags,
			&i.LinkState,
			&i.LinkStateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCorporationIDs = `-- name: ListAllCorporationIDs :many
SELECT DISTINCT corporation_id FROM character_corporations
ORDER BY corporation_id
`

func (q *Queries) ListAllCorporationIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listAllCorporationIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var corporation_id int64
		if err := rows.Scan(&corporation_id); err != nil {
			return nil, err
		}
		items = append(items, corporation_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersByUser = `-- name: ListCharactersByUser :many
SELECT character_id, user_id, name, access_token, refresh_token, token_expiry, scopes, cached_until, created_at, updated_at, owner_hash, tags, link_state, link_state_at FROM characters
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListCharactersByUser(ctx context.Context, userID int64) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listCharactersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.CharacterID,
			&i.UserID,
			&i.Name,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiry,
			&i.Scopes,
			&i.CachedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerHash,
			&i.Tags,
			&i.LinkState,
			&i.LinkStateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCloneNames = `-- name: ListCloneNames :many
SELECT character_id, clone_id, custom_name
FROM clone_names
WHERE user_id = $1 AND character_id = $2
`

type ListCloneNamesParams struct {
	UserID      int64 `json:"user_id"`
	CharacterID int64 `json:"character_id"`
}

type ListCloneNamesRow struct {
	CharacterID int64  `json:"character_id"`
	CloneID     int64  `json:"clone_id"`
	CustomName  string `json:"custom_name"`
}

func (q *Queries) ListCloneNames(ctx context.Context, arg ListCloneNamesParams) ([]ListCloneNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCloneNames, arg.UserID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCloneNamesRow
	for rows.Next() {
		var i ListCloneNamesRow
		if err := rows.Scan(&i.CharacterID, &i.CloneID, &i.CustomName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractDetailIDsByCharacter = `-- name: ListContractDetailIDsByCharacter :many
SELECT contract_id FROM contract_details
WHERE character_id = $1
ORDER BY contract_id
`

func (q *Queries) ListContractDetailIDsByCharacter(ctx context.Context, characterID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listContractDetailIDsByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var contract_id int64
		if err := rows.Scan(&contract_id); err != nil {
			return nil, err
		}
		items = append(items, contract_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCorporationIDsByUser = `-- name: ListCorporationIDsByUser :many
SELECT DISTINCT cc.corporation_id
FROM character_corporations cc
JOIN characters c ON c.character_id = cc.character_id
WHERE c.user_id = $1
ORDER BY cc.corporation_id
`

// Every corporation the given user's characters belong to,
// from the worker-maintained character -> corporation map.
// Scoped to one user: per-user data stays siloed, so the
// wars page never flags another user's corporation as yours.
func (q *Queries) ListCorporationIDsByUser(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listCorporationIDsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var corporation_id int64
		if err := rows.Scan(&corporation_id); err != nil {
			return nil, err
		}
		items = append(items, corporation_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalSnapshots = `-- name: ListGlobalSnapshots :many
SELECT kind, payload, fetched_at, cached_until, etag FROM global_snapshots
ORDER BY kind
`

func (q *Queries) ListGlobalSnapshots(ctx context.Context) ([]GlobalSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalSnapshot
	for rows.Next() {
		var i GlobalSnapshot
		if err := rows.Scan(
			&i.Kind,
			&i.Payload,
			&i.FetchedAt,
			&i.CachedUntil,
			&i.Etag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKillmailDetailIDsByCharacter = `-- name: ListKillmailDetailIDsByCharacter :many
SELECT killmail_id FROM killmail_details
WHERE character_id = $1
ORDER BY killmail_id
`

func (q *Queries) ListKillmailDetailIDsByCharacter(ctx context.Context, characterID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listKillmailDetailIDsByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var killmail_id int64
		if err := rows.Scan(&killmail_id); err != nil {
			return nil, err
		}
		items = append(items, killmail_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKillmailDetailsByCharacter = `-- name: ListKillmailDetailsByCharacter :many
SELECT killmail_id, character_id, hash, payload, fetched_at FROM killmail_details
WHERE character_id = $1
ORDER BY killmail_id
`

func (q *Queries) ListKillmailDetailsByCharacter(ctx context.Context, characterID int64) ([]KillmailDetail, error) {
	rows, err := q.db.QueryContext(ctx, listKillmailDetailsByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KillmailDetail
	for rows.Next() {
		var i KillmailDetail
		if err := rows.Scan(
			&i.KillmailID,
			&i.CharacterID,
			&i.Hash,
			&i.Payload,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiquidCoreTypes = `-- name: ListLiquidCoreTypes :many
SELECT mh.type_id, SUM(mh.volume * mh.average)::bigint AS isk_velocity
FROM market_history mh
WHERE mh.region_id = $1
  AND mh.date >= (SELECT to_char(MAX(mh2.date)::date - INTERVAL '7 days', 'YYYY-MM-DD') FROM market_history mh2 WHERE mh2.region_id = $1)
GROUP BY mh.type_id
ORDER BY isk_velocity DESC
LIMIT $2::bigint
`

type ListLiquidCoreTypesParams struct {
	RegionID  int64 `json:"region_id"`
	CoreLimit int64 `json:"core_limit"`
}

type ListLiquidCoreTypesRow struct {
	TypeID      int64 `json:"type_id"`
	IskVelocity int64 `json:"isk_velocity"`
}

func (q *Queries) ListLiquidCoreTypes(ctx context.Context, arg ListLiquidCoreTypesParams) ([]ListLiquidCoreTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLiquidCoreTypes, arg.RegionID, arg.CoreLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiquidCoreTypesRow
	for rows.Next() {
		var i ListLiquidCoreTypesRow
		if err := rows.Scan(&i.TypeID, &i.IskVelocity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalFittings = `-- name: ListLocalFittings :many
SELECT id, user_id, name, ship_type_id, items_json, is_public, is_draft, created_at, updated_at FROM local_fittings
WHERE user_id = $1
ORDER BY updated_at DESC, id DESC
LIMIT 100
`

type ListLocalFittingsRow struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	Name       string    `json:"name"`
	ShipTypeID int64     `json:"ship_type_id"`
	ItemsJson  string    `json:"items_json"`
	IsPublic   bool      `json:"is_public"`
	IsDraft    bool      `json:"is_draft"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) ListLocalFittings(ctx context.Context, userID int64) ([]ListLocalFittingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLocalFittings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocalFittingsRow
	for rows.Next() {
		var i ListLocalFittingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ShipTypeID,
			&i.ItemsJson,
			&i.IsPublic,
			&i.IsDraft,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanetLayoutsForUser = `-- name: ListPlanetLayoutsForUser :many
SELECT s.character_id, s.kind, s.payload, s.fetched_at
FROM character_snapshots s
JOIN characters c ON c.character_id = s.character_id
WHERE c.user_id = $1 AND strpos(s.kind, 'planet_layout_') = 1
ORDER BY s.character_id, s.kind
`

type ListPlanetLayoutsForUserRow struct {
	CharacterID int64     `json:"character_id"`
	Kind        string    `json:"kind"`
	Payload     string    `json:"payload"`
	FetchedAt   time.Time `json:"fetched_at"`
}

func (q *Queries) ListPlanetLayoutsForUser(ctx context.Context, userID int64) ([]ListPlanetLayoutsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlanetLayoutsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlanetLayoutsForUserRow
	for rows.Next() {
		var i ListPlanetLayoutsForUserRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.Kind,
			&i.Payload,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentKillmailDetails = `-- name: ListRecentKillmailDetails :many
SELECT payload FROM killmail_details
ORDER BY fetched_at DESC
LIMIT $1::bigint
`

func (q *Queries) ListRecentKillmailDetails(ctx context.Context, rowLimit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRecentKillmailDetails, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var payload string
		if err := rows.Scan(&payload); err != nil {
			return nil, err
		}
		items = append(items, payload)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillPlanItems = `-- name: ListSkillPlanItems :many
SELECT plan_id, skill_type_id, target_level, position FROM skill_plan_items
WHERE plan_id = $1
ORDER BY position, skill_type_id
`

func (q *Queries) ListSkillPlanItems(ctx context.Context, planID int64) ([]SkillPlanItem, error) {
	rows, err := q.db.QueryContext(ctx, listSkillPlanItems, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillPlanItem
	for rows.Next() {
		var i SkillPlanItem
		if err := rows.Scan(
			&i.PlanID,
			&i.SkillTypeID,
			&i.TargetLevel,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillPlans = `-- name: ListSkillPlans :many
SELECT id, user_id, character_id, name, created_at FROM skill_plans
WHERE user_id = $1 AND character_id = $2
ORDER BY created_at, id
`

type ListSkillPlansParams struct {
	UserID      int64 `json:"user_id"`
	CharacterID int64 `json:"character_id"`
}

func (q *Queries) ListSkillPlans(ctx context.Context, arg ListSkillPlansParams) ([]SkillPlan, error) {
	rows, err := q.db.QueryContext(ctx, listSkillPlans, arg.UserID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillPlan
	for rows.Next() {
		var i SkillPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CharacterID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotFetchStatesByCharacter = `-- name: ListSnapshotFetchStatesByCharacter :many
SELECT character_id, kind, state, detail, attempted_at FROM snapshot_fetch_state
WHERE character_id = $1
ORDER BY kind
`

func (q *Queries) ListSnapshotFetchStatesByCharacter(ctx context.Context, characterID int64) ([]SnapshotFetchState, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotFetchStatesByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotFetchState
	for rows.Next() {
		var i SnapshotFetchState
		if err := rows.Scan(
			&i.CharacterID,
			&i.Kind,
			&i.State,
			&i.Detail,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotMetaByCharacter = `-- name: ListSnapshotMetaByCharacter :many
SELECT kind, fetched_at, cached_until FROM character_snapshots
WHERE character_id = $1
ORDER BY kind
`

type ListSnapshotMetaByCharacterRow struct {
	Kind        string       `json:"kind"`
	FetchedAt   time.Time    `json:"fetched_at"`
	CachedUntil sql.NullTime `json:"cached_until"`
}

// A character's stored snapshots without their payloads: which kinds
// exist and how fresh each is. The payloads (a whole asset list, a
// mailbox) are by far the bulk of the table, and the readers that
// only order, count or check freshness have no use for them.
func (q *Queries) ListSnapshotMetaByCharacter(ctx context.Context, characterID int64) ([]ListSnapshotMetaByCharacterRow, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotMetaByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSnapshotMetaByCharacterRow
	for rows.Next() {
		var i ListSnapshotMetaByCharacterRow
		if err := rows.Scan(&i.Kind, &i.FetchedAt, &i.CachedUntil); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByCharacter = `-- name: ListSnapshotsByCharacter :many
SELECT character_id, kind, payload, fetched_at, cached_until, etag FROM character_snapshots
WHERE character_id = $1
ORDER BY kind
`

func (q *Queries) ListSnapshotsByCharacter(ctx context.Context, characterID int64) ([]CharacterSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterSnapshot
	for rows.Next() {
		var i CharacterSnapshot
		if err := rows.Scan(
			&i.CharacterID,
			&i.Kind,
			&i.Payload,
			&i.FetchedAt,
			&i.CachedUntil,
			&i.Etag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByKind = `-- name: ListSnapshotsByKind :many
SELECT character_id, kind, payload, fetched_at, cached_until, etag FROM character_snapshots
WHERE kind = $1
ORDER BY character_id
`

func (q *Queries) ListSnapshotsByKind(ctx context.Context, kind string) ([]CharacterSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterSnapshot
	for rows.Next() {
		var i CharacterSnapshot
		if err := rows.Scan(
			&i.CharacterID,
			&i.Kind,
			&i.Payload,
			&i.FetchedAt,
			&i.CachedUntil,
			&i.Etag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsForUser = `-- name: ListSnapshotsForUser :many
SELECT s.character_id, s.kind, s.payload, s.fetched_at, s.cached_until
FROM character_snapshots s
JOIN characters c ON c.character_id = s.character_id
WHERE c.user_id = $1 AND s.kind = ANY($2::text[])
ORDER BY s.character_id, s.kind
`

type ListSnapshotsForUserParams struct {
	UserID int64    `json:"user_id"`
	Kinds  []string `json:"kinds"`
}

type ListSnapshotsForUserRow struct {
	CharacterID int64        `json:"character_id"`
	Kind        string       `json:"kind"`
	Payload     string       `json:"payload"`
	FetchedAt   time.Time    `json:"fetched_at"`
	CachedUntil sql.NullTime `json:"cached_until"`
}

func (q *Queries) ListSnapshotsForUser(ctx context.Context, arg ListSnapshotsForUserParams) ([]ListSnapshotsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsForUser, arg.UserID, pq.Array(arg.Kinds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSnapshotsForUserRow
	for rows.Next() {
		var i ListSnapshotsForUserRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.Kind,
			&i.Payload,
			&i.FetchedAt,
			&i.CachedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWalletHistory = `-- name: ListUserWalletHistory :many
SELECT user_id, character_id, day, balance, net_worth, sampled_at
FROM wallet_history
WHERE user_id = $1
ORDER BY day, character_id
`

func (q *Queries) ListUserWalletHistory(ctx context.Context, userID int64) ([]WalletHistory, error) {
	rows, err := q.db.QueryContext(ctx, listUserWalletHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletHistory
	for rows.Next() {
		var i WalletHistory
		if err := rows.Scan(
			&i.UserID,
			&i.CharacterID,
			&i.Day,
			&i.Balance,
			&i.NetWorth,
			&i.SampledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, created_at, home_layout, last_briefing_at FROM users
ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.HomeLayout,
			&i.LastBriefingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletHistorySamples = `-- name: ListWalletHistorySamples :many
SELECT user_id, character_id, day, balance, net_worth, sampled_at
FROM wallet_history
WHERE user_id = $1 AND character_id = $2
ORDER BY day
`

type ListWalletHistorySamplesParams struct {
	UserID      int64 `json:"user_id"`
	CharacterID int64 `json:"character_id"`
}

func (q *Queries) ListWalletHistorySamples(ctx context.Context, arg ListWalletHistorySamplesParams) ([]WalletHistory, error) {
	rows, err := q.db.QueryContext(ctx, listWalletHistorySamples, arg.UserID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletHistory
	for rows.Next() {
		var i WalletHistory
		if err := rows.Scan(
			&i.UserID,
			&i.CharacterID,
			&i.Day,
			&i.Balance,
			&i.NetWorth,
			&i.SampledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWidgetConfigsByUser = `-- name: ListWidgetConfigsByUser :many
SELECT user_id, widget_id, config, updated_at FROM widget_configs
WHERE user_id = $1
ORDER BY widget_id
`

func (q *Queries) ListWidgetConfigsByUser(ctx context.Context, userID int64) ([]WidgetConfig, error) {
	rows, err := q.db.QueryContext(ctx, listWidgetConfigsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WidgetConfig
	for rows.Next() {
		var i WidgetConfig
		if err := rows.Scan(
			&i.UserID,
			&i.WidgetID,
			&i.Config,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSkillPlanPosition = `-- name: NextSkillPlanPosition :one
SELECT CAST(COALESCE(MAX(position), 0) + 1 AS BIGINT) FROM skill_plan_items WHERE plan_id = $1
`

func (q *Queries) NextSkillPlanPosition(ctx context.Context, planID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextSkillPlanPosition, planID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const searchLocalFittings = `-- name: SearchLocalFittings :many
SELECT lf.id, lf.user_id, lf.name, lf.ship_type_id, lf.items_json, lf.is_public, lf.is_draft, lf.created_at, lf.updated_at,
       COALESCE(tn.name, '') AS ship_name
FROM local_fittings lf
LEFT JOIN type_names tn ON tn.type_id = lf.ship_type_id
WHERE lf.user_id = $1
  AND ($2::text = '' OR lf.name ILIKE '%' || $2::text || '%' OR tn.name ILIKE '%' || $2::text || '%')
ORDER BY lf.updated_at DESC, lf.id DESC
LIMIT 20
`

type SearchLocalFittingsParams struct {
	UserID int64  `json:"user_id"`
	Q      string `json:"q"`
}

type SearchLocalFittingsRow struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	Name       string    `json:"name"`
	ShipTypeID int64     `json:"ship_type_id"`
	ItemsJson  string    `json:"items_json"`
	IsPublic   bool      `json:"is_public"`
	IsDraft    bool      `json:"is_draft"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	ShipName   string    `json:"ship_name"`
}

func (q *Queries) SearchLocalFittings(ctx context.Context, arg SearchLocalFittingsParams) ([]SearchLocalFittingsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchLocalFittings, arg.UserID, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchLocalFittingsRow
	for rows.Next() {
		var i SearchLocalFittingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ShipTypeID,
			&i.ItemsJson,
			&i.IsPublic,
			&i.IsDraft,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShipName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPublicFittings = `-- name: SearchPublicFittings :many
SELECT lf.id, lf.name, lf.ship_type_id, lf.items_json, lf.updated_at,
       COALESCE(tn.name, '') AS ship_name,
       COALESCE((SELECT c.name FROM characters c WHERE c.user_id = lf.user_id ORDER BY c.character_id LIMIT 1), '') AS author_name
FROM local_fittings lf
LEFT JOIN type_names tn ON tn.type_id = lf.ship_type_id
WHERE lf.is_public AND NOT lf.is_draft AND lf.user_id != $1
  AND ($2::text = '' OR lf.name ILIKE '%' || $2::text || '%' OR tn.name ILIKE '%' || $2::text || '%')
ORDER BY lf.updated_at DESC, lf.id DESC
LIMIT 20
`

type SearchPublicFittingsParams struct {
	UserID int64  `json:"user_id"`
	Q      string `json:"q"`
}

type SearchPublicFittingsRow struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	ShipTypeID int64       `json:"ship_type_id"`
	ItemsJson  string      `json:"items_json"`
	UpdatedAt  time.Time   `json:"updated_at"`
	ShipName   string      `json:"ship_name"`
	AuthorName interface{} `json:"author_name"`
}

func (q *Queries) SearchPublicFittings(ctx context.Context, arg SearchPublicFittingsParams) ([]SearchPublicFittingsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPublicFittings, arg.UserID, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPublicFittingsRow
	for rows.Next() {
		var i SearchPublicFittingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShipTypeID,
			&i.ItemsJson,
			&i.UpdatedAt,
			&i.ShipName,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCharacterLinkState = `-- name: SetCharacterLinkState :exec
UPDATE characters
SET link_state = $1, link_state_at = $2, updated_at = now()
WHERE character_id = $3
`

type SetCharacterLinkStateParams struct {
	LinkState   string       `json:"link_state"`
	LinkStateAt sql.NullTime `json:"link_state_at"`
	CharacterID int64        `json:"character_id"`
}

func (q *Queries) SetCharacterLinkState(ctx context.Context, arg SetCharacterLinkStateParams) error {
	_, err := q.db.ExecContext(ctx, setCharacterLinkState, arg.LinkState, arg.LinkStateAt, arg.CharacterID)
	return err
}

const setCharacterTags = `-- name: SetCharacterTags :exec
UPDATE characters
SET tags = $1, updated_at = now()
WHERE character_id = $2 AND user_id = $3
`

type SetCharacterTagsParams struct {
	Tags        string `json:"tags"`
	CharacterID int64  `json:"character_id"`
	UserID      int64  `json:"user_id"`
}

func (q *Queries) SetCharacterTags(ctx context.Context, arg SetCharacterTagsParams) error {
	_, err := q.db.ExecContext(ctx, setCharacterTags, arg.Tags, arg.CharacterID, arg.UserID)
	return err
}

const setUserBriefingAnchor = `-- name: SetUserBriefingAnchor :exec
UPDATE users
SET last_briefing_at = $1
WHERE id = $2
`

type SetUserBriefingAnchorParams struct {
	LastBriefingAt sql.NullTime `json:"last_briefing_at"`
	ID             int64        `json:"id"`
}

func (q *Queries) SetUserBriefingAnchor(ctx context.Context, arg SetUserBriefingAnchorParams) error {
	_, err := q.db.ExecContext(ctx, setUserBriefingAnchor, arg.LastBriefingAt, arg.ID)
	return err
}

const setUserHomeLayout = `-- name: SetUserHomeLayout :exec
UPDATE users
SET home_layout = $1
WHERE id = $2
`

type SetUserHomeLayoutParams struct {
	HomeLayout string `json:"home_layout"`
	ID         int64  `json:"id"`
}

func (q *Queries) SetUserHomeLayout(ctx context.Context, arg SetUserHomeLayoutParams) error {
	_, err := q.db.ExecContext(ctx, setUserHomeLayout, arg.HomeLayout, arg.ID)
	return err
}

const touchGlobalSnapshot = `-- name: TouchGlobalSnapshot :execrows
UPDATE global_snapshots
SET fetched_at = $1, cached_until = $2
WHERE kind = $3
`

type TouchGlobalSnapshotParams struct {
	FetchedAt   time.Time `json:"fetched_at"`
	CachedUntil time.Time `json:"cached_until"`
	Kind        string    `json:"kind"`
}

// ESI answered "not modified": only the bookkeeping moves.
func (q *Queries) TouchGlobalSnapshot(ctx context.Context, arg TouchGlobalSnapshotParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchGlobalSnapshot, arg.FetchedAt, arg.CachedUntil, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchSnapshot = `-- name: TouchSnapshot :execrows
UPDATE character_snapshots
SET fetched_at = $1, cached_until = $2
WHERE character_id = $3 AND kind = $4
`

type TouchSnapshotParams struct {
	FetchedAt   time.Time    `json:"fetched_at"`
	CachedUntil sql.NullTime `json:"cached_until"`
	CharacterID int64        `json:"character_id"`
	Kind        string       `json:"kind"`
}

// ESI answered "not modified": the stored payload is still current,
// so only the bookkeeping beside it moves.
func (q *Queries) TouchSnapshot(ctx context.Context, arg TouchSnapshotParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchSnapshot,
		arg.FetchedAt,
		arg.CachedUntil,
		arg.CharacterID,
		arg.Kind,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCharacterTokens = `-- name: UpdateCharacterTokens :exec
UPDATE characters
SET access_token = $1, refresh_token = $2, token_expiry = $3, updated_at = now()
WHERE character_id = $4
`

type UpdateCharacterTokensParams struct {
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token"`
	TokenExpiry  sql.NullTime `json:"token_expiry"`
	CharacterID  int64        `json:"character_id"`
}

func (q *Queries) UpdateCharacterTokens(ctx context.Context, arg UpdateCharacterTokensParams) error {
	_, err := q.db.ExecContext(ctx, updateCharacterTokens,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
		arg.CharacterID,
	)
	return err
}

const updateLocalFitting = `-- name: UpdateLocalFitting :exec
UPDATE local_fittings
SET name = $1, ship_type_id = $2, items_json = $3, is_public = $4, is_draft = $5, updated_at = $6
WHERE id = $7 AND user_id = $8
`

type UpdateLocalFittingParams struct {
	Name       string    `json:"name"`
	ShipTypeID int64     `json:"ship_type_id"`
	ItemsJson  string    `json:"items_json"`
	IsPublic   bool      `json:"is_public"`
	IsDraft    bool      `json:"is_draft"`
	UpdatedAt  time.Time `json:"updated_at"`
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
}

func (q *Queries) UpdateLocalFitting(ctx context.Context, arg UpdateLocalFittingParams) error {
	_, err := q.db.ExecContext(ctx, updateLocalFitting,
		arg.Name,
		arg.ShipTypeID,
		arg.ItemsJson,
		arg.IsPublic,
		arg.IsDraft,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateSkillPlanItemPosition = `-- name: UpdateSkillPlanItemPosition :exec
UPDATE skill_plan_items SET position = $1 WHERE plan_id = $2 AND skill_type_id = $3
`

type UpdateSkillPlanItemPositionParams struct {
	Position    int64 `json:"position"`
	PlanID      int64 `json:"plan_id"`
	SkillTypeID int64 `json:"skill_type_id"`
}

func (q *Queries) UpdateSkillPlanItemPosition(ctx context.Context, arg UpdateSkillPlanItemPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateSkillPlanItemPosition, arg.Position, arg.PlanID, arg.SkillTypeID)
	return err
}

const upsertCharacter = `-- name: UpsertCharacter :one
INSERT INTO characters (
    character_id, user_id, name,
    access_token, refresh_token, token_expiry,
    scopes, cached_until, owner_hash, link_state, link_state_at,
    updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, $10, $11,
    now()
)
ON CONFLICT (character_id) DO UPDATE SET
    user_id       = excluded.user_id,
    name          = excluded.name,
    access_token  = excluded.access_token,
    refresh_token = excluded.refresh_token,
    token_expiry  = excluded.token_expiry,
    scopes        = excluded.scopes,
    cached_until  = excluded.cached_until,
    owner_hash    = excluded.owner_hash,
    link_state    = excluded.link_state,
    link_state_at = excluded.link_state_at,
    updated_at    = excluded.updated_at
RETURNING character_id, user_id, name, access_token, refresh_token, token_expiry, scopes, cached_until, created_at, updated_at, owner_hash, tags, link_state, link_state_at
`

type UpsertCharacterParams struct {
	CharacterID  int64        `json:"character_id"`
	UserID       int64        `json:"user_id"`
	Name         string       `json:"name"`
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token"`
	TokenExpiry  sql.NullTime `json:"token_expiry"`
	Scopes       string       `json:"scopes"`
	CachedUntil  sql.NullTime `json:"cached_until"`
	OwnerHash    string       `json:"owner_hash"`
	LinkState    string       `json:"link_state"`
	LinkStateAt  sql.NullTime `json:"link_state_at"`
}

func (q *Queries) UpsertCharacter(ctx context.Context, arg UpsertCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, upsertCharacter,
		arg.CharacterID,
		arg.UserID,
		arg.Name,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
		arg.Scopes,
		arg.CachedUntil,
		arg.OwnerHash,
		arg.LinkState,
		arg.LinkStateAt,
	)
	var i Character
	err := row.Scan(
		&i.CharacterID,
		&i.UserID,
		&i.Name,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.Scopes,
		&i.CachedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerHash,
		&i.Tags,
		&i.LinkState,
		&i.LinkStateAt,
	)
	return i, err
}

const upsertCharacterCorporation = `-- name: UpsertCharacterCorporation :exec
INSERT INTO character_corporations (character_id, corporation_id, updated_at)
VALUES ($1, $2, $3)
ON CONFLICT (character_id) DO UPDATE SET
    corporation_id = excluded.corporation_id,
    updated_at     = excluded.updated_at
`

type UpsertCharacterCorporationParams struct {
	CharacterID   int64     `json:"character_id"`
	CorporationID int64     `json:"corporation_id"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) UpsertCharacterCorporation(ctx context.Context, arg UpsertCharacterCorporationParams) error {
	_, err := q.db.ExecContext(ctx, upsertCharacterCorporation, arg.CharacterID, arg.CorporationID, arg.UpdatedAt)
	return err
}

const upsertCloneName = `-- name: UpsertCloneName :exec


INSERT INTO clone_names (user_id, character_id, clone_id, custom_name, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id, character_id, clone_id)
DO UPDATE SET custom_name = EXCLUDED.custom_name, updated_at = now()
`

type UpsertCloneNameParams struct {
	UserID      int64  `json:"user_id"`
	CharacterID int64  `json:"character_id"`
	CloneID     int64  `json:"clone_id"`
	CustomName  string `json:"custom_name"`
}

// ---------------------------------------------------------------------
// Market history + alerts (schema 013): daily aggregates, wants,
// fetch state, the watchlist, and worker-computed order health.
// ---------------------------------------------------------------------
// ---------------------------------------------------------------------
// Custom jump-clone names (schema 006): pilot-given labels per clone.
// ---------------------------------------------------------------------
func (q *Queries) UpsertCloneName(ctx context.Context, arg UpsertCloneNameParams) error {
	_, err := q.db.ExecContext(ctx, upsertCloneName,
		arg.UserID,
		arg.CharacterID,
		arg.CloneID,
		arg.CustomName,
	)
	return err
}

const upsertContractDetail = `-- name: UpsertContractDetail :exec
INSERT INTO contract_details (contract_id, character_id, payload, fetched_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (contract_id) DO UPDATE SET
    character_id = excluded.character_id,
    payload      = excluded.payload,
    fetched_at   = excluded.fetched_at
`

type UpsertContractDetailParams struct {
	ContractID  int64     `json:"contract_id"`
	CharacterID int64     `json:"character_id"`
	Payload     string    `json:"payload"`
	FetchedAt   time.Time `json:"fetched_at"`
}

func (q *Queries) UpsertContractDetail(ctx context.Context, arg UpsertContractDetailParams) error {
	_, err := q.db.ExecContext(ctx, upsertContractDetail,
		arg.ContractID,
		arg.CharacterID,
		arg.Payload,
		arg.FetchedAt,
	)
	return err
}

const upsertGlobalSnapshot = `-- name: UpsertGlobalSnapshot :exec
INSERT INTO global_snapshots (kind, payload, fetched_at, cached_until, etag)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (kind) DO UPDATE SET
    payload      = excluded.payload,
    fetched_at   = excluded.fetched_at,
    cached_until = excluded.cached_until,
    etag         = excluded.etag
`

type UpsertGlobalSnapshotParams struct {
	Kind        string    `json:"kind"`
	Payload     string    `json:"payload"`
	FetchedAt   time.Time `json:"fetched_at"`
	CachedUntil time.Time `json:"cached_until"`
	Etag        string    `json:"etag"`
}

func (q *Queries) UpsertGlobalSnapshot(ctx context.Context, arg UpsertGlobalSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertGlobalSnapshot,
		arg.Kind,
		arg.Payload,
		arg.FetchedAt,
		arg.CachedUntil,
		arg.Etag,
	)
	return err
}

const upsertKillmailDetail = `-- name: UpsertKillmailDetail :exec
INSERT INTO killmail_details (killmail_id, character_id, hash, payload, fetched_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (killmail_id) DO UPDATE SET
    character_id = excluded.character_id,
    hash         = excluded.hash,
    payload      = excluded.payload,
    fetched_at   = excluded.fetched_at
`

type UpsertKillmailDetailParams struct {
	KillmailID  int64     `json:"killmail_id"`
	CharacterID int64     `json:"character_id"`
	Hash        string    `json:"hash"`
	Payload     string    `json:"payload"`
	FetchedAt   time.Time `json:"fetched_at"`
}

func (q *Queries) UpsertKillmailDetail(ctx context.Context, arg UpsertKillmailDetailParams) error {
	_, err := q.db.ExecContext(ctx, upsertKillmailDetail,
		arg.KillmailID,
		arg.CharacterID,
		arg.Hash,
		arg.Payload,
		arg.FetchedAt,
	)
	return err
}

const upsertSkillPlanItem = `-- name: UpsertSkillPlanItem :exec
INSERT INTO skill_plan_items (plan_id, skill_type_id, target_level, position)
VALUES ($1, $2, $3, $4)
ON CONFLICT(plan_id, skill_type_id) DO UPDATE SET target_level = excluded.target_level
`

type UpsertSkillPlanItemParams struct {
	PlanID      int64 `json:"plan_id"`
	SkillTypeID int64 `json:"skill_type_id"`
	TargetLevel int64 `json:"target_level"`
	Position    int64 `json:"position"`
}

// Adding an existing skill raises (or keeps) its target level and
// leaves position to the caller: a fresh insert takes MAX(position)+1
// (the handler supplies it).
func (q *Queries) UpsertSkillPlanItem(ctx context.Context, arg UpsertSkillPlanItemParams) error {
	_, err := q.db.ExecContext(ctx, upsertSkillPlanItem,
		arg.PlanID,
		arg.SkillTypeID,
		arg.TargetLevel,
		arg.Position,
	)
	return err
}

const upsertSnapshot = `-- name: UpsertSnapshot :exec
INSERT INTO character_snapshots (character_id, kind, payload, fetched_at, cached_until, etag)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (character_id, kind) DO UPDATE SET
    payload      = excluded.payload,
    fetched_at   = excluded.fetched_at,
    cached_until = excluded.cached_until,
    etag         = excluded.etag
`

type UpsertSnapshotParams struct {
	CharacterID int64        `json:"character_id"`
	Kind        string       `json:"kind"`
	Payload     string       `json:"payload"`
	FetchedAt   time.Time    `json:"fetched_at"`
	CachedUntil sql.NullTime `json:"cached_until"`
	Etag        string       `json:"etag"`
}

func (q *Queries) UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertSnapshot,
		arg.CharacterID,
		arg.Kind,
		arg.Payload,
		arg.FetchedAt,
		arg.CachedUntil,
		arg.Etag,
	)
	return err
}

const upsertSnapshotFetchState = `-- name: UpsertSnapshotFetchState :exec
INSERT INTO snapshot_fetch_state (character_id, kind, state, detail, attempted_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (character_id, kind) DO UPDATE SET
    state        = excluded.state,
    detail       = excluded.detail,
    attempted_at = excluded.attempted_at
`

type UpsertSnapshotFetchStateParams struct {
	CharacterID int64     `json:"character_id"`
	Kind        string    `json:"kind"`
	State       string    `json:"state"`
	Detail      string    `json:"detail"`
	AttemptedAt time.Time `json:"attempted_at"`
}

func (q *Queries) UpsertSnapshotFetchState(ctx context.Context, arg UpsertSnapshotFetchStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertSnapshotFetchState,
		arg.CharacterID,
		arg.Kind,
		arg.State,
		arg.Detail,
		arg.AttemptedAt,
	)
	return err
}

const upsertWalletHistorySample = `-- name: UpsertWalletHistorySample :exec
INSERT INTO wallet_history (user_id, character_id, day, balance, net_worth, sampled_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, character_id, day) DO UPDATE SET
    balance    = excluded.balance,
    net_worth   = excluded.net_worth,
    sampled_at = excluded.sampled_at
`

type UpsertWalletHistorySampleParams struct {
	UserID      int64           `json:"user_id"`
	CharacterID int64           `json:"character_id"`
	Day         string          `json:"day"`
	Balance     float64         `json:"balance"`
	NetWorth    sql.NullFloat64 `json:"net_worth"`
	SampledAt   time.Time       `json:"sampled_at"`
}

func (q *Queries) UpsertWalletHistorySample(ctx context.Context, arg UpsertWalletHistorySampleParams) error {
	_, err := q.db.ExecContext(ctx, upsertWalletHistorySample,
		arg.UserID,
		arg.CharacterID,
		arg.Day,
		arg.Balance,
		arg.NetWorth,
		arg.SampledAt,
	)
	return err
}

const upsertWarDetail = `-- name: UpsertWarDetail :exec
INSERT INTO war_details (war_id, payload, fetched_at)
VALUES ($1, $2, $3)
ON CONFLICT (war_id) DO UPDATE SET
    payload    = excluded.payload,
    fetched_at = excluded.fetched_at
`

type UpsertWarDetailParams struct {
	WarID     int64     `json:"war_id"`
	Payload   string    `json:"payload"`
	FetchedAt time.Time `json:"fetched_at"`
}

func (q *Queries) UpsertWarDetail(ctx context.Context, arg UpsertWarDetailParams) error {
	_, err := q.db.ExecContext(ctx, upsertWarDetail, arg.WarID, arg.Payload, arg.FetchedAt)
	return err
}

const upsertWidgetConfig = `-- name: UpsertWidgetConfig :exec
INSERT INTO widget_configs (user_id, widget_id, config, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, widget_id) DO UPDATE SET
    config     = excluded.config,
    updated_at = excluded.updated_at
`

type UpsertWidgetConfigParams struct {
	UserID    int64     `json:"user_id"`
	WidgetID  string    `json:"widget_id"`
	Config    string    `json:"config"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpsertWidgetConfig(ctx context.Context, arg UpsertWidgetConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertWidgetConfig,
		arg.UserID,
		arg.WidgetID,
		arg.Config,
		arg.UpdatedAt,
	)
	return err
}
