// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_typing.sql

package db

import (
	"context"
	"time"
)

const deleteTypingAllianceGuesses = `-- name: DeleteTypingAllianceGuesses :exec
DELETE FROM alliance_records
WHERE priority = $2::bigint AND state = 'pending'
  AND alliance_id IN (SELECT entity_id FROM typing_guesses WHERE box = $1 AND kind = 'alliance')
`

type DeleteTypingAllianceGuessesParams struct {
	Box            string `json:"box"`
	TypingPriority int64  `json:"typing_priority"`
}

func (q *Queries) DeleteTypingAllianceGuesses(ctx context.Context, arg DeleteTypingAllianceGuessesParams) error {
	_, err := q.db.ExecContext(ctx, deleteTypingAllianceGuesses, arg.Box, arg.TypingPriority)
	return err
}

const deleteTypingCorporationGuesses = `-- name: DeleteTypingCorporationGuesses :exec
DELETE FROM corporation_records
WHERE priority = $2::bigint AND state = 'pending'
  AND corporation_id IN (SELECT entity_id FROM typing_guesses WHERE box = $1 AND kind = 'corporation')
`

type DeleteTypingCorporationGuessesParams struct {
	Box            string `json:"box"`
	TypingPriority int64  `json:"typing_priority"`
}

func (q *Queries) DeleteTypingCorporationGuesses(ctx context.Context, arg DeleteTypingCorporationGuessesParams) error {
	_, err := q.db.ExecContext(ctx, deleteTypingCorporationGuesses, arg.Box, arg.TypingPriority)
	return err
}

const deleteTypingDetailGuesses = `-- name: DeleteTypingDetailGuesses :exec
DELETE FROM type_details
WHERE priority = $2::bigint AND fetched_at IS NULL
  AND type_id IN (SELECT entity_id FROM typing_guesses WHERE box = $1 AND kind = 'type_description')
`

type DeleteTypingDetailGuessesParams struct {
	Box            string `json:"box"`
	TypingPriority int64  `json:"typing_priority"`
}

func (q *Queries) DeleteTypingDetailGuesses(ctx context.Context, arg DeleteTypingDetailGuessesParams) error {
	_, err := q.db.ExecContext(ctx, deleteTypingDetailGuesses, arg.Box, arg.TypingPriority)
	return err
}

const deleteTypingGuessesForBox = `-- name: DeleteTypingGuessesForBox :exec
DELETE FROM typing_guesses WHERE box = $1
`

func (q *Queries) DeleteTypingGuessesForBox(ctx context.Context, box string) error {
	_, err := q.db.ExecContext(ctx, deleteTypingGuessesForBox, box)
	return err
}

const deleteTypingHistoryGuesses = `-- name: DeleteTypingHistoryGuesses :exec
DELETE FROM market_history_wants
WHERE priority = $2::bigint
  AND (region_id, type_id) IN (SELECT region_id, entity_id FROM typing_guesses WHERE box = $1 AND kind = 'market_history')
`

type DeleteTypingHistoryGuessesParams struct {
	Box            string `json:"box"`
	TypingPriority int64  `json:"typing_priority"`
}

func (q *Queries) DeleteTypingHistoryGuesses(ctx context.Context, arg DeleteTypingHistoryGuessesParams) error {
	_, err := q.db.ExecContext(ctx, deleteTypingHistoryGuesses, arg.Box, arg.TypingPriority)
	return err
}

const deleteTypingPilotGuesses = `-- name: DeleteTypingPilotGuesses :exec

DELETE FROM pilot_records
WHERE priority = $2::bigint AND state = 'pending'
  AND character_id IN (SELECT entity_id FROM typing_guesses WHERE box = $1 AND kind = 'pilot')
`

type DeleteTypingPilotGuessesParams struct {
	Box            string `json:"box"`
	TypingPriority int64  `json:"typing_priority"`
}

// A box's next keystroke drops the queue rows its guesses are
// still waiting in. Only rows still at the typing ring go: one
// the pilot opened has been bumped to viewed, and one already
// holding data is a record now, not a guess.
func (q *Queries) DeleteTypingPilotGuesses(ctx context.Context, arg DeleteTypingPilotGuessesParams) error {
	_, err := q.db.ExecContext(ctx, deleteTypingPilotGuesses, arg.Box, arg.TypingPriority)
	return err
}

const getTypingGuess = `-- name: GetTypingGuess :one
SELECT box, kind, entity_id, region_id, noted_at, hit_at
FROM typing_guesses
WHERE box = $1 AND kind = $2 AND entity_id = $3 AND region_id = $4
`

type GetTypingGuessParams struct {
	Box      string `json:"box"`
	Kind     string `json:"kind"`
	EntityID int64  `json:"entity_id"`
	RegionID int64  `json:"region_id"`
}

func (q *Queries) GetTypingGuess(ctx context.Context, arg GetTypingGuessParams) (TypingGuess, error) {
	row := q.db.QueryRowContext(ctx, getTypingGuess,
		arg.Box,
		arg.Kind,
		arg.EntityID,
		arg.RegionID,
	)
	var i TypingGuess
	err := row.Scan(
		&i.Box,
		&i.Kind,
		&i.EntityID,
		&i.RegionID,
		&i.NotedAt,
		&i.HitAt,
	)
	return i, err
}

const insertTypingGuess = `-- name: InsertTypingGuess :exec

INSERT INTO typing_guesses (box, kind, entity_id, region_id, noted_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (box, kind, entity_id, region_id) DO UPDATE SET
    noted_at = excluded.noted_at
`

type InsertTypingGuessParams struct {
	Box      string    `json:"box"`
	Kind     string    `json:"kind"`
	EntityID int64     `json:"entity_id"`
	RegionID int64     `json:"region_id"`
	NotedAt  time.Time `json:"noted_at"`
}

// Typing-intent guesses (schema 028): what each search box's
// latest keystroke guessed, so the next keystroke can replace it.
// The queue rows carry the typing ring (worker_pagewants.go); this
// table carries which box put them there, and whether the pilot
// opened one within minutes of it being noted (the hit rate the
// prefetch tuning reads later).
func (q *Queries) InsertTypingGuess(ctx context.Context, arg InsertTypingGuessParams) error {
	_, err := q.db.ExecContext(ctx, insertTypingGuess,
		arg.Box,
		arg.Kind,
		arg.EntityID,
		arg.RegionID,
		arg.NotedAt,
	)
	return err
}

const markTypingGuessHits = `-- name: MarkTypingGuessHits :exec
UPDATE typing_guesses SET hit_at = $4::timestamptz
WHERE kind = $1 AND entity_id = $2 AND region_id = $3
  AND hit_at IS NULL AND noted_at > $5::timestamptz
`

type MarkTypingGuessHitsParams struct {
	Kind     string    `json:"kind"`
	EntityID int64     `json:"entity_id"`
	RegionID int64     `json:"region_id"`
	Now      time.Time `json:"now"`
	Since    time.Time `json:"since"`
}

func (q *Queries) MarkTypingGuessHits(ctx context.Context, arg MarkTypingGuessHitsParams) error {
	_, err := q.db.ExecContext(ctx, markTypingGuessHits,
		arg.Kind,
		arg.EntityID,
		arg.RegionID,
		arg.Now,
		arg.Since,
	)
	return err
}
