// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_ops.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createOp = `-- name: CreateOp :one
INSERT INTO ops (corporation_id, title, description, starts_at, duration_minutes, doctrine, form_up, fc_character_id, created_by_character, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type CreateOpParams struct {
	CorporationID      int64     `json:"corporation_id"`
	Title              string    `json:"title"`
	Description        string    `json:"description"`
	StartsAt           time.Time `json:"starts_at"`
	DurationMinutes    int64     `json:"duration_minutes"`
	Doctrine           string    `json:"doctrine"`
	FormUp             string    `json:"form_up"`
	FcCharacterID      int64     `json:"fc_character_id"`
	CreatedByCharacter int64     `json:"created_by_character"`
	CreatedAt          time.Time `json:"created_at"`
}

func (q *Queries) CreateOp(ctx context.Context, arg CreateOpParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOp,
		arg.CorporationID,
		arg.Title,
		arg.Description,
		arg.StartsAt,
		arg.DurationMinutes,
		arg.Doctrine,
		arg.FormUp,
		arg.FcCharacterID,
		arg.CreatedByCharacter,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOp = `-- name: GetOp :one
SELECT id, corporation_id, title, description, starts_at, duration_minutes, doctrine, form_up, fc_character_id, created_by_character, created_at, cancelled_at FROM ops WHERE id = $1
`

func (q *Queries) GetOp(ctx context.Context, id int64) (Op, error) {
	row := q.db.QueryRowContext(ctx, getOp, id)
	var i Op
	err := row.Scan(
		&i.ID,
		&i.CorporationID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.DurationMinutes,
		&i.Doctrine,
		&i.FormUp,
		&i.FcCharacterID,
		&i.CreatedByCharacter,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const listCharacterCorporationsByUser = `-- name: ListCharacterCorporationsByUser :many

SELECT c.character_id, c.name, cc.corporation_id
FROM characters c
JOIN character_corporations cc ON cc.character_id = c.character_id
WHERE c.user_id = $1
ORDER BY c.character_id
`

type ListCharacterCorporationsByUserRow struct {
	CharacterID   int64  `json:"character_id"`
	Name          string `json:"name"`
	CorporationID int64  `json:"corporation_id"`
}

// ---------------------------------------------------------------------
// Ops (schema 014): EveSynapse's own calendar entries and the
// sign-ups to them.
// ---------------------------------------------------------------------
// The corporation of each of an account's characters.
func (q *Queries) ListCharacterCorporationsByUser(ctx context.Context, userID int64) ([]ListCharacterCorporationsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listCharacterCorporationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharacterCorporationsByUserRow
	for rows.Next() {
		var i ListCharacterCorporationsByUserRow
		if err := rows.Scan(&i.CharacterID, &i.Name, &i.CorporationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpSignups = `-- name: ListOpSignups :many
SELECT op_id, character_id, user_id, response, ship, fleet_role, note, updated_at FROM op_signups WHERE op_id = $1 ORDER BY character_id
`

func (q *Queries) ListOpSignups(ctx context.Context, opID int64) ([]OpSignup, error) {
	rows, err := q.db.QueryContext(ctx, listOpSignups, opID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpSignup
	for rows.Next() {
		var i OpSignup
		if err := rows.Scan(
			&i.OpID,
			&i.CharacterID,
			&i.UserID,
			&i.Response,
			&i.Ship,
			&i.FleetRole,
			&i.Note,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpSignupsForOps = `-- name: ListOpSignupsForOps :many
SELECT op_id, character_id, user_id, response FROM op_signups
WHERE op_id = ANY($1::bigint[])
`

type ListOpSignupsForOpsRow struct {
	OpID        int64  `json:"op_id"`
	CharacterID int64  `json:"character_id"`
	UserID      int64  `json:"user_id"`
	Response    string `json:"response"`
}

func (q *Queries) ListOpSignupsForOps(ctx context.Context, opIds []int64) ([]ListOpSignupsForOpsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpSignupsForOps, pq.Array(opIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpSignupsForOpsRow
	for rows.Next() {
		var i ListOpSignupsForOpsRow
		if err := rows.Scan(
			&i.OpID,
			&i.CharacterID,
			&i.UserID,
			&i.Response,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpsForCorporationsBetween = `-- name: ListOpsForCorporationsBetween :many
SELECT id, corporation_id, title, description, starts_at, duration_minutes, doctrine, form_up, fc_character_id, created_by_character, created_at, cancelled_at FROM ops
WHERE corporation_id = ANY($1::bigint[])
  AND starts_at >= $2 AND starts_at < $3
ORDER BY starts_at, id
`

type ListOpsForCorporationsBetweenParams struct {
	CorporationIds []int64   `json:"corporation_ids"`
	FromTime       time.Time `json:"from_time"`
	ToTime         time.Time `json:"to_time"`
}

func (q *Queries) ListOpsForCorporationsBetween(ctx context.Context, arg ListOpsForCorporationsBetweenParams) ([]Op, error) {
	rows, err := q.db.QueryContext(ctx, listOpsForCorporationsBetween, pq.Array(arg.CorporationIds), arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Op
	for rows.Next() {
		var i Op
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.DurationMinutes,
			&i.Doctrine,
			&i.FormUp,
			&i.FcCharacterID,
			&i.CreatedByCharacter,
			&i.CreatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOpCancelled = `-- name: SetOpCancelled :exec
UPDATE ops SET cancelled_at = $1 WHERE id = $2
`

type SetOpCancelledParams struct {
	CancelledAt sql.NullTime `json:"cancelled_at"`
	ID          int64        `json:"id"`
}

func (q *Queries) SetOpCancelled(ctx context.Context, arg SetOpCancelledParams) error {
	_, err := q.db.ExecContext(ctx, setOpCancelled, arg.CancelledAt, arg.ID)
	return err
}

const updateOp = `-- name: UpdateOp :exec
UPDATE ops SET
    title            = $1,
    description      = $2,
    starts_at        = $3,
    duration_minutes = $4,
    doctrine         = $5,
    form_up          = $6,
    fc_character_id  = $7
WHERE id = $8
`

type UpdateOpParams struct {
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	StartsAt        time.Time `json:"starts_at"`
	DurationMinutes int64     `json:"duration_minutes"`
	Doctrine        string    `json:"doctrine"`
	FormUp          string    `json:"form_up"`
	FcCharacterID   int64     `json:"fc_character_id"`
	ID              int64     `json:"id"`
}

func (q *Queries) UpdateOp(ctx context.Context, arg UpdateOpParams) error {
	_, err := q.db.ExecContext(ctx, updateOp,
		arg.Title,
		arg.Description,
		arg.StartsAt,
		arg.DurationMinutes,
		arg.Doctrine,
		arg.FormUp,
		arg.FcCharacterID,
		arg.ID,
	)
	return err
}

const upsertOpSignup = `-- name: UpsertOpSignup :exec
INSERT INTO op_signups (op_id, character_id, user_id, response, ship, fleet_role, note, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (op_id, character_id) DO UPDATE SET
    user_id    = excluded.user_id,
    response   = excluded.response,
    ship       = excluded.ship,
    fleet_role = excluded.fleet_role,
    note       = excluded.note,
    updated_at = excluded.updated_at
`

type UpsertOpSignupParams struct {
	OpID        int64     `json:"op_id"`
	CharacterID int64     `json:"character_id"`
	UserID      int64     `json:"user_id"`
	Response    string    `json:"response"`
	Ship        string    `json:"ship"`
	FleetRole   string    `json:"fleet_role"`
	Note        string    `json:"note"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpsertOpSignup(ctx context.Context, arg UpsertOpSignupParams) error {
	_, err := q.db.ExecContext(ctx, upsertOpSignup,
		arg.OpID,
		arg.CharacterID,
		arg.UserID,
		arg.Response,
		arg.Ship,
		arg.FleetRole,
		arg.Note,
		arg.UpdatedAt,
	)
	return err
}
