// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_groups.sql

package db

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const addOrgGroupMember = `-- name: AddOrgGroupMember :exec
INSERT INTO org_group_members (group_id, character_id, added_by, added_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddOrgGroupMemberParams struct {
	GroupID     int64     `json:"group_id"`
	CharacterID int64     `json:"character_id"`
	AddedBy     int64     `json:"added_by"`
	AddedAt     time.Time `json:"added_at"`
}

func (q *Queries) AddOrgGroupMember(ctx context.Context, arg AddOrgGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addOrgGroupMember,
		arg.GroupID,
		arg.CharacterID,
		arg.AddedBy,
		arg.AddedAt,
	)
	return err
}

const createOrgGroup = `-- name: CreateOrgGroup :one
INSERT INTO org_groups (owner_kind, owner_id, name, description, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateOrgGroupParams struct {
	OwnerKind   string    `json:"owner_kind"`
	OwnerID     int64     `json:"owner_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedBy   int64     `json:"created_by"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateOrgGroup(ctx context.Context, arg CreateOrgGroupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOrgGroup,
		arg.OwnerKind,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteDiscordRoleRule = `-- name: DeleteDiscordRoleRule :exec
DELETE FROM discord_role_rules WHERE id = $1 AND guild_id = $2
`

type DeleteDiscordRoleRuleParams struct {
	ID      int64  `json:"id"`
	GuildID string `json:"guild_id"`
}

func (q *Queries) DeleteDiscordRoleRule(ctx context.Context, arg DeleteDiscordRoleRuleParams) error {
	_, err := q.db.ExecContext(ctx, deleteDiscordRoleRule, arg.ID, arg.GuildID)
	return err
}

const deleteDiscordRoleRulesForGroup = `-- name: DeleteDiscordRoleRulesForGroup :exec
DELETE FROM discord_role_rules WHERE kind = 'group' AND ref = $1
`

// A group that is deleted takes the rules that named it along.
func (q *Queries) DeleteDiscordRoleRulesForGroup(ctx context.Context, groupRef string) error {
	_, err := q.db.ExecContext(ctx, deleteDiscordRoleRulesForGroup, groupRef)
	return err
}

const deleteDiscordRoleRulesForGuild = `-- name: DeleteDiscordRoleRulesForGuild :exec
DELETE FROM discord_role_rules WHERE guild_id = $1
`

func (q *Queries) DeleteDiscordRoleRulesForGuild(ctx context.Context, guildID string) error {
	_, err := q.db.ExecContext(ctx, deleteDiscordRoleRulesForGuild, guildID)
	return err
}

const deleteOrgGroup = `-- name: DeleteOrgGroup :exec
DELETE FROM org_groups WHERE id = $1
`

func (q *Queries) DeleteOrgGroup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrgGroup, id)
	return err
}

const getOrgGroup = `-- name: GetOrgGroup :one
SELECT id, owner_kind, owner_id, name, description, created_by, created_at FROM org_groups WHERE id = $1
`

func (q *Queries) GetOrgGroup(ctx context.Context, id int64) (OrgGroup, error) {
	row := q.db.QueryRowContext(ctx, getOrgGroup, id)
	var i OrgGroup
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertDiscordRoleRule = `-- name: InsertDiscordRoleRule :exec
INSERT INTO discord_role_rules (guild_id, kind, ref, role_id, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (guild_id, kind, ref, role_id) DO NOTHING
`

type InsertDiscordRoleRuleParams struct {
	GuildID   string    `json:"guild_id"`
	Kind      string    `json:"kind"`
	Ref       string    `json:"ref"`
	RoleID    string    `json:"role_id"`
	CreatedBy int64     `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertDiscordRoleRule(ctx context.Context, arg InsertDiscordRoleRuleParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscordRoleRule,
		arg.GuildID,
		arg.Kind,
		arg.Ref,
		arg.RoleID,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const listCharactersInCorporations = `-- name: ListCharactersInCorporations :many
SELECT c.character_id, c.name, cc.corporation_id
FROM characters c
JOIN character_corporations cc ON cc.character_id = c.character_id
WHERE cc.corporation_id = ANY($1::bigint[])
ORDER BY lower(c.name), c.character_id
`

type ListCharactersInCorporationsRow struct {
	CharacterID   int64  `json:"character_id"`
	Name          string `json:"name"`
	CorporationID int64  `json:"corporation_id"`
}

// Every linked character in a set of corporations: who a director can
// put in a group.
func (q *Queries) ListCharactersInCorporations(ctx context.Context, corporationIds []int64) ([]ListCharactersInCorporationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCharactersInCorporations, pq.Array(corporationIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharactersInCorporationsRow
	for rows.Next() {
		var i ListCharactersInCorporationsRow
		if err := rows.Scan(&i.CharacterID, &i.Name, &i.CorporationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscordRoleRules = `-- name: ListDiscordRoleRules :many

SELECT id, guild_id, kind, ref, role_id, created_by, created_at FROM discord_role_rules ORDER BY guild_id, id
`

// ---------------------------------------------------------------------
// Discord role rules and groups (schema 019).
// ---------------------------------------------------------------------
func (q *Queries) ListDiscordRoleRules(ctx context.Context) ([]DiscordRoleRule, error) {
	rows, err := q.db.QueryContext(ctx, listDiscordRoleRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscordRoleRule
	for rows.Next() {
		var i DiscordRoleRule
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Kind,
			&i.Ref,
			&i.RoleID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscordRoleRulesForGuild = `-- name: ListDiscordRoleRulesForGuild :many
SELECT id, guild_id, kind, ref, role_id, created_by, created_at FROM discord_role_rules WHERE guild_id = $1 ORDER BY id
`

func (q *Queries) ListDiscordRoleRulesForGuild(ctx context.Context, guildID string) ([]DiscordRoleRule, error) {
	rows, err := q.db.QueryContext(ctx, listDiscordRoleRulesForGuild, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscordRoleRule
	for rows.Next() {
		var i DiscordRoleRule
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Kind,
			&i.Ref,
			&i.RoleID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnownCorporations = `-- name: ListKnownCorporations :many
SELECT DISTINCT corporation_id FROM character_corporations ORDER BY corporation_id
`

// The corporations EveSynapse has seen linked characters in.
func (q *Queries) ListKnownCorporations(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listKnownCorporations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var corporation_id int64
		if err := rows.Scan(&corporation_id); err != nil {
			return nil, err
		}
		items = append(items, corporation_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgGroupMembers = `-- name: ListOrgGroupMembers :many
SELECT m.character_id, m.added_at,
       COALESCE(c.name, '')::text AS name,
       COALESCE(cc.corporation_id, 0)::bigint AS corporation_id
FROM org_group_members m
LEFT JOIN characters c ON c.character_id = m.character_id
LEFT JOIN character_corporations cc ON cc.character_id = m.character_id
WHERE m.group_id = $1
ORDER BY lower(COALESCE(c.name, '')), m.character_id
`

type ListOrgGroupMembersRow struct {
	CharacterID   int64     `json:"character_id"`
	AddedAt       time.Time `json:"added_at"`
	Name          string    `json:"name"`
	CorporationID int64     `json:"corporation_id"`
}

// The members of a group, with the name and corporation EveSynapse
// has for each character that is linked here. A member that is not
// linked has no name and no corporation.
func (q *Queries) ListOrgGroupMembers(ctx context.Context, groupID int64) ([]ListOrgGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrgGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgGroupMembersRow
	for rows.Next() {
		var i ListOrgGroupMembersRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.AddedAt,
			&i.Name,
			&i.CorporationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgGroupsByUser = `-- name: ListOrgGroupsByUser :many
SELECT m.group_id, m.character_id, g.owner_kind, g.owner_id
FROM org_group_members m
JOIN org_groups g ON g.id = m.group_id
JOIN characters c ON c.character_id = m.character_id
WHERE c.user_id = $1 AND c.link_state = 'ok'
`

type ListOrgGroupsByUserRow struct {
	GroupID     int64  `json:"group_id"`
	CharacterID int64  `json:"character_id"`
	OwnerKind   string `json:"owner_kind"`
	OwnerID     int64  `json:"owner_id"`
}

// The groups each working character of an account is in.
func (q *Queries) ListOrgGroupsByUser(ctx context.Context, userID int64) ([]ListOrgGroupsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrgGroupsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgGroupsByUserRow
	for rows.Next() {
		var i ListOrgGroupsByUserRow
		if err := rows.Scan(
			&i.GroupID,
			&i.CharacterID,
			&i.OwnerKind,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgGroupsForOwner = `-- name: ListOrgGroupsForOwner :many

SELECT id, owner_kind, owner_id, name, description, created_by, created_at FROM org_groups
WHERE owner_kind = $1 AND owner_id = $2
ORDER BY lower(name), id
`

type ListOrgGroupsForOwnerParams struct {
	OwnerKind string `json:"owner_kind"`
	OwnerID   int64  `json:"owner_id"`
}

// Groups.
func (q *Queries) ListOrgGroupsForOwner(ctx context.Context, arg ListOrgGroupsForOwnerParams) ([]OrgGroup, error) {
	rows, err := q.db.QueryContext(ctx, listOrgGroupsForOwner, arg.OwnerKind, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgGroup
	for rows.Next() {
		var i OrgGroup
		if err := rows.Scan(
			&i.ID,
			&i.OwnerKind,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkingCharacterCorporationsByUser = `-- name: ListWorkingCharacterCorporationsByUser :many
SELECT c.character_id, c.name, cc.corporation_id
FROM characters c
JOIN character_corporations cc ON cc.character_id = c.character_id
WHERE c.user_id = $1 AND c.link_state = 'ok'
ORDER BY c.character_id
`

type ListWorkingCharacterCorporationsByUserRow struct {
	CharacterID   int64  `json:"character_id"`
	Name          string `json:"name"`
	CorporationID int64  `json:"corporation_id"`
}

// The working characters of an account, each with its corporation.
func (q *Queries) ListWorkingCharacterCorporationsByUser(ctx context.Context, userID int64) ([]ListWorkingCharacterCorporationsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkingCharacterCorporationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkingCharacterCorporationsByUserRow
	for rows.Next() {
		var i ListWorkingCharacterCorporationsByUserRow
		if err := rows.Scan(&i.CharacterID, &i.Name, &i.CorporationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrgGroupMember = `-- name: RemoveOrgGroupMember :exec
DELETE FROM org_group_members WHERE group_id = $1 AND character_id = $2
`

type RemoveOrgGroupMemberParams struct {
	GroupID     int64 `json:"group_id"`
	CharacterID int64 `json:"character_id"`
}

func (q *Queries) RemoveOrgGroupMember(ctx context.Context, arg RemoveOrgGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeOrgGroupMember, arg.GroupID, arg.CharacterID)
	return err
}

const setDiscordGuildOpsChannel = `-- name: SetDiscordGuildOpsChannel :exec
UPDATE discord_guilds SET ops_channel = $1 WHERE guild_id = $2
`

type SetDiscordGuildOpsChannelParams struct {
	OpsChannel string `json:"ops_channel"`
	GuildID    string `json:"guild_id"`
}

func (q *Queries) SetDiscordGuildOpsChannel(ctx context.Context, arg SetDiscordGuildOpsChannelParams) error {
	_, err := q.db.ExecContext(ctx, setDiscordGuildOpsChannel, arg.OpsChannel, arg.GuildID)
	return err
}
