// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_ops.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createOp = `-- name: CreateOp :one
INSERT INTO ops (corporation_id, title, description, starts_at, duration_minutes, doctrine, form_up, fc_character_id, created_by_character, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type CreateOpParams struct {
	CorporationID      int64     `json:"corporation_id"`
	Title              string    `json:"title"`
	Description        string    `json:"description"`
	StartsAt           time.Time `json:"starts_at"`
	DurationMinutes    int64     `json:"duration_minutes"`
	Doctrine           string    `json:"doctrine"`
	FormUp             string    `json:"form_up"`
	FcCharacterID      int64     `json:"fc_character_id"`
	CreatedByCharacter int64     `json:"created_by_character"`
	CreatedAt          time.Time `json:"created_at"`
}

func (q *Queries) CreateOp(ctx context.Context, arg CreateOpParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOp,
		arg.CorporationID,
		arg.Title,
		arg.Description,
		arg.StartsAt,
		arg.DurationMinutes,
		arg.Doctrine,
		arg.FormUp,
		arg.FcCharacterID,
		arg.CreatedByCharacter,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteManualAttendanceExcept = `-- name: DeleteManualAttendanceExcept :exec
DELETE FROM op_attendance
WHERE op_id = $1 AND source = 'manual'
  AND NOT (character_id = ANY($2::bigint[]))
`

type DeleteManualAttendanceExceptParams struct {
	OpID    int64   `json:"op_id"`
	KeepIds []int64 `json:"keep_ids"`
}

func (q *Queries) DeleteManualAttendanceExcept(ctx context.Context, arg DeleteManualAttendanceExceptParams) error {
	_, err := q.db.ExecContext(ctx, deleteManualAttendanceExcept, arg.OpID, pq.Array(arg.KeepIds))
	return err
}

const getOp = `-- name: GetOp :one
SELECT id, corporation_id, title, description, starts_at, duration_minutes, doctrine, form_up, fc_character_id, created_by_character, created_at, cancelled_at, capture_status, capture_checked_at, discord_announced_at FROM ops WHERE id = $1
`

func (q *Queries) GetOp(ctx context.Context, id int64) (Op, error) {
	row := q.db.QueryRowContext(ctx, getOp, id)
	var i Op
	err := row.Scan(
		&i.ID,
		&i.CorporationID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.DurationMinutes,
		&i.Doctrine,
		&i.FormUp,
		&i.FcCharacterID,
		&i.CreatedByCharacter,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.CaptureStatus,
		&i.CaptureCheckedAt,
		&i.DiscordAnnouncedAt,
	)
	return i, err
}

const insertManualAttendance = `-- name: InsertManualAttendance :exec
INSERT INTO op_attendance (op_id, character_id, source, first_seen_at, last_seen_at)
VALUES ($1, $2, 'manual', $3, $3)
ON CONFLICT (op_id, character_id) DO NOTHING
`

type InsertManualAttendanceParams struct {
	OpID        int64     `json:"op_id"`
	CharacterID int64     `json:"character_id"`
	SeenAt      time.Time `json:"seen_at"`
}

// Marked by hand. Never touches a row the fleet reported.
func (q *Queries) InsertManualAttendance(ctx context.Context, arg InsertManualAttendanceParams) error {
	_, err := q.db.ExecContext(ctx, insertManualAttendance, arg.OpID, arg.CharacterID, arg.SeenAt)
	return err
}

const listCharacterCorporationsByUser = `-- name: ListCharacterCorporationsByUser :many

SELECT c.character_id, c.name, cc.corporation_id
FROM characters c
JOIN character_corporations cc ON cc.character_id = c.character_id
WHERE c.user_id = $1
ORDER BY c.character_id
`

type ListCharacterCorporationsByUserRow struct {
	CharacterID   int64  `json:"character_id"`
	Name          string `json:"name"`
	CorporationID int64  `json:"corporation_id"`
}

// ---------------------------------------------------------------------
// Ops (schema 014): EveSynapse's own calendar entries and the
// sign-ups to them.
// ---------------------------------------------------------------------
// The corporation of each of an account's characters.
func (q *Queries) ListCharacterCorporationsByUser(ctx context.Context, userID int64) ([]ListCharacterCorporationsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listCharacterCorporationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharacterCorporationsByUserRow
	for rows.Next() {
		var i ListCharacterCorporationsByUserRow
		if err := rows.Scan(&i.CharacterID, &i.Name, &i.CorporationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCorporationPAPs = `-- name: ListCorporationPAPs :many
SELECT a.character_id,
       COUNT(*)::bigint AS total,
       COUNT(*) FILTER (WHERE o.starts_at >= $1)::bigint AS recent,
       MAX(o.starts_at)::timestamptz AS last_op
FROM op_attendance a
JOIN ops o ON o.id = a.op_id
WHERE o.corporation_id = $2
  AND o.cancelled_at IS NULL
  AND o.starts_at >= $3
GROUP BY a.character_id
ORDER BY total DESC, a.character_id
`

type ListCorporationPAPsParams struct {
	RecentSince   time.Time `json:"recent_since"`
	CorporationID int64     `json:"corporation_id"`
	Since         time.Time `json:"since"`
}

type ListCorporationPAPsRow struct {
	CharacterID int64     `json:"character_id"`
	Total       int64     `json:"total"`
	Recent      int64     `json:"recent"`
	LastOp      time.Time `json:"last_op"`
}

// Attendance counts for a corporation's ops since a date, per
// character: the PAP table.
func (q *Queries) ListCorporationPAPs(ctx context.Context, arg ListCorporationPAPsParams) ([]ListCorporationPAPsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCorporationPAPs, arg.RecentSince, arg.CorporationID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCorporationPAPsRow
	for rows.Next() {
		var i ListCorporationPAPsRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.Total,
			&i.Recent,
			&i.LastOp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpAttendance = `-- name: ListOpAttendance :many
SELECT op_id, character_id, ship_type_id, source, first_seen_at, last_seen_at FROM op_attendance WHERE op_id = $1 ORDER BY character_id
`

func (q *Queries) ListOpAttendance(ctx context.Context, opID int64) ([]OpAttendance, error) {
	rows, err := q.db.QueryContext(ctx, listOpAttendance, opID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpAttendance
	for rows.Next() {
		var i OpAttendance
		if err := rows.Scan(
			&i.OpID,
			&i.CharacterID,
			&i.ShipTypeID,
			&i.Source,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpSignups = `-- name: ListOpSignups :many
SELECT op_id, character_id, user_id, response, ship, fleet_role, note, updated_at FROM op_signups WHERE op_id = $1 ORDER BY character_id
`

func (q *Queries) ListOpSignups(ctx context.Context, opID int64) ([]OpSignup, error) {
	rows, err := q.db.QueryContext(ctx, listOpSignups, opID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpSignup
	for rows.Next() {
		var i OpSignup
		if err := rows.Scan(
			&i.OpID,
			&i.CharacterID,
			&i.UserID,
			&i.Response,
			&i.Ship,
			&i.FleetRole,
			&i.Note,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpSignupsForOps = `-- name: ListOpSignupsForOps :many
SELECT op_id, character_id, user_id, response FROM op_signups
WHERE op_id = ANY($1::bigint[])
`

type ListOpSignupsForOpsRow struct {
	OpID        int64  `json:"op_id"`
	CharacterID int64  `json:"character_id"`
	UserID      int64  `json:"user_id"`
	Response    string `json:"response"`
}

func (q *Queries) ListOpSignupsForOps(ctx context.Context, opIds []int64) ([]ListOpSignupsForOpsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpSignupsForOps, pq.Array(opIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpSignupsForOpsRow
	for rows.Next() {
		var i ListOpSignupsForOpsRow
		if err := rows.Scan(
			&i.OpID,
			&i.CharacterID,
			&i.UserID,
			&i.Response,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpsForCorporationsBetween = `-- name: ListOpsForCorporationsBetween :many
SELECT id, corporation_id, title, description, starts_at, duration_minutes, doctrine, form_up, fc_character_id, created_by_character, created_at, cancelled_at, capture_status, capture_checked_at, discord_announced_at FROM ops
WHERE corporation_id = ANY($1::bigint[])
  AND starts_at >= $2 AND starts_at < $3
ORDER BY starts_at, id
`

type ListOpsForCorporationsBetweenParams struct {
	CorporationIds []int64   `json:"corporation_ids"`
	FromTime       time.Time `json:"from_time"`
	ToTime         time.Time `json:"to_time"`
}

func (q *Queries) ListOpsForCorporationsBetween(ctx context.Context, arg ListOpsForCorporationsBetweenParams) ([]Op, error) {
	rows, err := q.db.QueryContext(ctx, listOpsForCorporationsBetween, pq.Array(arg.CorporationIds), arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Op
	for rows.Next() {
		var i Op
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.DurationMinutes,
			&i.Doctrine,
			&i.FormUp,
			&i.FcCharacterID,
			&i.CreatedByCharacter,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.CaptureStatus,
			&i.CaptureCheckedAt,
			&i.DiscordAnnouncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpsToCapture = `-- name: ListOpsToCapture :many

SELECT id, corporation_id, title, description, starts_at, duration_minutes, doctrine, form_up, fc_character_id, created_by_character, created_at, cancelled_at, capture_status, capture_checked_at, discord_announced_at FROM ops
WHERE cancelled_at IS NULL
  AND fc_character_id <> 0
  AND starts_at <= $1
  AND starts_at + (duration_minutes * interval '1 minute') >= $2
ORDER BY starts_at, id
`

type ListOpsToCaptureParams struct {
	StartsBefore time.Time `json:"starts_before"`
	EndsAfter    time.Time `json:"ends_after"`
}

// ---------------------------------------------------------------------
// Attendance (schema 015).
// ---------------------------------------------------------------------
// Ops whose fleet may be up right now: not cancelled, and inside the
// window from a little before the start to a little after the end.
func (q *Queries) ListOpsToCapture(ctx context.Context, arg ListOpsToCaptureParams) ([]Op, error) {
	rows, err := q.db.QueryContext(ctx, listOpsToCapture, arg.StartsBefore, arg.EndsAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Op
	for rows.Next() {
		var i Op
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.DurationMinutes,
			&i.Doctrine,
			&i.FormUp,
			&i.FcCharacterID,
			&i.CreatedByCharacter,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.CaptureStatus,
			&i.CaptureCheckedAt,
			&i.DiscordAnnouncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOpCancelled = `-- name: SetOpCancelled :exec
UPDATE ops SET cancelled_at = $1 WHERE id = $2
`

type SetOpCancelledParams struct {
	CancelledAt sql.NullTime `json:"cancelled_at"`
	ID          int64        `json:"id"`
}

func (q *Queries) SetOpCancelled(ctx context.Context, arg SetOpCancelledParams) error {
	_, err := q.db.ExecContext(ctx, setOpCancelled, arg.CancelledAt, arg.ID)
	return err
}

const setOpCaptureStatus = `-- name: SetOpCaptureStatus :exec
UPDATE ops SET capture_status = $1, capture_checked_at = $2
WHERE id = $3
`

type SetOpCaptureStatusParams struct {
	CaptureStatus string       `json:"capture_status"`
	CheckedAt     sql.NullTime `json:"checked_at"`
	ID            int64        `json:"id"`
}

func (q *Queries) SetOpCaptureStatus(ctx context.Context, arg SetOpCaptureStatusParams) error {
	_, err := q.db.ExecContext(ctx, setOpCaptureStatus, arg.CaptureStatus, arg.CheckedAt, arg.ID)
	return err
}

const updateOp = `-- name: UpdateOp :exec
UPDATE ops SET
    title            = $1,
    description      = $2,
    starts_at        = $3,
    duration_minutes = $4,
    doctrine         = $5,
    form_up          = $6,
    fc_character_id  = $7
WHERE id = $8
`

type UpdateOpParams struct {
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	StartsAt        time.Time `json:"starts_at"`
	DurationMinutes int64     `json:"duration_minutes"`
	Doctrine        string    `json:"doctrine"`
	FormUp          string    `json:"form_up"`
	FcCharacterID   int64     `json:"fc_character_id"`
	ID              int64     `json:"id"`
}

func (q *Queries) UpdateOp(ctx context.Context, arg UpdateOpParams) error {
	_, err := q.db.ExecContext(ctx, updateOp,
		arg.Title,
		arg.Description,
		arg.StartsAt,
		arg.DurationMinutes,
		arg.Doctrine,
		arg.FormUp,
		arg.FcCharacterID,
		arg.ID,
	)
	return err
}

const upsertFleetAttendance = `-- name: UpsertFleetAttendance :exec
INSERT INTO op_attendance (op_id, character_id, ship_type_id, source, first_seen_at, last_seen_at)
VALUES ($1, $2, $3, 'fleet', $4, $4)
ON CONFLICT (op_id, character_id) DO UPDATE SET
    ship_type_id = excluded.ship_type_id,
    source       = 'fleet',
    last_seen_at = excluded.last_seen_at
`

type UpsertFleetAttendanceParams struct {
	OpID        int64     `json:"op_id"`
	CharacterID int64     `json:"character_id"`
	ShipTypeID  int64     `json:"ship_type_id"`
	SeenAt      time.Time `json:"seen_at"`
}

// Seen in the fleet. A character already marked by hand becomes a
// fleet sighting: the fleet is the better witness.
func (q *Queries) UpsertFleetAttendance(ctx context.Context, arg UpsertFleetAttendanceParams) error {
	_, err := q.db.ExecContext(ctx, upsertFleetAttendance,
		arg.OpID,
		arg.CharacterID,
		arg.ShipTypeID,
		arg.SeenAt,
	)
	return err
}

const upsertOpSignup = `-- name: UpsertOpSignup :exec
INSERT INTO op_signups (op_id, character_id, user_id, response, ship, fleet_role, note, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (op_id, character_id) DO UPDATE SET
    user_id    = excluded.user_id,
    response   = excluded.response,
    ship       = excluded.ship,
    fleet_role = excluded.fleet_role,
    note       = excluded.note,
    updated_at = excluded.updated_at
`

type UpsertOpSignupParams struct {
	OpID        int64     `json:"op_id"`
	CharacterID int64     `json:"character_id"`
	UserID      int64     `json:"user_id"`
	Response    string    `json:"response"`
	Ship        string    `json:"ship"`
	FleetRole   string    `json:"fleet_role"`
	Note        string    `json:"note"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpsertOpSignup(ctx context.Context, arg UpsertOpSignupParams) error {
	_, err := q.db.ExecContext(ctx, upsertOpSignup,
		arg.OpID,
		arg.CharacterID,
		arg.UserID,
		arg.Response,
		arg.Ship,
		arg.FleetRole,
		arg.Note,
		arg.UpdatedAt,
	)
	return err
}
