// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_srp.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createSRPRequest = `-- name: CreateSRPRequest :one
INSERT INTO srp_requests (corporation_id, op_id, killmail_id, killmail_hash, character_id, user_id,
                          ship_type_id, solar_system_id, lost_at, loss_value, note, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (killmail_id) DO NOTHING
RETURNING id
`

type CreateSRPRequestParams struct {
	CorporationID int64     `json:"corporation_id"`
	OpID          int64     `json:"op_id"`
	KillmailID    int64     `json:"killmail_id"`
	KillmailHash  string    `json:"killmail_hash"`
	CharacterID   int64     `json:"character_id"`
	UserID        int64     `json:"user_id"`
	ShipTypeID    int64     `json:"ship_type_id"`
	SolarSystemID int64     `json:"solar_system_id"`
	LostAt        time.Time `json:"lost_at"`
	LossValue     float64   `json:"loss_value"`
	Note          string    `json:"note"`
	CreatedAt     time.Time `json:"created_at"`
}

// A killmail is claimed once: a second request for it creates nothing.
func (q *Queries) CreateSRPRequest(ctx context.Context, arg CreateSRPRequestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSRPRequest,
		arg.CorporationID,
		arg.OpID,
		arg.KillmailID,
		arg.KillmailHash,
		arg.CharacterID,
		arg.UserID,
		arg.ShipTypeID,
		arg.SolarSystemID,
		arg.LostAt,
		arg.LossValue,
		arg.Note,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const decideSRPRequest = `-- name: DecideSRPRequest :execrows
UPDATE srp_requests SET
    status       = $1,
    payout       = $2,
    handled_by   = $3,
    handler_note = $4,
    handled_at   = $5
WHERE id = $6 AND status = 'open'
`

type DecideSRPRequestParams struct {
	Status      string       `json:"status"`
	Payout      float64      `json:"payout"`
	HandledBy   int64        `json:"handled_by"`
	HandlerNote string       `json:"handler_note"`
	HandledAt   sql.NullTime `json:"handled_at"`
	ID          int64        `json:"id"`
}

// Only an open request is decided, so two handlers cannot both pay one.
func (q *Queries) DecideSRPRequest(ctx context.Context, arg DecideSRPRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decideSRPRequest,
		arg.Status,
		arg.Payout,
		arg.HandledBy,
		arg.HandlerNote,
		arg.HandledAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCorpPermission = `-- name: DeleteCorpPermission :exec
DELETE FROM corp_permissions WHERE corporation_id = $1 AND permission = $2
`

type DeleteCorpPermissionParams struct {
	CorporationID int64  `json:"corporation_id"`
	Permission    string `json:"permission"`
}

func (q *Queries) DeleteCorpPermission(ctx context.Context, arg DeleteCorpPermissionParams) error {
	_, err := q.db.ExecContext(ctx, deleteCorpPermission, arg.CorporationID, arg.Permission)
	return err
}

const getCorpPermission = `-- name: GetCorpPermission :one

SELECT corporation_id, permission, kind, ref, updated_by, updated_at FROM corp_permissions WHERE corporation_id = $1 AND permission = $2
`

type GetCorpPermissionParams struct {
	CorporationID int64  `json:"corporation_id"`
	Permission    string `json:"permission"`
}

// ---------------------------------------------------------------------
// Ship replacement (schema 025), and who runs a corporation's
// programmes.
// ---------------------------------------------------------------------
func (q *Queries) GetCorpPermission(ctx context.Context, arg GetCorpPermissionParams) (CorpPermission, error) {
	row := q.db.QueryRowContext(ctx, getCorpPermission, arg.CorporationID, arg.Permission)
	var i CorpPermission
	err := row.Scan(
		&i.CorporationID,
		&i.Permission,
		&i.Kind,
		&i.Ref,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpAttendance = `-- name: GetOpAttendance :one
SELECT op_id, character_id, ship_type_id, source, first_seen_at, last_seen_at FROM op_attendance WHERE op_id = $1 AND character_id = $2
`

type GetOpAttendanceParams struct {
	OpID        int64 `json:"op_id"`
	CharacterID int64 `json:"character_id"`
}

func (q *Queries) GetOpAttendance(ctx context.Context, arg GetOpAttendanceParams) (OpAttendance, error) {
	row := q.db.QueryRowContext(ctx, getOpAttendance, arg.OpID, arg.CharacterID)
	var i OpAttendance
	err := row.Scan(
		&i.OpID,
		&i.CharacterID,
		&i.ShipTypeID,
		&i.Source,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getSRPRequest = `-- name: GetSRPRequest :one
SELECT id, corporation_id, op_id, killmail_id, killmail_hash, character_id, user_id, ship_type_id, solar_system_id, lost_at, loss_value, note, status, payout, handled_by, handler_note, handled_at, created_at FROM srp_requests WHERE id = $1
`

func (q *Queries) GetSRPRequest(ctx context.Context, id int64) (SrpRequest, error) {
	row := q.db.QueryRowContext(ctx, getSRPRequest, id)
	var i SrpRequest
	err := row.Scan(
		&i.ID,
		&i.CorporationID,
		&i.OpID,
		&i.KillmailID,
		&i.KillmailHash,
		&i.CharacterID,
		&i.UserID,
		&i.ShipTypeID,
		&i.SolarSystemID,
		&i.LostAt,
		&i.LossValue,
		&i.Note,
		&i.Status,
		&i.Payout,
		&i.HandledBy,
		&i.HandlerNote,
		&i.HandledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSRPSettings = `-- name: GetSRPSettings :one
SELECT corporation_id, policy, updated_at FROM srp_settings WHERE corporation_id = $1
`

func (q *Queries) GetSRPSettings(ctx context.Context, corporationID int64) (SrpSetting, error) {
	row := q.db.QueryRowContext(ctx, getSRPSettings, corporationID)
	var i SrpSetting
	err := row.Scan(&i.CorporationID, &i.Policy, &i.UpdatedAt)
	return i, err
}

const listHandledSRPRequests = `-- name: ListHandledSRPRequests :many
SELECT id, corporation_id, op_id, killmail_id, killmail_hash, character_id, user_id, ship_type_id, solar_system_id, lost_at, loss_value, note, status, payout, handled_by, handler_note, handled_at, created_at FROM srp_requests
WHERE corporation_id = $1 AND status <> 'open'
ORDER BY handled_at DESC NULLS LAST, id DESC
LIMIT $2::bigint
`

type ListHandledSRPRequestsParams struct {
	CorporationID int64 `json:"corporation_id"`
	RowLimit      int64 `json:"row_limit"`
}

func (q *Queries) ListHandledSRPRequests(ctx context.Context, arg ListHandledSRPRequestsParams) ([]SrpRequest, error) {
	rows, err := q.db.QueryContext(ctx, listHandledSRPRequests, arg.CorporationID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SrpRequest
	for rows.Next() {
		var i SrpRequest
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.OpID,
			&i.KillmailID,
			&i.KillmailHash,
			&i.CharacterID,
			&i.UserID,
			&i.ShipTypeID,
			&i.SolarSystemID,
			&i.LostAt,
			&i.LossValue,
			&i.Note,
			&i.Status,
			&i.Payout,
			&i.HandledBy,
			&i.HandlerNote,
			&i.HandledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLossDetails = `-- name: ListLossDetails :many
SELECT killmail_id, hash, payload FROM killmail_details
WHERE killmail_id = ANY($1::bigint[])
  AND (payload::jsonb -> 'victim' ->> 'character_id')::bigint = ANY($2::bigint[])
ORDER BY killmail_id DESC
`

type ListLossDetailsParams struct {
	KillmailIds  []int64 `json:"killmail_ids"`
	CharacterIds []int64 `json:"character_ids"`
}

type ListLossDetailsRow struct {
	KillmailID int64  `json:"killmail_id"`
	Hash       string `json:"hash"`
	Payload    string `json:"payload"`
}

// The stored killmails among those named whose victim is one of the
// characters named: a pilot's own losses.
func (q *Queries) ListLossDetails(ctx context.Context, arg ListLossDetailsParams) ([]ListLossDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLossDetails, pq.Array(arg.KillmailIds), pq.Array(arg.CharacterIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLossDetailsRow
	for rows.Next() {
		var i ListLossDetailsRow
		if err := rows.Scan(&i.KillmailID, &i.Hash, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenSRPRequests = `-- name: ListOpenSRPRequests :many
SELECT id, corporation_id, op_id, killmail_id, killmail_hash, character_id, user_id, ship_type_id, solar_system_id, lost_at, loss_value, note, status, payout, handled_by, handler_note, handled_at, created_at FROM srp_requests
WHERE corporation_id = ANY($1::bigint[]) AND status = 'open'
ORDER BY created_at, id
`

func (q *Queries) ListOpenSRPRequests(ctx context.Context, corporationIds []int64) ([]SrpRequest, error) {
	rows, err := q.db.QueryContext(ctx, listOpenSRPRequests, pq.Array(corporationIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SrpRequest
	for rows.Next() {
		var i SrpRequest
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.OpID,
			&i.KillmailID,
			&i.KillmailHash,
			&i.CharacterID,
			&i.UserID,
			&i.ShipTypeID,
			&i.SolarSystemID,
			&i.LostAt,
			&i.LossValue,
			&i.Note,
			&i.Status,
			&i.Payout,
			&i.HandledBy,
			&i.HandlerNote,
			&i.HandledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSRPClaimedKillmails = `-- name: ListSRPClaimedKillmails :many
SELECT killmail_id FROM srp_requests WHERE killmail_id = ANY($1::bigint[])
`

func (q *Queries) ListSRPClaimedKillmails(ctx context.Context, killmailIds []int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listSRPClaimedKillmails, pq.Array(killmailIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var killmail_id int64
		if err := rows.Scan(&killmail_id); err != nil {
			return nil, err
		}
		items = append(items, killmail_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSRPRequestsByUser = `-- name: ListSRPRequestsByUser :many
SELECT id, corporation_id, op_id, killmail_id, killmail_hash, character_id, user_id, ship_type_id, solar_system_id, lost_at, loss_value, note, status, payout, handled_by, handler_note, handled_at, created_at FROM srp_requests WHERE user_id = $1 ORDER BY created_at DESC, id DESC LIMIT $2::bigint
`

type ListSRPRequestsByUserParams struct {
	UserID   int64 `json:"user_id"`
	RowLimit int64 `json:"row_limit"`
}

func (q *Queries) ListSRPRequestsByUser(ctx context.Context, arg ListSRPRequestsByUserParams) ([]SrpRequest, error) {
	rows, err := q.db.QueryContext(ctx, listSRPRequestsByUser, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SrpRequest
	for rows.Next() {
		var i SrpRequest
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.OpID,
			&i.KillmailID,
			&i.KillmailHash,
			&i.CharacterID,
			&i.UserID,
			&i.ShipTypeID,
			&i.SolarSystemID,
			&i.LostAt,
			&i.LossValue,
			&i.Note,
			&i.Status,
			&i.Payout,
			&i.HandledBy,
			&i.HandlerNote,
			&i.HandledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSRPRequestsDecidedForUser = `-- name: ListSRPRequestsDecidedForUser :many
SELECT id, corporation_id, op_id, killmail_id, killmail_hash, character_id, user_id, ship_type_id, solar_system_id, lost_at, loss_value, note, status, payout, handled_by, handler_note, handled_at, created_at FROM srp_requests
WHERE user_id = $1 AND status <> 'open' AND handled_at >= $2
ORDER BY handled_at, id
`

type ListSRPRequestsDecidedForUserParams struct {
	UserID int64        `json:"user_id"`
	Since  sql.NullTime `json:"since"`
}

// A request an account was answered on since a date: what it is told
// about.
func (q *Queries) ListSRPRequestsDecidedForUser(ctx context.Context, arg ListSRPRequestsDecidedForUserParams) ([]SrpRequest, error) {
	rows, err := q.db.QueryContext(ctx, listSRPRequestsDecidedForUser, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SrpRequest
	for rows.Next() {
		var i SrpRequest
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.OpID,
			&i.KillmailID,
			&i.KillmailHash,
			&i.CharacterID,
			&i.UserID,
			&i.ShipTypeID,
			&i.SolarSystemID,
			&i.LostAt,
			&i.LossValue,
			&i.Note,
			&i.Status,
			&i.Payout,
			&i.HandledBy,
			&i.HandlerNote,
			&i.HandledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenSRPRequest = `-- name: ReopenSRPRequest :execrows
UPDATE srp_requests SET status = 'open', payout = 0, handled_by = 0, handler_note = '', handled_at = NULL
WHERE id = $1 AND status <> 'open'
`

func (q *Queries) ReopenSRPRequest(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, reopenSRPRequest, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCorpPermission = `-- name: SetCorpPermission :exec
INSERT INTO corp_permissions (corporation_id, permission, kind, ref, updated_by, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (corporation_id, permission) DO UPDATE SET
    kind       = excluded.kind,
    ref        = excluded.ref,
    updated_by = excluded.updated_by,
    updated_at = excluded.updated_at
`

type SetCorpPermissionParams struct {
	CorporationID int64     `json:"corporation_id"`
	Permission    string    `json:"permission"`
	Kind          string    `json:"kind"`
	Ref           string    `json:"ref"`
	UpdatedBy     int64     `json:"updated_by"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) SetCorpPermission(ctx context.Context, arg SetCorpPermissionParams) error {
	_, err := q.db.ExecContext(ctx, setCorpPermission,
		arg.CorporationID,
		arg.Permission,
		arg.Kind,
		arg.Ref,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const setSRPSettings = `-- name: SetSRPSettings :exec
INSERT INTO srp_settings (corporation_id, policy, updated_at)
VALUES ($1, $2, $3)
ON CONFLICT (corporation_id) DO UPDATE SET
    policy     = excluded.policy,
    updated_at = excluded.updated_at
`

type SetSRPSettingsParams struct {
	CorporationID int64     `json:"corporation_id"`
	Policy        string    `json:"policy"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) SetSRPSettings(ctx context.Context, arg SetSRPSettingsParams) error {
	_, err := q.db.ExecContext(ctx, setSRPSettings, arg.CorporationID, arg.Policy, arg.UpdatedAt)
	return err
}

const sumSRPPaid = `-- name: SumSRPPaid :one
SELECT COUNT(*)::bigint AS requests, COALESCE(SUM(payout), 0)::double precision AS paid
FROM srp_requests
WHERE corporation_id = $1 AND status = 'paid' AND handled_at >= $2
`

type SumSRPPaidParams struct {
	CorporationID int64        `json:"corporation_id"`
	Since         sql.NullTime `json:"since"`
}

type SumSRPPaidRow struct {
	Requests int64   `json:"requests"`
	Paid     float64 `json:"paid"`
}

func (q *Queries) SumSRPPaid(ctx context.Context, arg SumSRPPaidParams) (SumSRPPaidRow, error) {
	row := q.db.QueryRowContext(ctx, sumSRPPaid, arg.CorporationID, arg.Since)
	var i SumSRPPaidRow
	err := row.Scan(&i.Requests, &i.Paid)
	return i, err
}

const withdrawSRPRequest = `-- name: WithdrawSRPRequest :execrows
DELETE FROM srp_requests WHERE id = $1 AND user_id = $2 AND status = 'open'
`

type WithdrawSRPRequestParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// A pilot takes back a request nobody has answered.
func (q *Queries) WithdrawSRPRequest(ctx context.Context, arg WithdrawSRPRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, withdrawSRPRequest, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
