// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_market.sql

package db

import (
	"context"
)

const clearGuidePriceWant = `-- name: ClearGuidePriceWant :exec
DELETE FROM guide_price_wants
WHERE id = 1
`

func (q *Queries) ClearGuidePriceWant(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearGuidePriceWant)
	return err
}

const closeOrderLifecycle = `-- name: CloseOrderLifecycle :exec
UPDATE order_lifecycle
SET closed_at = ?, close_kind = ?, beaten_now = 0
WHERE character_id = ? AND order_id = ? AND closed_at = ''
`

type CloseOrderLifecycleParams struct {
	ClosedAt    string `json:"closed_at"`
	CloseKind   string `json:"close_kind"`
	CharacterID int64  `json:"character_id"`
	OrderID     int64  `json:"order_id"`
}

func (q *Queries) CloseOrderLifecycle(ctx context.Context, arg CloseOrderLifecycleParams) error {
	_, err := q.db.ExecContext(ctx, closeOrderLifecycle,
		arg.ClosedAt,
		arg.CloseKind,
		arg.CharacterID,
		arg.OrderID,
	)
	return err
}

const deleteGuidePrices = `-- name: DeleteGuidePrices :exec
DELETE FROM guide_prices
`

func (q *Queries) DeleteGuidePrices(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteGuidePrices)
	return err
}

const deleteMarketRegionStatsByRegion = `-- name: DeleteMarketRegionStatsByRegion :exec
DELETE FROM market_region_stats
WHERE region_id = ?
`

// P1 region stats (schema 031): worker-written per-(region,
// type) book statistics. A completed sweep replaces a region's
// rows inside one transaction: delete the region, then upsert
// the fresh measures type by type. The daily table keeps one
// snapshot row per (region, type, day) for trend work.
func (q *Queries) DeleteMarketRegionStatsByRegion(ctx context.Context, regionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMarketRegionStatsByRegion, regionID)
	return err
}

const deleteMarketStationStatsByRegion = `-- name: DeleteMarketStationStatsByRegion :exec
DELETE FROM market_station_stats
WHERE region_id = ?
`

// ---------------------------------------------------------------------
// P2 station stats (schema 032): per-(station, type) book
// statistics written by the same whole-region sweeps as the
// region stats above. A completed sweep replaces the region's
// station rows inside the sweep transaction: delete the region,
// then upsert the fresh measures station by station. The
// spread scanner page reads only these rows.
// ---------------------------------------------------------------------
func (q *Queries) DeleteMarketStationStatsByRegion(ctx context.Context, regionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMarketStationStatsByRegion, regionID)
	return err
}

const deleteOrderHealthEntry = `-- name: DeleteOrderHealthEntry :exec
DELETE FROM order_health
WHERE character_id = ? AND order_id = ?
`

type DeleteOrderHealthEntryParams struct {
	CharacterID int64 `json:"character_id"`
	OrderID     int64 `json:"order_id"`
}

func (q *Queries) DeleteOrderHealthEntry(ctx context.Context, arg DeleteOrderHealthEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteOrderHealthEntry, arg.CharacterID, arg.OrderID)
	return err
}

const deleteOrderHealthForCharacter = `-- name: DeleteOrderHealthForCharacter :exec
DELETE FROM order_health
WHERE character_id = ?
`

func (q *Queries) DeleteOrderHealthForCharacter(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrderHealthForCharacter, characterID)
	return err
}

const deleteWatchlistEntry = `-- name: DeleteWatchlistEntry :exec
DELETE FROM market_watchlist
WHERE user_id = ? AND type_id = ? AND region_id = ?
`

type DeleteWatchlistEntryParams struct {
	UserID   int64 `json:"user_id"`
	TypeID   int64 `json:"type_id"`
	RegionID int64 `json:"region_id"`
}

func (q *Queries) DeleteWatchlistEntry(ctx context.Context, arg DeleteWatchlistEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteWatchlistEntry, arg.UserID, arg.TypeID, arg.RegionID)
	return err
}

const getAllianceRecord = `-- name: GetAllianceRecord :one
SELECT alliance_id, payload, state, fetched_at, priority
FROM alliance_records
WHERE alliance_id = ?
`

func (q *Queries) GetAllianceRecord(ctx context.Context, allianceID int64) (AllianceRecord, error) {
	row := q.db.QueryRowContext(ctx, getAllianceRecord, allianceID)
	var i AllianceRecord
	err := row.Scan(
		&i.AllianceID,
		&i.Payload,
		&i.State,
		&i.FetchedAt,
		&i.Priority,
	)
	return i, err
}

const getCorporationRecord = `-- name: GetCorporationRecord :one
SELECT corporation_id, payload, state, fetched_at, priority
FROM corporation_records
WHERE corporation_id = ?
`

// ---------------------------------------------------------------------
// Public corporation & alliance records (schema 026): the queues
// behind /corporation/ and /alliance/. Same posture as pilot
// records: pending rows are always due, ready rows re-check past
// the stale cutoff, missing rows settle for good.
// ---------------------------------------------------------------------
func (q *Queries) GetCorporationRecord(ctx context.Context, corporationID int64) (CorporationRecord, error) {
	row := q.db.QueryRowContext(ctx, getCorporationRecord, corporationID)
	var i CorporationRecord
	err := row.Scan(
		&i.CorporationID,
		&i.Payload,
		&i.State,
		&i.FetchedAt,
		&i.Priority,
	)
	return i, err
}

const getGuidePriceWant = `-- name: GetGuidePriceWant :one
SELECT id, wanted_at FROM guide_price_wants
WHERE id = 1
`

func (q *Queries) GetGuidePriceWant(ctx context.Context) (GuidePriceWant, error) {
	row := q.db.QueryRowContext(ctx, getGuidePriceWant)
	var i GuidePriceWant
	err := row.Scan(&i.ID, &i.WantedAt)
	return i, err
}

const getGuidePricesMeta = `-- name: GetGuidePricesMeta :one
SELECT id, fetched_at, cached_until FROM guide_prices_meta
WHERE id = 1
`

func (q *Queries) GetGuidePricesMeta(ctx context.Context) (GuidePricesMetum, error) {
	row := q.db.QueryRowContext(ctx, getGuidePricesMeta)
	var i GuidePricesMetum
	err := row.Scan(&i.ID, &i.FetchedAt, &i.CachedUntil)
	return i, err
}

const getMarketFetchState = `-- name: GetMarketFetchState :one
SELECT kind, state, detail, attempted_at
FROM market_fetch_state
WHERE kind = ?
`

func (q *Queries) GetMarketFetchState(ctx context.Context, kind string) (MarketFetchState, error) {
	row := q.db.QueryRowContext(ctx, getMarketFetchState, kind)
	var i MarketFetchState
	err := row.Scan(
		&i.Kind,
		&i.State,
		&i.Detail,
		&i.AttemptedAt,
	)
	return i, err
}

const getOrderLifecycle = `-- name: GetOrderLifecycle :one
SELECT character_id, order_id, type_id, location_id, region_id, is_buy_order, listed_price, volume_total, volume_remain_last, first_seen_at, last_seen_at, closed_at, close_kind, outbid_events, beaten_now
FROM order_lifecycle
WHERE character_id = ? AND order_id = ?
`

type GetOrderLifecycleParams struct {
	CharacterID int64 `json:"character_id"`
	OrderID     int64 `json:"order_id"`
}

// ---------------------------------------------------------------------
// P4 order lifecycle (schema 033): append-only per-order history
// distilled from order snapshots. The worker upserts open orders,
// closes rows whose order has left the snapshot, and prunes old
// closed rows; the Orders page reads only these rows.
// ---------------------------------------------------------------------
func (q *Queries) GetOrderLifecycle(ctx context.Context, arg GetOrderLifecycleParams) (OrderLifecycle, error) {
	row := q.db.QueryRowContext(ctx, getOrderLifecycle, arg.CharacterID, arg.OrderID)
	var i OrderLifecycle
	err := row.Scan(
		&i.CharacterID,
		&i.OrderID,
		&i.TypeID,
		&i.LocationID,
		&i.RegionID,
		&i.IsBuyOrder,
		&i.ListedPrice,
		&i.VolumeTotal,
		&i.VolumeRemainLast,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ClosedAt,
		&i.CloseKind,
		&i.OutbidEvents,
		&i.BeatenNow,
	)
	return i, err
}

const getPilotNameWant = `-- name: GetPilotNameWant :one
SELECT normalized_name, display_name, state, character_id, requested_at, resolved_at, next_try_at, attempts
FROM pilot_name_wants
WHERE normalized_name = ?
`

// Pilot name-resolution wants (schema 022): a topbar search for
// a pilot name no local tier knows notes the name once; the
// worker resolves due rows through ESI's public name lookup.
// 'missing' and 'ready' are settled states; 'error' rows wait
// for next_try_at so a failing lookup is not re-asked per search.
func (q *Queries) GetPilotNameWant(ctx context.Context, normalizedName string) (PilotNameWant, error) {
	row := q.db.QueryRowContext(ctx, getPilotNameWant, normalizedName)
	var i PilotNameWant
	err := row.Scan(
		&i.NormalizedName,
		&i.DisplayName,
		&i.State,
		&i.CharacterID,
		&i.RequestedAt,
		&i.ResolvedAt,
		&i.NextTryAt,
		&i.Attempts,
	)
	return i, err
}

const getPilotRecord = `-- name: GetPilotRecord :one
SELECT character_id, payload, state, fetched_at
FROM pilot_records
WHERE character_id = ?
`

type GetPilotRecordRow struct {
	CharacterID int64  `json:"character_id"`
	Payload     string `json:"payload"`
	State       string `json:"state"`
	FetchedAt   string `json:"fetched_at"`
}

// ---------------------------------------------------------------------
// Public pilot records (schema 015): the queue behind /pilot/.
// Pending rows are always due; ready rows re-check once their
// fetched_at passes the stale cutoff; missing rows (ESI 404)
// settle for good. The item details page enqueues type
// descriptions the same way: a type_details row with an empty
// fetched_at is a want.
// ---------------------------------------------------------------------
func (q *Queries) GetPilotRecord(ctx context.Context, characterID int64) (GetPilotRecordRow, error) {
	row := q.db.QueryRowContext(ctx, getPilotRecord, characterID)
	var i GetPilotRecordRow
	err := row.Scan(
		&i.CharacterID,
		&i.Payload,
		&i.State,
		&i.FetchedAt,
	)
	return i, err
}

const getPlanetName = `-- name: GetPlanetName :one
SELECT planet_id, name, state, resolved_at
FROM planet_names
WHERE planet_id = ?
`

// ---------------------------------------------------------------------
// Planet names (schema 025): queued when a PI surface meets an
// unresolved planet id, resolved in the background through the
// public GET /universe/planets/{id}/ (no token). 'resolved' rows
// re-check after a long window (planet names never change);
// 'missing' rows (404: not a planet) re-check after days;
// 'pending' rows are always due.
// ---------------------------------------------------------------------
func (q *Queries) GetPlanetName(ctx context.Context, planetID int64) (PlanetName, error) {
	row := q.db.QueryRowContext(ctx, getPlanetName, planetID)
	var i PlanetName
	err := row.Scan(
		&i.PlanetID,
		&i.Name,
		&i.State,
		&i.ResolvedAt,
	)
	return i, err
}

const getStructureContext = `-- name: GetStructureContext :one
SELECT structure_id, owner_corporation_id, system_id, type_id, updated_at
FROM structure_context
WHERE structure_id = ?
`

// ---------------------------------------------------------------------
// Structure context (schema 028): owner/system/type facts the
// corporation structure snapshots report, persisted as the
// snapshots are processed so the structure page renders from one
// small row. Latest snapshot wins; names are NOT stored here (they
// live in structure_names under provenance rules).
// ---------------------------------------------------------------------
func (q *Queries) GetStructureContext(ctx context.Context, structureID int64) (StructureContext, error) {
	row := q.db.QueryRowContext(ctx, getStructureContext, structureID)
	var i StructureContext
	err := row.Scan(
		&i.StructureID,
		&i.OwnerCorporationID,
		&i.SystemID,
		&i.TypeID,
		&i.UpdatedAt,
	)
	return i, err
}

const getStructureName = `-- name: GetStructureName :one
SELECT structure_id, name, state, resolved_at, source
FROM structure_names
WHERE structure_id = ?
`

// ---------------------------------------------------------------------
// Player structure names (schema 014): queued when a worker-computed
// view or the market book view meets an unresolved structure id,
// resolved in the background via any linked character holding
// esi-universe.read_structures.v1 (the lookup endpoint is
// authenticated-only). 'resolved' rows re-check after 30 days
// (structures can be renamed); 'missing' rows (403/404: private or
// gone) re-check after 24 hours; 'pending' rows are always due.
// The worker tries every eligible linked character before a
// negative answer is cached, and 'source' (schema 023) records the
// name's provenance so ESI truth outranks any lower-trust tier.
// ---------------------------------------------------------------------
func (q *Queries) GetStructureName(ctx context.Context, structureID int64) (StructureName, error) {
	row := q.db.QueryRowContext(ctx, getStructureName, structureID)
	var i StructureName
	err := row.Scan(
		&i.StructureID,
		&i.Name,
		&i.State,
		&i.ResolvedAt,
		&i.Source,
	)
	return i, err
}

const getWatchlistEntry = `-- name: GetWatchlistEntry :one
SELECT user_id, type_id, region_id, threshold_pct, created_at
FROM market_watchlist
WHERE user_id = ? AND type_id = ? AND region_id = ?
`

type GetWatchlistEntryParams struct {
	UserID   int64 `json:"user_id"`
	TypeID   int64 `json:"type_id"`
	RegionID int64 `json:"region_id"`
}

func (q *Queries) GetWatchlistEntry(ctx context.Context, arg GetWatchlistEntryParams) (MarketWatchlist, error) {
	row := q.db.QueryRowContext(ctx, getWatchlistEntry, arg.UserID, arg.TypeID, arg.RegionID)
	var i MarketWatchlist
	err := row.Scan(
		&i.UserID,
		&i.TypeID,
		&i.RegionID,
		&i.ThresholdPct,
		&i.CreatedAt,
	)
	return i, err
}

const insertPilotOrbitWant = `-- name: InsertPilotOrbitWant :exec
INSERT OR IGNORE INTO pilot_records (character_id, priority)
VALUES (?, 0)
`

func (q *Queries) InsertPilotOrbitWant(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, insertPilotOrbitWant, characterID)
	return err
}

const listAllWatchlistEntries = `-- name: ListAllWatchlistEntries :many
SELECT user_id, type_id, region_id, threshold_pct, created_at
FROM market_watchlist
ORDER BY type_id, region_id
`

func (q *Queries) ListAllWatchlistEntries(ctx context.Context) ([]MarketWatchlist, error) {
	rows, err := q.db.QueryContext(ctx, listAllWatchlistEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketWatchlist
	for rows.Next() {
		var i MarketWatchlist
		if err := rows.Scan(
			&i.UserID,
			&i.TypeID,
			&i.RegionID,
			&i.ThresholdPct,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllianceDrains = `-- name: ListAllianceDrains :many
SELECT alliance_id
FROM alliance_records
WHERE state = 'pending'
   OR (state = 'ready' AND fetched_at < ?1)
ORDER BY CASE state WHEN 'pending' THEN 0 ELSE 1 END, priority DESC, fetched_at
LIMIT ?2
`

type ListAllianceDrainsParams struct {
	StaleCutoff string `json:"stale_cutoff"`
	DrainLimit  int64  `json:"drain_limit"`
}

func (q *Queries) ListAllianceDrains(ctx context.Context, arg ListAllianceDrainsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listAllianceDrains, arg.StaleCutoff, arg.DrainLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var alliance_id int64
		if err := rows.Scan(&alliance_id); err != nil {
			return nil, err
		}
		items = append(items, alliance_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClosedOrderLifecycleByCharacter = `-- name: ListClosedOrderLifecycleByCharacter :many
SELECT character_id, order_id, type_id, location_id, region_id, is_buy_order, listed_price, volume_total, volume_remain_last, first_seen_at, last_seen_at, closed_at, close_kind, outbid_events, beaten_now
FROM order_lifecycle
WHERE character_id = ? AND closed_at != ''
ORDER BY closed_at DESC, order_id DESC
LIMIT ?
`

type ListClosedOrderLifecycleByCharacterParams struct {
	CharacterID int64 `json:"character_id"`
	Limit       int64 `json:"limit"`
}

func (q *Queries) ListClosedOrderLifecycleByCharacter(ctx context.Context, arg ListClosedOrderLifecycleByCharacterParams) ([]OrderLifecycle, error) {
	rows, err := q.db.QueryContext(ctx, listClosedOrderLifecycleByCharacter, arg.CharacterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderLifecycle
	for rows.Next() {
		var i OrderLifecycle
		if err := rows.Scan(
			&i.CharacterID,
			&i.OrderID,
			&i.TypeID,
			&i.LocationID,
			&i.RegionID,
			&i.IsBuyOrder,
			&i.ListedPrice,
			&i.VolumeTotal,
			&i.VolumeRemainLast,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ClosedAt,
			&i.CloseKind,
			&i.OutbidEvents,
			&i.BeatenNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCorporationDrains = `-- name: ListCorporationDrains :many
SELECT corporation_id
FROM corporation_records
WHERE state = 'pending'
   OR (state = 'ready' AND fetched_at < ?1)
ORDER BY CASE state WHEN 'pending' THEN 0 ELSE 1 END, priority DESC, fetched_at
LIMIT ?2
`

type ListCorporationDrainsParams struct {
	StaleCutoff string `json:"stale_cutoff"`
	DrainLimit  int64  `json:"drain_limit"`
}

func (q *Queries) ListCorporationDrains(ctx context.Context, arg ListCorporationDrainsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listCorporationDrains, arg.StaleCutoff, arg.DrainLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var corporation_id int64
		if err := rows.Scan(&corporation_id); err != nil {
			return nil, err
		}
		items = append(items, corporation_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuePilotNameWants = `-- name: ListDuePilotNameWants :many
SELECT normalized_name, display_name, state, character_id, requested_at, resolved_at, next_try_at, attempts
FROM pilot_name_wants
WHERE (state = 'pending' OR state = 'error')
  AND (next_try_at = '' OR next_try_at <= ?1)
ORDER BY requested_at
LIMIT ?2
`

type ListDuePilotNameWantsParams struct {
	Now string `json:"now"`
	Lim int64  `json:"lim"`
}

func (q *Queries) ListDuePilotNameWants(ctx context.Context, arg ListDuePilotNameWantsParams) ([]PilotNameWant, error) {
	rows, err := q.db.QueryContext(ctx, listDuePilotNameWants, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PilotNameWant
	for rows.Next() {
		var i PilotNameWant
		if err := rows.Scan(
			&i.NormalizedName,
			&i.DisplayName,
			&i.State,
			&i.CharacterID,
			&i.RequestedAt,
			&i.ResolvedAt,
			&i.NextTryAt,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuidePrices = `-- name: ListGuidePrices :many
SELECT type_id, adjusted_price, average_price FROM guide_prices
ORDER BY type_id
`

func (q *Queries) ListGuidePrices(ctx context.Context) ([]GuidePrice, error) {
	rows, err := q.db.QueryContext(ctx, listGuidePrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuidePrice
	for rows.Next() {
		var i GuidePrice
		if err := rows.Scan(&i.TypeID, &i.AdjustedPrice, &i.AveragePrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketHistory = `-- name: ListMarketHistory :many
SELECT region_id, type_id, date, average, highest, lowest, volume, order_count
FROM market_history
WHERE region_id = ? AND type_id = ?
ORDER BY date DESC
LIMIT ?
`

type ListMarketHistoryParams struct {
	RegionID int64 `json:"region_id"`
	TypeID   int64 `json:"type_id"`
	Limit    int64 `json:"limit"`
}

// The history window is a row count, not a calendar span: the
// chart and change math read the newest N rows of recorded
// trades, newest first, so a sparse item's stored trades are
// never hidden by an arbitrary date cutoff.
func (q *Queries) ListMarketHistory(ctx context.Context, arg ListMarketHistoryParams) ([]MarketHistory, error) {
	rows, err := q.db.QueryContext(ctx, listMarketHistory, arg.RegionID, arg.TypeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketHistory
	for rows.Next() {
		var i MarketHistory
		if err := rows.Scan(
			&i.RegionID,
			&i.TypeID,
			&i.Date,
			&i.Average,
			&i.Highest,
			&i.Lowest,
			&i.Volume,
			&i.OrderCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketHistoryWants = `-- name: ListMarketHistoryWants :many
SELECT region_id, type_id, last_requested_at
FROM market_history_wants
WHERE last_requested_at >= ?
ORDER BY region_id, type_id
`

func (q *Queries) ListMarketHistoryWants(ctx context.Context, lastRequestedAt string) ([]MarketHistoryWant, error) {
	rows, err := q.db.QueryContext(ctx, listMarketHistoryWants, lastRequestedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketHistoryWant
	for rows.Next() {
		var i MarketHistoryWant
		if err := rows.Scan(&i.RegionID, &i.TypeID, &i.LastRequestedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketRegionStatsByRegion = `-- name: ListMarketRegionStatsByRegion :many
SELECT region_id, type_id, best_sell, typical_sell, sell_band, best_buy, typical_buy, buy_band, sell_orders, buy_orders, sell_volume, buy_volume, updated_at
FROM market_region_stats
WHERE region_id = ?
ORDER BY type_id
`

func (q *Queries) ListMarketRegionStatsByRegion(ctx context.Context, regionID int64) ([]MarketRegionStat, error) {
	rows, err := q.db.QueryContext(ctx, listMarketRegionStatsByRegion, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketRegionStat
	for rows.Next() {
		var i MarketRegionStat
		if err := rows.Scan(
			&i.RegionID,
			&i.TypeID,
			&i.BestSell,
			&i.TypicalSell,
			&i.SellBand,
			&i.BestBuy,
			&i.TypicalBuy,
			&i.BuyBand,
			&i.SellOrders,
			&i.BuyOrders,
			&i.SellVolume,
			&i.BuyVolume,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketRegionStatsByType = `-- name: ListMarketRegionStatsByType :many
SELECT region_id, type_id, best_sell, typical_sell, sell_band, best_buy, typical_buy, buy_band, sell_orders, buy_orders, sell_volume, buy_volume, updated_at
FROM market_region_stats
WHERE type_id = ?
ORDER BY region_id
`

func (q *Queries) ListMarketRegionStatsByType(ctx context.Context, typeID int64) ([]MarketRegionStat, error) {
	rows, err := q.db.QueryContext(ctx, listMarketRegionStatsByType, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketRegionStat
	for rows.Next() {
		var i MarketRegionStat
		if err := rows.Scan(
			&i.RegionID,
			&i.TypeID,
			&i.BestSell,
			&i.TypicalSell,
			&i.SellBand,
			&i.BestBuy,
			&i.TypicalBuy,
			&i.BuyBand,
			&i.SellOrders,
			&i.BuyOrders,
			&i.SellVolume,
			&i.BuyVolume,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketRegionStatsDaily = `-- name: ListMarketRegionStatsDaily :many
SELECT region_id, type_id, day, best_sell, typical_sell, sell_band, best_buy, typical_buy, buy_band, sell_orders, buy_orders, sell_volume, buy_volume
FROM market_region_stats_daily
WHERE region_id = ? AND type_id = ?
ORDER BY day
`

type ListMarketRegionStatsDailyParams struct {
	RegionID int64 `json:"region_id"`
	TypeID   int64 `json:"type_id"`
}

func (q *Queries) ListMarketRegionStatsDaily(ctx context.Context, arg ListMarketRegionStatsDailyParams) ([]MarketRegionStatsDaily, error) {
	rows, err := q.db.QueryContext(ctx, listMarketRegionStatsDaily, arg.RegionID, arg.TypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketRegionStatsDaily
	for rows.Next() {
		var i MarketRegionStatsDaily
		if err := rows.Scan(
			&i.RegionID,
			&i.TypeID,
			&i.Day,
			&i.BestSell,
			&i.TypicalSell,
			&i.SellBand,
			&i.BestBuy,
			&i.TypicalBuy,
			&i.BuyBand,
			&i.SellOrders,
			&i.BuyOrders,
			&i.SellVolume,
			&i.BuyVolume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketStationStatsByRegion = `-- name: ListMarketStationStatsByRegion :many
SELECT location_id, region_id, type_id, best_sell, best_buy, sell_orders, buy_orders, sell_volume, buy_volume, updated_at
FROM market_station_stats
WHERE region_id = ?
ORDER BY location_id, type_id
`

func (q *Queries) ListMarketStationStatsByRegion(ctx context.Context, regionID int64) ([]MarketStationStat, error) {
	rows, err := q.db.QueryContext(ctx, listMarketStationStatsByRegion, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketStationStat
	for rows.Next() {
		var i MarketStationStat
		if err := rows.Scan(
			&i.LocationID,
			&i.RegionID,
			&i.TypeID,
			&i.BestSell,
			&i.BestBuy,
			&i.SellOrders,
			&i.BuyOrders,
			&i.SellVolume,
			&i.BuyVolume,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenOrderLifecycleByCharacter = `-- name: ListOpenOrderLifecycleByCharacter :many
SELECT character_id, order_id, type_id, location_id, region_id, is_buy_order, listed_price, volume_total, volume_remain_last, first_seen_at, last_seen_at, closed_at, close_kind, outbid_events, beaten_now
FROM order_lifecycle
WHERE character_id = ? AND closed_at = ''
ORDER BY order_id
`

func (q *Queries) ListOpenOrderLifecycleByCharacter(ctx context.Context, characterID int64) ([]OrderLifecycle, error) {
	rows, err := q.db.QueryContext(ctx, listOpenOrderLifecycleByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderLifecycle
	for rows.Next() {
		var i OrderLifecycle
		if err := rows.Scan(
			&i.CharacterID,
			&i.OrderID,
			&i.TypeID,
			&i.LocationID,
			&i.RegionID,
			&i.IsBuyOrder,
			&i.ListedPrice,
			&i.VolumeTotal,
			&i.VolumeRemainLast,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ClosedAt,
			&i.CloseKind,
			&i.OutbidEvents,
			&i.BeatenNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderHealthByCharacter = `-- name: ListOrderHealthByCharacter :many
SELECT character_id, order_id, type_id, region_id, location_id, my_price, station_best, region_best, status, computed_at
FROM order_health
WHERE character_id = ?
ORDER BY type_id, order_id
`

func (q *Queries) ListOrderHealthByCharacter(ctx context.Context, characterID int64) ([]OrderHealth, error) {
	rows, err := q.db.QueryContext(ctx, listOrderHealthByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderHealth
	for rows.Next() {
		var i OrderHealth
		if err := rows.Scan(
			&i.CharacterID,
			&i.OrderID,
			&i.TypeID,
			&i.RegionID,
			&i.LocationID,
			&i.MyPrice,
			&i.StationBest,
			&i.RegionBest,
			&i.Status,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderHealthByUser = `-- name: ListOrderHealthByUser :many
SELECT oh.character_id, oh.order_id, oh.type_id, oh.region_id, oh.location_id, oh.my_price, oh.station_best, oh.region_best, oh.status, oh.computed_at
FROM order_health oh
JOIN characters c ON c.character_id = oh.character_id
WHERE c.user_id = ?
ORDER BY c.name, oh.type_id, oh.order_id
`

func (q *Queries) ListOrderHealthByUser(ctx context.Context, userID int64) ([]OrderHealth, error) {
	rows, err := q.db.QueryContext(ctx, listOrderHealthByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderHealth
	for rows.Next() {
		var i OrderHealth
		if err := rows.Scan(
			&i.CharacterID,
			&i.OrderID,
			&i.TypeID,
			&i.RegionID,
			&i.LocationID,
			&i.MyPrice,
			&i.StationBest,
			&i.RegionBest,
			&i.Status,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderLifecycleByCharacter = `-- name: ListOrderLifecycleByCharacter :many
SELECT character_id, order_id, type_id, location_id, region_id, is_buy_order, listed_price, volume_total, volume_remain_last, first_seen_at, last_seen_at, closed_at, close_kind, outbid_events, beaten_now
FROM order_lifecycle
WHERE character_id = ?
ORDER BY first_seen_at DESC, order_id DESC
`

func (q *Queries) ListOrderLifecycleByCharacter(ctx context.Context, characterID int64) ([]OrderLifecycle, error) {
	rows, err := q.db.QueryContext(ctx, listOrderLifecycleByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderLifecycle
	for rows.Next() {
		var i OrderLifecycle
		if err := rows.Scan(
			&i.CharacterID,
			&i.OrderID,
			&i.TypeID,
			&i.LocationID,
			&i.RegionID,
			&i.IsBuyOrder,
			&i.ListedPrice,
			&i.VolumeTotal,
			&i.VolumeRemainLast,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ClosedAt,
			&i.CloseKind,
			&i.OutbidEvents,
			&i.BeatenNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderLifecycleByUser = `-- name: ListOrderLifecycleByUser :many
SELECT ol.character_id, ol.order_id, ol.type_id, ol.location_id, ol.region_id, ol.is_buy_order, ol.listed_price, ol.volume_total, ol.volume_remain_last, ol.first_seen_at, ol.last_seen_at, ol.closed_at, ol.close_kind, ol.outbid_events, ol.beaten_now
FROM order_lifecycle ol
JOIN characters c ON c.character_id = ol.character_id
WHERE c.user_id = ?
ORDER BY ol.closed_at DESC, ol.first_seen_at DESC, ol.order_id DESC
`

func (q *Queries) ListOrderLifecycleByUser(ctx context.Context, userID int64) ([]OrderLifecycle, error) {
	rows, err := q.db.QueryContext(ctx, listOrderLifecycleByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderLifecycle
	for rows.Next() {
		var i OrderLifecycle
		if err := rows.Scan(
			&i.CharacterID,
			&i.OrderID,
			&i.TypeID,
			&i.LocationID,
			&i.RegionID,
			&i.IsBuyOrder,
			&i.ListedPrice,
			&i.VolumeTotal,
			&i.VolumeRemainLast,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ClosedAt,
			&i.CloseKind,
			&i.OutbidEvents,
			&i.BeatenNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPilotDrains = `-- name: ListPilotDrains :many
SELECT character_id
FROM pilot_records
WHERE state = 'pending'
   OR (state = 'ready' AND fetched_at < ?1)
ORDER BY CASE state WHEN 'pending' THEN 0 ELSE 1 END, priority DESC, fetched_at
LIMIT ?2
`

type ListPilotDrainsParams struct {
	StaleCutoff string `json:"stale_cutoff"`
	DrainLimit  int64  `json:"drain_limit"`
}

func (q *Queries) ListPilotDrains(ctx context.Context, arg ListPilotDrainsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPilotDrains, arg.StaleCutoff, arg.DrainLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var character_id int64
		if err := rows.Scan(&character_id); err != nil {
			return nil, err
		}
		items = append(items, character_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPilotRecordIDs = `-- name: ListPilotRecordIDs :many
SELECT character_id
FROM pilot_records
`

func (q *Queries) ListPilotRecordIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPilotRecordIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var character_id int64
		if err := rows.Scan(&character_id); err != nil {
			return nil, err
		}
		items = append(items, character_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanetResolutions = `-- name: ListPlanetResolutions :many
SELECT planet_id
FROM planet_names
WHERE state = 'pending'
   OR (state = 'resolved' AND resolved_at < ?1)
   OR (state = 'missing' AND resolved_at < ?2)
ORDER BY CASE state WHEN 'pending' THEN 0 ELSE 1 END, planet_id
LIMIT ?3
`

type ListPlanetResolutionsParams struct {
	ResolvedCutoff  string `json:"resolved_cutoff"`
	MissingCutoff   string `json:"missing_cutoff"`
	ResolutionLimit int64  `json:"resolution_limit"`
}

func (q *Queries) ListPlanetResolutions(ctx context.Context, arg ListPlanetResolutionsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPlanetResolutions, arg.ResolvedCutoff, arg.MissingCutoff, arg.ResolutionLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var planet_id int64
		if err := rows.Scan(&planet_id); err != nil {
			return nil, err
		}
		items = append(items, planet_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStructureResolutions = `-- name: ListStructureResolutions :many
SELECT structure_id
FROM structure_names
WHERE state = 'pending'
   OR (state = 'resolved' AND resolved_at < ?1)
   OR (state = 'missing' AND resolved_at < ?2)
ORDER BY CASE state WHEN 'pending' THEN 0 ELSE 1 END, structure_id
LIMIT ?3
`

type ListStructureResolutionsParams struct {
	ResolvedCutoff  string `json:"resolved_cutoff"`
	MissingCutoff   string `json:"missing_cutoff"`
	ResolutionLimit int64  `json:"resolution_limit"`
}

func (q *Queries) ListStructureResolutions(ctx context.Context, arg ListStructureResolutionsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listStructureResolutions, arg.ResolvedCutoff, arg.MissingCutoff, arg.ResolutionLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var structure_id int64
		if err := rows.Scan(&structure_id); err != nil {
			return nil, err
		}
		items = append(items, structure_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchlistByUser = `-- name: ListWatchlistByUser :many
SELECT user_id, type_id, region_id, threshold_pct, created_at
FROM market_watchlist
WHERE user_id = ?
ORDER BY type_id, region_id
`

func (q *Queries) ListWatchlistByUser(ctx context.Context, userID int64) ([]MarketWatchlist, error) {
	rows, err := q.db.QueryContext(ctx, listWatchlistByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketWatchlist
	for rows.Next() {
		var i MarketWatchlist
		if err := rows.Scan(
			&i.UserID,
			&i.TypeID,
			&i.RegionID,
			&i.ThresholdPct,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const noteGuidePriceWant = `-- name: NoteGuidePriceWant :exec
INSERT INTO guide_price_wants (id, wanted_at)
VALUES (1, ?)
ON CONFLICT (id) DO UPDATE SET
    wanted_at = excluded.wanted_at
`

// ---------------------------------------------------------------------
// v0.3.14 guide-price wants (schema 027): the durable note a
// kill view leaves when it has no prices to value with. One
// singleton row -- the guide is global, so one want covers every
// viewer -- noted at render time, answered by the worker's
// urgent drain with a guide refresh when ESI's window allows.
// ---------------------------------------------------------------------
func (q *Queries) NoteGuidePriceWant(ctx context.Context, wantedAt string) error {
	_, err := q.db.ExecContext(ctx, noteGuidePriceWant, wantedAt)
	return err
}

const pruneOldOrderLifecycle = `-- name: PruneOldOrderLifecycle :exec
DELETE FROM order_lifecycle
WHERE rowid IN (
    SELECT ol.rowid FROM order_lifecycle AS ol
    WHERE ol.closed_at != '' AND ol.closed_at < ?
    ORDER BY ol.closed_at
    LIMIT ?
)
`

type PruneOldOrderLifecycleParams struct {
	ClosedAt string `json:"closed_at"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) PruneOldOrderLifecycle(ctx context.Context, arg PruneOldOrderLifecycleParams) error {
	_, err := q.db.ExecContext(ctx, pruneOldOrderLifecycle, arg.ClosedAt, arg.Limit)
	return err
}

const setAllianceRecord = `-- name: SetAllianceRecord :exec
INSERT INTO alliance_records (alliance_id, payload, state, fetched_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (alliance_id) DO UPDATE SET
    payload    = excluded.payload,
    state      = excluded.state,
    fetched_at = excluded.fetched_at
`

type SetAllianceRecordParams struct {
	AllianceID int64  `json:"alliance_id"`
	Payload    string `json:"payload"`
	State      string `json:"state"`
	FetchedAt  string `json:"fetched_at"`
}

func (q *Queries) SetAllianceRecord(ctx context.Context, arg SetAllianceRecordParams) error {
	_, err := q.db.ExecContext(ctx, setAllianceRecord,
		arg.AllianceID,
		arg.Payload,
		arg.State,
		arg.FetchedAt,
	)
	return err
}

const setCorporationRecord = `-- name: SetCorporationRecord :exec
INSERT INTO corporation_records (corporation_id, payload, state, fetched_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (corporation_id) DO UPDATE SET
    payload    = excluded.payload,
    state      = excluded.state,
    fetched_at = excluded.fetched_at
`

type SetCorporationRecordParams struct {
	CorporationID int64  `json:"corporation_id"`
	Payload       string `json:"payload"`
	State         string `json:"state"`
	FetchedAt     string `json:"fetched_at"`
}

func (q *Queries) SetCorporationRecord(ctx context.Context, arg SetCorporationRecordParams) error {
	_, err := q.db.ExecContext(ctx, setCorporationRecord,
		arg.CorporationID,
		arg.Payload,
		arg.State,
		arg.FetchedAt,
	)
	return err
}

const setPilotNameWantError = `-- name: SetPilotNameWantError :exec
UPDATE pilot_name_wants
SET state = 'error', attempts = attempts + 1, resolved_at = ?, next_try_at = ?
WHERE normalized_name = ?
`

type SetPilotNameWantErrorParams struct {
	ResolvedAt     string `json:"resolved_at"`
	NextTryAt      string `json:"next_try_at"`
	NormalizedName string `json:"normalized_name"`
}

func (q *Queries) SetPilotNameWantError(ctx context.Context, arg SetPilotNameWantErrorParams) error {
	_, err := q.db.ExecContext(ctx, setPilotNameWantError, arg.ResolvedAt, arg.NextTryAt, arg.NormalizedName)
	return err
}

const setPilotNameWantMissing = `-- name: SetPilotNameWantMissing :exec
UPDATE pilot_name_wants
SET state = 'missing', resolved_at = ?, next_try_at = ''
WHERE normalized_name = ?
`

type SetPilotNameWantMissingParams struct {
	ResolvedAt     string `json:"resolved_at"`
	NormalizedName string `json:"normalized_name"`
}

func (q *Queries) SetPilotNameWantMissing(ctx context.Context, arg SetPilotNameWantMissingParams) error {
	_, err := q.db.ExecContext(ctx, setPilotNameWantMissing, arg.ResolvedAt, arg.NormalizedName)
	return err
}

const setPilotNameWantReady = `-- name: SetPilotNameWantReady :exec
UPDATE pilot_name_wants
SET state = 'ready', character_id = ?, resolved_at = ?, next_try_at = ''
WHERE normalized_name = ?
`

type SetPilotNameWantReadyParams struct {
	CharacterID    int64  `json:"character_id"`
	ResolvedAt     string `json:"resolved_at"`
	NormalizedName string `json:"normalized_name"`
}

func (q *Queries) SetPilotNameWantReady(ctx context.Context, arg SetPilotNameWantReadyParams) error {
	_, err := q.db.ExecContext(ctx, setPilotNameWantReady, arg.CharacterID, arg.ResolvedAt, arg.NormalizedName)
	return err
}

const setPilotRecord = `-- name: SetPilotRecord :exec
INSERT INTO pilot_records (character_id, payload, state, fetched_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (character_id) DO UPDATE SET
    payload    = excluded.payload,
    state      = excluded.state,
    fetched_at = excluded.fetched_at
`

type SetPilotRecordParams struct {
	CharacterID int64  `json:"character_id"`
	Payload     string `json:"payload"`
	State       string `json:"state"`
	FetchedAt   string `json:"fetched_at"`
}

func (q *Queries) SetPilotRecord(ctx context.Context, arg SetPilotRecordParams) error {
	_, err := q.db.ExecContext(ctx, setPilotRecord,
		arg.CharacterID,
		arg.Payload,
		arg.State,
		arg.FetchedAt,
	)
	return err
}

const setPlanetName = `-- name: SetPlanetName :exec
INSERT INTO planet_names (planet_id, name, state, resolved_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (planet_id) DO UPDATE SET
    name        = excluded.name,
    state       = excluded.state,
    resolved_at = excluded.resolved_at
`

type SetPlanetNameParams struct {
	PlanetID   int64  `json:"planet_id"`
	Name       string `json:"name"`
	State      string `json:"state"`
	ResolvedAt string `json:"resolved_at"`
}

func (q *Queries) SetPlanetName(ctx context.Context, arg SetPlanetNameParams) error {
	_, err := q.db.ExecContext(ctx, setPlanetName,
		arg.PlanetID,
		arg.Name,
		arg.State,
		arg.ResolvedAt,
	)
	return err
}

const setStructureContext = `-- name: SetStructureContext :exec
INSERT INTO structure_context (structure_id, owner_corporation_id, system_id, type_id, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (structure_id) DO UPDATE SET
    owner_corporation_id = excluded.owner_corporation_id,
    system_id            = excluded.system_id,
    type_id              = excluded.type_id,
    updated_at           = excluded.updated_at
`

type SetStructureContextParams struct {
	StructureID        int64  `json:"structure_id"`
	OwnerCorporationID int64  `json:"owner_corporation_id"`
	SystemID           int64  `json:"system_id"`
	TypeID             int64  `json:"type_id"`
	UpdatedAt          string `json:"updated_at"`
}

func (q *Queries) SetStructureContext(ctx context.Context, arg SetStructureContextParams) error {
	_, err := q.db.ExecContext(ctx, setStructureContext,
		arg.StructureID,
		arg.OwnerCorporationID,
		arg.SystemID,
		arg.TypeID,
		arg.UpdatedAt,
	)
	return err
}

const setStructureName = `-- name: SetStructureName :exec
INSERT INTO structure_names (structure_id, name, state, resolved_at, source)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (structure_id) DO UPDATE SET
    name        = excluded.name,
    state       = excluded.state,
    resolved_at = excluded.resolved_at,
    source      = excluded.source
`

type SetStructureNameParams struct {
	StructureID int64  `json:"structure_id"`
	Name        string `json:"name"`
	State       string `json:"state"`
	ResolvedAt  string `json:"resolved_at"`
	Source      string `json:"source"`
}

func (q *Queries) SetStructureName(ctx context.Context, arg SetStructureNameParams) error {
	_, err := q.db.ExecContext(ctx, setStructureName,
		arg.StructureID,
		arg.Name,
		arg.State,
		arg.ResolvedAt,
		arg.Source,
	)
	return err
}

const updateOrderLifecycleBeaten = `-- name: UpdateOrderLifecycleBeaten :exec
UPDATE order_lifecycle
SET beaten_now = ?, outbid_events = ?
WHERE character_id = ? AND order_id = ? AND closed_at = ''
`

type UpdateOrderLifecycleBeatenParams struct {
	BeatenNow    int64 `json:"beaten_now"`
	OutbidEvents int64 `json:"outbid_events"`
	CharacterID  int64 `json:"character_id"`
	OrderID      int64 `json:"order_id"`
}

func (q *Queries) UpdateOrderLifecycleBeaten(ctx context.Context, arg UpdateOrderLifecycleBeatenParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderLifecycleBeaten,
		arg.BeatenNow,
		arg.OutbidEvents,
		arg.CharacterID,
		arg.OrderID,
	)
	return err
}

const upsertAllianceWant = `-- name: UpsertAllianceWant :exec
INSERT INTO alliance_records (alliance_id, priority)
VALUES (?, 1)
ON CONFLICT (alliance_id) DO UPDATE SET priority = MAX(priority, 1)
`

func (q *Queries) UpsertAllianceWant(ctx context.Context, allianceID int64) error {
	_, err := q.db.ExecContext(ctx, upsertAllianceWant, allianceID)
	return err
}

const upsertCorporationWant = `-- name: UpsertCorporationWant :exec
INSERT INTO corporation_records (corporation_id, priority)
VALUES (?, 1)
ON CONFLICT (corporation_id) DO UPDATE SET priority = MAX(priority, 1)
`

func (q *Queries) UpsertCorporationWant(ctx context.Context, corporationID int64) error {
	_, err := q.db.ExecContext(ctx, upsertCorporationWant, corporationID)
	return err
}

const upsertGuidePrice = `-- name: UpsertGuidePrice :exec
INSERT INTO guide_prices (type_id, adjusted_price, average_price)
VALUES (?, ?, ?)
ON CONFLICT (type_id) DO UPDATE SET
    adjusted_price = excluded.adjusted_price,
    average_price  = excluded.average_price
`

type UpsertGuidePriceParams struct {
	TypeID        int64   `json:"type_id"`
	AdjustedPrice float64 `json:"adjusted_price"`
	AveragePrice  float64 `json:"average_price"`
}

func (q *Queries) UpsertGuidePrice(ctx context.Context, arg UpsertGuidePriceParams) error {
	_, err := q.db.ExecContext(ctx, upsertGuidePrice, arg.TypeID, arg.AdjustedPrice, arg.AveragePrice)
	return err
}

const upsertGuidePricesMeta = `-- name: UpsertGuidePricesMeta :exec
INSERT INTO guide_prices_meta (id, fetched_at, cached_until)
VALUES (1, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    fetched_at   = excluded.fetched_at,
    cached_until = excluded.cached_until
`

type UpsertGuidePricesMetaParams struct {
	FetchedAt   string `json:"fetched_at"`
	CachedUntil string `json:"cached_until"`
}

func (q *Queries) UpsertGuidePricesMeta(ctx context.Context, arg UpsertGuidePricesMetaParams) error {
	_, err := q.db.ExecContext(ctx, upsertGuidePricesMeta, arg.FetchedAt, arg.CachedUntil)
	return err
}

const upsertMarketFetchState = `-- name: UpsertMarketFetchState :exec
INSERT INTO market_fetch_state (kind, state, detail, attempted_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (kind) DO UPDATE SET
    state        = excluded.state,
    detail       = excluded.detail,
    attempted_at = excluded.attempted_at
`

type UpsertMarketFetchStateParams struct {
	Kind        string `json:"kind"`
	State       string `json:"state"`
	Detail      string `json:"detail"`
	AttemptedAt string `json:"attempted_at"`
}

func (q *Queries) UpsertMarketFetchState(ctx context.Context, arg UpsertMarketFetchStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketFetchState,
		arg.Kind,
		arg.State,
		arg.Detail,
		arg.AttemptedAt,
	)
	return err
}

const upsertMarketHistory = `-- name: UpsertMarketHistory :exec
INSERT OR REPLACE INTO market_history (region_id, type_id, date, average, highest, lowest, volume, order_count)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type UpsertMarketHistoryParams struct {
	RegionID   int64   `json:"region_id"`
	TypeID     int64   `json:"type_id"`
	Date       string  `json:"date"`
	Average    float64 `json:"average"`
	Highest    float64 `json:"highest"`
	Lowest     float64 `json:"lowest"`
	Volume     int64   `json:"volume"`
	OrderCount int64   `json:"order_count"`
}

// ---------------------------------------------------------------------
// Phase 3 (schema 011): industry build planner reads. Bulk import
// inserts stay hand-rolled in the SDE importer alongside the other
// sde_* tables; only reads live here.
// ---------------------------------------------------------------------
func (q *Queries) UpsertMarketHistory(ctx context.Context, arg UpsertMarketHistoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketHistory,
		arg.RegionID,
		arg.TypeID,
		arg.Date,
		arg.Average,
		arg.Highest,
		arg.Lowest,
		arg.Volume,
		arg.OrderCount,
	)
	return err
}

const upsertMarketHistoryWant = `-- name: UpsertMarketHistoryWant :exec
INSERT INTO market_history_wants (region_id, type_id, last_requested_at)
VALUES (?, ?, ?)
ON CONFLICT (region_id, type_id) DO UPDATE SET
    last_requested_at = excluded.last_requested_at
`

type UpsertMarketHistoryWantParams struct {
	RegionID        int64  `json:"region_id"`
	TypeID          int64  `json:"type_id"`
	LastRequestedAt string `json:"last_requested_at"`
}

func (q *Queries) UpsertMarketHistoryWant(ctx context.Context, arg UpsertMarketHistoryWantParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketHistoryWant, arg.RegionID, arg.TypeID, arg.LastRequestedAt)
	return err
}

const upsertMarketRegionStat = `-- name: UpsertMarketRegionStat :exec
INSERT INTO market_region_stats (region_id, type_id, best_sell, typical_sell, sell_band, best_buy, typical_buy, buy_band, sell_orders, buy_orders, sell_volume, buy_volume, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (region_id, type_id) DO UPDATE SET
    best_sell    = excluded.best_sell,
    typical_sell = excluded.typical_sell,
    sell_band    = excluded.sell_band,
    best_buy     = excluded.best_buy,
    typical_buy  = excluded.typical_buy,
    buy_band     = excluded.buy_band,
    sell_orders  = excluded.sell_orders,
    buy_orders   = excluded.buy_orders,
    sell_volume  = excluded.sell_volume,
    buy_volume   = excluded.buy_volume,
    updated_at   = excluded.updated_at
`

type UpsertMarketRegionStatParams struct {
	RegionID    int64   `json:"region_id"`
	TypeID      int64   `json:"type_id"`
	BestSell    float64 `json:"best_sell"`
	TypicalSell float64 `json:"typical_sell"`
	SellBand    float64 `json:"sell_band"`
	BestBuy     float64 `json:"best_buy"`
	TypicalBuy  float64 `json:"typical_buy"`
	BuyBand     float64 `json:"buy_band"`
	SellOrders  int64   `json:"sell_orders"`
	BuyOrders   int64   `json:"buy_orders"`
	SellVolume  int64   `json:"sell_volume"`
	BuyVolume   int64   `json:"buy_volume"`
	UpdatedAt   string  `json:"updated_at"`
}

func (q *Queries) UpsertMarketRegionStat(ctx context.Context, arg UpsertMarketRegionStatParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketRegionStat,
		arg.RegionID,
		arg.TypeID,
		arg.BestSell,
		arg.TypicalSell,
		arg.SellBand,
		arg.BestBuy,
		arg.TypicalBuy,
		arg.BuyBand,
		arg.SellOrders,
		arg.BuyOrders,
		arg.SellVolume,
		arg.BuyVolume,
		arg.UpdatedAt,
	)
	return err
}

const upsertMarketRegionStatDaily = `-- name: UpsertMarketRegionStatDaily :exec
INSERT INTO market_region_stats_daily (region_id, type_id, day, best_sell, typical_sell, sell_band, best_buy, typical_buy, buy_band, sell_orders, buy_orders, sell_volume, buy_volume)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (region_id, type_id, day) DO UPDATE SET
    best_sell    = excluded.best_sell,
    typical_sell = excluded.typical_sell,
    sell_band    = excluded.sell_band,
    best_buy     = excluded.best_buy,
    typical_buy  = excluded.typical_buy,
    buy_band     = excluded.buy_band,
    sell_orders  = excluded.sell_orders,
    buy_orders   = excluded.buy_orders,
    sell_volume  = excluded.sell_volume,
    buy_volume   = excluded.buy_volume
`

type UpsertMarketRegionStatDailyParams struct {
	RegionID    int64   `json:"region_id"`
	TypeID      int64   `json:"type_id"`
	Day         string  `json:"day"`
	BestSell    float64 `json:"best_sell"`
	TypicalSell float64 `json:"typical_sell"`
	SellBand    float64 `json:"sell_band"`
	BestBuy     float64 `json:"best_buy"`
	TypicalBuy  float64 `json:"typical_buy"`
	BuyBand     float64 `json:"buy_band"`
	SellOrders  int64   `json:"sell_orders"`
	BuyOrders   int64   `json:"buy_orders"`
	SellVolume  int64   `json:"sell_volume"`
	BuyVolume   int64   `json:"buy_volume"`
}

func (q *Queries) UpsertMarketRegionStatDaily(ctx context.Context, arg UpsertMarketRegionStatDailyParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketRegionStatDaily,
		arg.RegionID,
		arg.TypeID,
		arg.Day,
		arg.BestSell,
		arg.TypicalSell,
		arg.SellBand,
		arg.BestBuy,
		arg.TypicalBuy,
		arg.BuyBand,
		arg.SellOrders,
		arg.BuyOrders,
		arg.SellVolume,
		arg.BuyVolume,
	)
	return err
}

const upsertMarketStationStat = `-- name: UpsertMarketStationStat :exec
INSERT INTO market_station_stats (location_id, region_id, type_id, best_sell, best_buy, sell_orders, buy_orders, sell_volume, buy_volume, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (location_id, type_id) DO UPDATE SET
    region_id   = excluded.region_id,
    best_sell   = excluded.best_sell,
    best_buy    = excluded.best_buy,
    sell_orders = excluded.sell_orders,
    buy_orders  = excluded.buy_orders,
    sell_volume = excluded.sell_volume,
    buy_volume  = excluded.buy_volume,
    updated_at  = excluded.updated_at
`

type UpsertMarketStationStatParams struct {
	LocationID int64   `json:"location_id"`
	RegionID   int64   `json:"region_id"`
	TypeID     int64   `json:"type_id"`
	BestSell   float64 `json:"best_sell"`
	BestBuy    float64 `json:"best_buy"`
	SellOrders int64   `json:"sell_orders"`
	BuyOrders  int64   `json:"buy_orders"`
	SellVolume int64   `json:"sell_volume"`
	BuyVolume  int64   `json:"buy_volume"`
	UpdatedAt  string  `json:"updated_at"`
}

func (q *Queries) UpsertMarketStationStat(ctx context.Context, arg UpsertMarketStationStatParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketStationStat,
		arg.LocationID,
		arg.RegionID,
		arg.TypeID,
		arg.BestSell,
		arg.BestBuy,
		arg.SellOrders,
		arg.BuyOrders,
		arg.SellVolume,
		arg.BuyVolume,
		arg.UpdatedAt,
	)
	return err
}

const upsertOrderHealth = `-- name: UpsertOrderHealth :exec
INSERT INTO order_health (character_id, order_id, type_id, region_id, location_id, my_price, station_best, region_best, status, computed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (character_id, order_id) DO UPDATE SET
    type_id      = excluded.type_id,
    region_id    = excluded.region_id,
    location_id  = excluded.location_id,
    my_price     = excluded.my_price,
    station_best = excluded.station_best,
    region_best  = excluded.region_best,
    status       = excluded.status,
    computed_at  = excluded.computed_at
`

type UpsertOrderHealthParams struct {
	CharacterID int64   `json:"character_id"`
	OrderID     int64   `json:"order_id"`
	TypeID      int64   `json:"type_id"`
	RegionID    int64   `json:"region_id"`
	LocationID  int64   `json:"location_id"`
	MyPrice     float64 `json:"my_price"`
	StationBest float64 `json:"station_best"`
	RegionBest  float64 `json:"region_best"`
	Status      string  `json:"status"`
	ComputedAt  string  `json:"computed_at"`
}

func (q *Queries) UpsertOrderHealth(ctx context.Context, arg UpsertOrderHealthParams) error {
	_, err := q.db.ExecContext(ctx, upsertOrderHealth,
		arg.CharacterID,
		arg.OrderID,
		arg.TypeID,
		arg.RegionID,
		arg.LocationID,
		arg.MyPrice,
		arg.StationBest,
		arg.RegionBest,
		arg.Status,
		arg.ComputedAt,
	)
	return err
}

const upsertOrderLifecycle = `-- name: UpsertOrderLifecycle :exec
INSERT INTO order_lifecycle (character_id, order_id, type_id, location_id, region_id, is_buy_order, listed_price, volume_total, volume_remain_last, first_seen_at, last_seen_at, closed_at, close_kind, outbid_events, beaten_now)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '', '', 0, 0)
ON CONFLICT (character_id, order_id) DO UPDATE SET
    type_id            = excluded.type_id,
    location_id        = excluded.location_id,
    region_id          = excluded.region_id,
    is_buy_order       = excluded.is_buy_order,
    listed_price       = excluded.listed_price,
    volume_total       = excluded.volume_total,
    volume_remain_last = excluded.volume_remain_last,
    last_seen_at       = excluded.last_seen_at
`

type UpsertOrderLifecycleParams struct {
	CharacterID      int64   `json:"character_id"`
	OrderID          int64   `json:"order_id"`
	TypeID           int64   `json:"type_id"`
	LocationID       int64   `json:"location_id"`
	RegionID         int64   `json:"region_id"`
	IsBuyOrder       int64   `json:"is_buy_order"`
	ListedPrice      float64 `json:"listed_price"`
	VolumeTotal      int64   `json:"volume_total"`
	VolumeRemainLast int64   `json:"volume_remain_last"`
	FirstSeenAt      string  `json:"first_seen_at"`
	LastSeenAt       string  `json:"last_seen_at"`
}

func (q *Queries) UpsertOrderLifecycle(ctx context.Context, arg UpsertOrderLifecycleParams) error {
	_, err := q.db.ExecContext(ctx, upsertOrderLifecycle,
		arg.CharacterID,
		arg.OrderID,
		arg.TypeID,
		arg.LocationID,
		arg.RegionID,
		arg.IsBuyOrder,
		arg.ListedPrice,
		arg.VolumeTotal,
		arg.VolumeRemainLast,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	return err
}

const upsertPilotNameWant = `-- name: UpsertPilotNameWant :exec
INSERT OR IGNORE INTO pilot_name_wants (normalized_name, display_name, state, requested_at)
VALUES (?, ?, 'pending', ?)
`

type UpsertPilotNameWantParams struct {
	NormalizedName string `json:"normalized_name"`
	DisplayName    string `json:"display_name"`
	RequestedAt    string `json:"requested_at"`
}

func (q *Queries) UpsertPilotNameWant(ctx context.Context, arg UpsertPilotNameWantParams) error {
	_, err := q.db.ExecContext(ctx, upsertPilotNameWant, arg.NormalizedName, arg.DisplayName, arg.RequestedAt)
	return err
}

const upsertPilotWant = `-- name: UpsertPilotWant :exec
INSERT INTO pilot_records (character_id, priority)
VALUES (?, 1)
ON CONFLICT (character_id) DO UPDATE SET priority = MAX(priority, 1)
`

func (q *Queries) UpsertPilotWant(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, upsertPilotWant, characterID)
	return err
}

const upsertPlanetSeen = `-- name: UpsertPlanetSeen :exec
INSERT OR IGNORE INTO planet_names (planet_id)
VALUES (?)
`

func (q *Queries) UpsertPlanetSeen(ctx context.Context, planetID int64) error {
	_, err := q.db.ExecContext(ctx, upsertPlanetSeen, planetID)
	return err
}

const upsertStructureSeen = `-- name: UpsertStructureSeen :exec
INSERT OR IGNORE INTO structure_names (structure_id)
VALUES (?)
`

func (q *Queries) UpsertStructureSeen(ctx context.Context, structureID int64) error {
	_, err := q.db.ExecContext(ctx, upsertStructureSeen, structureID)
	return err
}

const upsertWatchlistEntry = `-- name: UpsertWatchlistEntry :exec
INSERT INTO market_watchlist (user_id, type_id, region_id, threshold_pct, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (user_id, type_id, region_id) DO UPDATE SET
    threshold_pct = excluded.threshold_pct
`

type UpsertWatchlistEntryParams struct {
	UserID       int64   `json:"user_id"`
	TypeID       int64   `json:"type_id"`
	RegionID     int64   `json:"region_id"`
	ThresholdPct float64 `json:"threshold_pct"`
	CreatedAt    string  `json:"created_at"`
}

func (q *Queries) UpsertWatchlistEntry(ctx context.Context, arg UpsertWatchlistEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertWatchlistEntry,
		arg.UserID,
		arg.TypeID,
		arg.RegionID,
		arg.ThresholdPct,
		arg.CreatedAt,
	)
	return err
}
