-- EveSynapse Postgres baseline (schema_pg/001).
-- The one-time collapse of the 35 SQLite migrations (internal/app/schema)
-- into a single Postgres schema: INTEGER -> BIGINT and REAL -> DOUBLE
-- PRECISION throughout so the sqlc-generated Go models keep today's
-- int64/float64/string types; every timestamp stays TEXT (app-written
-- RFC3339 strings, zero conversion); users/local_fittings/skill_plans
-- ids are identity columns (GENERATED BY DEFAULT so the migrator can
-- insert existing ids); order_lifecycle gains a surrogate identity
-- column for its retention prune. Applied by openDB when the users
-- table is absent; future schema changes land as new numbered files
-- in this directory.
CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')), home_layout TEXT NOT NULL DEFAULT '', last_briefing_at TEXT NOT NULL DEFAULT '');
CREATE TABLE characters (character_id BIGINT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE, name TEXT NOT NULL DEFAULT '', access_token TEXT NOT NULL DEFAULT '', refresh_token TEXT NOT NULL DEFAULT '', token_expiry TEXT, scopes TEXT NOT NULL DEFAULT '', cached_until TEXT, created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')), updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')), owner_hash TEXT NOT NULL DEFAULT '', tags TEXT NOT NULL DEFAULT '', link_state TEXT NOT NULL DEFAULT 'ok', link_state_at TEXT);
CREATE TABLE character_snapshots (character_id BIGINT NOT NULL REFERENCES characters (character_id) ON DELETE CASCADE, kind TEXT NOT NULL, payload TEXT NOT NULL, fetched_at TEXT NOT NULL, cached_until TEXT, PRIMARY KEY (character_id, kind));
CREATE TABLE type_names (type_id BIGINT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE sde_types (type_id BIGINT PRIMARY KEY, name TEXT NOT NULL, group_id BIGINT NOT NULL DEFAULT 0, market_group_id BIGINT NOT NULL DEFAULT 0, published BIGINT NOT NULL DEFAULT 1, description TEXT NOT NULL DEFAULT '');
CREATE TABLE sde_groups (group_id BIGINT PRIMARY KEY, name TEXT NOT NULL, category_id BIGINT NOT NULL DEFAULT 0);
CREATE TABLE sde_categories (category_id BIGINT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE sde_stations (station_id BIGINT PRIMARY KEY, name TEXT NOT NULL, system_id BIGINT NOT NULL DEFAULT 0);
CREATE TABLE sde_systems (system_id BIGINT PRIMARY KEY, name TEXT NOT NULL, region_id BIGINT NOT NULL DEFAULT 0, security DOUBLE PRECISION NOT NULL DEFAULT 0);
CREATE TABLE sde_regions (region_id BIGINT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE sde_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL DEFAULT '');
CREATE TABLE killmail_details (killmail_id BIGINT PRIMARY KEY, character_id BIGINT NOT NULL REFERENCES characters (character_id) ON DELETE CASCADE, hash TEXT NOT NULL, payload TEXT NOT NULL, fetched_at TEXT NOT NULL);
CREATE TABLE snapshot_fetch_state (character_id BIGINT NOT NULL REFERENCES characters (character_id) ON DELETE CASCADE, kind TEXT NOT NULL, state TEXT NOT NULL, detail TEXT NOT NULL DEFAULT '', attempted_at TEXT NOT NULL, PRIMARY KEY (character_id, kind));
CREATE TABLE character_corporations (character_id BIGINT PRIMARY KEY REFERENCES characters (character_id) ON DELETE CASCADE, corporation_id BIGINT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE item_names (item_id BIGINT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE contract_details (contract_id BIGINT PRIMARY KEY, character_id BIGINT NOT NULL REFERENCES characters (character_id) ON DELETE CASCADE, payload TEXT NOT NULL, fetched_at TEXT NOT NULL);
CREATE TABLE global_snapshots (kind TEXT PRIMARY KEY, payload TEXT NOT NULL, fetched_at TEXT NOT NULL, cached_until TEXT NOT NULL);
CREATE TABLE war_details (war_id BIGINT PRIMARY KEY, payload TEXT NOT NULL, fetched_at TEXT NOT NULL);
CREATE TABLE sde_blueprints (blueprint_type_id BIGINT PRIMARY KEY, product_type_id BIGINT NOT NULL, product_quantity BIGINT NOT NULL DEFAULT 1, max_production_limit BIGINT NOT NULL DEFAULT 0, manufacturing_time_seconds BIGINT NOT NULL DEFAULT 0);
CREATE TABLE sde_blueprint_materials (blueprint_type_id BIGINT NOT NULL, material_type_id BIGINT NOT NULL, quantity BIGINT NOT NULL, PRIMARY KEY (blueprint_type_id, material_type_id));
CREATE TABLE sde_blueprint_skills (blueprint_type_id BIGINT NOT NULL, skill_type_id BIGINT NOT NULL, level BIGINT NOT NULL, PRIMARY KEY (blueprint_type_id, skill_type_id));
CREATE TABLE sde_skill_meta (type_id BIGINT PRIMARY KEY, rank DOUBLE PRECISION NOT NULL DEFAULT 1, primary_attr BIGINT NOT NULL DEFAULT 0, secondary_attr BIGINT NOT NULL DEFAULT 0);
CREATE TABLE sde_requirements (type_id BIGINT NOT NULL, skill_type_id BIGINT NOT NULL, level BIGINT NOT NULL, PRIMARY KEY (type_id, skill_type_id));
CREATE TABLE skill_plans (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE, character_id BIGINT NOT NULL REFERENCES characters (character_id) ON DELETE CASCADE, name TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE skill_plan_items (plan_id BIGINT NOT NULL REFERENCES skill_plans (id) ON DELETE CASCADE, skill_type_id BIGINT NOT NULL, target_level BIGINT NOT NULL, position BIGINT NOT NULL, PRIMARY KEY (plan_id, skill_type_id));
CREATE TABLE market_history (region_id BIGINT NOT NULL, type_id BIGINT NOT NULL, date TEXT NOT NULL, average DOUBLE PRECISION NOT NULL DEFAULT 0, highest DOUBLE PRECISION NOT NULL DEFAULT 0, lowest DOUBLE PRECISION NOT NULL DEFAULT 0, volume BIGINT NOT NULL DEFAULT 0, order_count BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (region_id, type_id, date));
CREATE TABLE market_history_wants (region_id BIGINT NOT NULL, type_id BIGINT NOT NULL, last_requested_at TEXT NOT NULL, PRIMARY KEY (region_id, type_id));
CREATE TABLE market_fetch_state (kind TEXT PRIMARY KEY, state TEXT NOT NULL, detail TEXT NOT NULL DEFAULT '', attempted_at TEXT NOT NULL);
CREATE TABLE market_watchlist (user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE, type_id BIGINT NOT NULL, region_id BIGINT NOT NULL DEFAULT 10000002, threshold_pct DOUBLE PRECISION NOT NULL DEFAULT 5, created_at TEXT NOT NULL, PRIMARY KEY (user_id, type_id, region_id));
CREATE TABLE order_health (character_id BIGINT NOT NULL REFERENCES characters (character_id) ON DELETE CASCADE, order_id BIGINT NOT NULL, type_id BIGINT NOT NULL, region_id BIGINT NOT NULL, location_id BIGINT NOT NULL, my_price DOUBLE PRECISION NOT NULL, station_best DOUBLE PRECISION NOT NULL DEFAULT 0, region_best DOUBLE PRECISION NOT NULL DEFAULT 0, status TEXT NOT NULL, computed_at TEXT NOT NULL, PRIMARY KEY (character_id, order_id));
CREATE TABLE structure_names (structure_id BIGINT PRIMARY KEY, name TEXT NOT NULL DEFAULT '', state TEXT NOT NULL DEFAULT 'pending', resolved_at TEXT NOT NULL DEFAULT '', source TEXT NOT NULL DEFAULT 'esi');
CREATE TABLE pilot_records (character_id BIGINT PRIMARY KEY, payload TEXT NOT NULL DEFAULT '', state TEXT NOT NULL DEFAULT 'pending', fetched_at TEXT NOT NULL DEFAULT '', priority BIGINT NOT NULL DEFAULT 0);
CREATE TABLE type_details (type_id BIGINT PRIMARY KEY, description TEXT NOT NULL DEFAULT '', fetched_at TEXT NOT NULL DEFAULT '');
CREATE TABLE wallet_history (user_id BIGINT NOT NULL, character_id BIGINT NOT NULL, day TEXT NOT NULL, balance DOUBLE PRECISION NOT NULL, net_worth DOUBLE PRECISION, sampled_at TEXT NOT NULL, PRIMARY KEY (user_id, character_id, day));
CREATE TABLE widget_configs (user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE, widget_id TEXT NOT NULL, config TEXT NOT NULL DEFAULT '{}', updated_at TEXT NOT NULL, PRIMARY KEY (user_id, widget_id));
CREATE TABLE guide_prices (type_id BIGINT PRIMARY KEY, adjusted_price DOUBLE PRECISION NOT NULL DEFAULT 0, average_price DOUBLE PRECISION NOT NULL DEFAULT 0);
CREATE TABLE guide_prices_meta (id BIGINT PRIMARY KEY CHECK (id = 1), fetched_at TEXT NOT NULL DEFAULT '', cached_until TEXT NOT NULL DEFAULT '');
CREATE TABLE pilot_name_wants (normalized_name TEXT PRIMARY KEY, display_name TEXT NOT NULL DEFAULT '', state TEXT NOT NULL DEFAULT 'pending', character_id BIGINT NOT NULL DEFAULT 0, requested_at TEXT NOT NULL DEFAULT '', resolved_at TEXT NOT NULL DEFAULT '', next_try_at TEXT NOT NULL DEFAULT '', attempts BIGINT NOT NULL DEFAULT 0);
CREATE TABLE sde_market_groups (market_group_id BIGINT PRIMARY KEY, parent_group_id BIGINT NOT NULL DEFAULT 0, name TEXT NOT NULL, icon_id BIGINT NOT NULL DEFAULT 0, has_types BIGINT NOT NULL DEFAULT 0);
CREATE TABLE planet_names (planet_id BIGINT PRIMARY KEY, name TEXT NOT NULL DEFAULT '', state TEXT NOT NULL DEFAULT 'pending', resolved_at TEXT NOT NULL DEFAULT '');
CREATE TABLE corporation_records (corporation_id BIGINT PRIMARY KEY, payload TEXT NOT NULL DEFAULT '', state TEXT NOT NULL DEFAULT 'pending', fetched_at TEXT NOT NULL DEFAULT '', priority BIGINT NOT NULL DEFAULT 0);
CREATE TABLE alliance_records (alliance_id BIGINT PRIMARY KEY, payload TEXT NOT NULL DEFAULT '', state TEXT NOT NULL DEFAULT 'pending', fetched_at TEXT NOT NULL DEFAULT '', priority BIGINT NOT NULL DEFAULT 0);
CREATE TABLE guide_price_wants (id BIGINT PRIMARY KEY CHECK (id = 1), wanted_at TEXT NOT NULL DEFAULT '');
CREATE TABLE structure_context (structure_id BIGINT PRIMARY KEY, owner_corporation_id BIGINT NOT NULL DEFAULT 0, system_id BIGINT NOT NULL DEFAULT 0, type_id BIGINT NOT NULL DEFAULT 0, updated_at TEXT NOT NULL DEFAULT '');
CREATE TABLE sde_type_attributes (type_id BIGINT NOT NULL, attribute_id BIGINT NOT NULL, value DOUBLE PRECISION NOT NULL DEFAULT 0, PRIMARY KEY (type_id, attribute_id));
CREATE TABLE sde_attribute_types (attribute_id BIGINT PRIMARY KEY, name TEXT NOT NULL DEFAULT '', stackable BIGINT NOT NULL DEFAULT 1, high_is_good BIGINT NOT NULL DEFAULT 1, unit_id BIGINT NOT NULL DEFAULT 0, default_value DOUBLE PRECISION NOT NULL DEFAULT 0);
CREATE TABLE sde_effects (effect_id BIGINT PRIMARY KEY, name TEXT NOT NULL DEFAULT '', category BIGINT NOT NULL DEFAULT 0);
CREATE TABLE sde_effect_modifiers (effect_id BIGINT NOT NULL, domain TEXT NOT NULL DEFAULT '', func TEXT NOT NULL DEFAULT '', modified_attr BIGINT NOT NULL DEFAULT 0, modifying_attr BIGINT NOT NULL DEFAULT 0, operation BIGINT NOT NULL DEFAULT 0, group_id BIGINT NOT NULL DEFAULT 0, skill_type_id BIGINT NOT NULL DEFAULT 0);
CREATE TABLE sde_type_effects (type_id BIGINT NOT NULL, effect_id BIGINT NOT NULL, is_default BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (type_id, effect_id));
CREATE TABLE sde_type_physics (type_id BIGINT PRIMARY KEY, mass DOUBLE PRECISION NOT NULL DEFAULT 0, volume DOUBLE PRECISION NOT NULL DEFAULT 0, capacity DOUBLE PRECISION NOT NULL DEFAULT 0);
CREATE TABLE local_fittings (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, name TEXT NOT NULL DEFAULT '', ship_type_id BIGINT NOT NULL DEFAULT 0, items_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL DEFAULT '');
CREATE TABLE market_region_stats (region_id BIGINT NOT NULL, type_id BIGINT NOT NULL, best_sell DOUBLE PRECISION NOT NULL DEFAULT 0, typical_sell DOUBLE PRECISION NOT NULL DEFAULT 0, sell_band DOUBLE PRECISION NOT NULL DEFAULT 0, best_buy DOUBLE PRECISION NOT NULL DEFAULT 0, typical_buy DOUBLE PRECISION NOT NULL DEFAULT 0, buy_band DOUBLE PRECISION NOT NULL DEFAULT 0, sell_orders BIGINT NOT NULL DEFAULT 0, buy_orders BIGINT NOT NULL DEFAULT 0, sell_volume BIGINT NOT NULL DEFAULT 0, buy_volume BIGINT NOT NULL DEFAULT 0, updated_at TEXT NOT NULL DEFAULT '', PRIMARY KEY (region_id, type_id), avg_daily_volume DOUBLE PRECISION NOT NULL DEFAULT 0);
CREATE TABLE market_region_stats_daily (region_id BIGINT NOT NULL, type_id BIGINT NOT NULL, day TEXT NOT NULL, best_sell DOUBLE PRECISION NOT NULL DEFAULT 0, typical_sell DOUBLE PRECISION NOT NULL DEFAULT 0, sell_band DOUBLE PRECISION NOT NULL DEFAULT 0, best_buy DOUBLE PRECISION NOT NULL DEFAULT 0, typical_buy DOUBLE PRECISION NOT NULL DEFAULT 0, buy_band DOUBLE PRECISION NOT NULL DEFAULT 0, sell_orders BIGINT NOT NULL DEFAULT 0, buy_orders BIGINT NOT NULL DEFAULT 0, sell_volume BIGINT NOT NULL DEFAULT 0, buy_volume BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (region_id, type_id, day));
CREATE TABLE market_station_stats (location_id BIGINT NOT NULL, region_id BIGINT NOT NULL, type_id BIGINT NOT NULL, best_sell DOUBLE PRECISION NOT NULL DEFAULT 0, best_buy DOUBLE PRECISION NOT NULL DEFAULT 0, sell_orders BIGINT NOT NULL DEFAULT 0, buy_orders BIGINT NOT NULL DEFAULT 0, sell_volume BIGINT NOT NULL DEFAULT 0, buy_volume BIGINT NOT NULL DEFAULT 0, updated_at TEXT NOT NULL DEFAULT '', PRIMARY KEY (location_id, type_id));
CREATE TABLE order_lifecycle (id BIGINT GENERATED ALWAYS AS IDENTITY, character_id BIGINT NOT NULL REFERENCES characters (character_id) ON DELETE CASCADE, order_id BIGINT NOT NULL, type_id BIGINT NOT NULL, location_id BIGINT NOT NULL, region_id BIGINT NOT NULL, is_buy_order BIGINT NOT NULL DEFAULT 0, listed_price DOUBLE PRECISION NOT NULL DEFAULT 0, volume_total BIGINT NOT NULL DEFAULT 0, volume_remain_last BIGINT NOT NULL DEFAULT 0, first_seen_at TEXT NOT NULL DEFAULT '', last_seen_at TEXT NOT NULL DEFAULT '', closed_at TEXT NOT NULL DEFAULT '', close_kind TEXT NOT NULL DEFAULT '', outbid_events BIGINT NOT NULL DEFAULT 0, beaten_now BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (character_id, order_id));
CREATE TABLE market_sweep_state (region_id BIGINT NOT NULL, next_page BIGINT NOT NULL DEFAULT 1, pages_total BIGINT NOT NULL DEFAULT 0, started_at TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL DEFAULT '', PRIMARY KEY (region_id));
CREATE TABLE market_sweep_orders (region_id BIGINT NOT NULL, type_id BIGINT NOT NULL, is_buy_order BIGINT NOT NULL DEFAULT 0, price DOUBLE PRECISION NOT NULL DEFAULT 0, volume_remain BIGINT NOT NULL DEFAULT 0, location_id BIGINT NOT NULL DEFAULT 0);
CREATE INDEX idx_characters_user_id ON characters (user_id);
CREATE INDEX idx_sde_types_name ON sde_types (name);
CREATE INDEX idx_sde_types_marketable ON sde_types (market_group_id, published, name);
CREATE INDEX idx_sde_blueprints_product ON sde_blueprints (product_type_id);
CREATE INDEX idx_sde_requirements_skill ON sde_requirements (skill_type_id);
CREATE INDEX idx_skill_plans_user_char ON skill_plans (user_id, character_id);
CREATE INDEX idx_sde_market_groups_parent ON sde_market_groups (parent_group_id, name);
CREATE INDEX idx_sde_market_groups_name ON sde_market_groups (name);
CREATE INDEX idx_sde_type_attributes_attr ON sde_type_attributes (attribute_id, type_id);
CREATE INDEX idx_sde_effect_modifiers_effect ON sde_effect_modifiers (effect_id);
CREATE INDEX idx_sde_type_effects_effect ON sde_type_effects (effect_id);
CREATE INDEX idx_local_fittings_user ON local_fittings (user_id, updated_at DESC, id DESC);
CREATE INDEX idx_market_region_stats_type ON market_region_stats (type_id, region_id);
CREATE INDEX idx_market_station_stats_region ON market_station_stats (region_id, type_id);
CREATE INDEX idx_market_station_stats_type ON market_station_stats (type_id, region_id);
CREATE INDEX idx_order_lifecycle_character_closed ON order_lifecycle (character_id, closed_at);
CREATE INDEX idx_market_sweep_orders_agg ON market_sweep_orders (region_id, type_id, is_buy_order, price);

-- Session store for scs/pgxstore (it does not create its own table).
CREATE TABLE sessions (
    token TEXT PRIMARY KEY,
    data BYTEA NOT NULL,
    expiry TIMESTAMPTZ NOT NULL
);
CREATE INDEX sessions_expiry_idx ON sessions (expiry);
CREATE INDEX order_lifecycle_id_idx ON order_lifecycle (id);
