-- Schema step 012: notifications.
--
-- The worker already sees the things worth telling a user about (a
-- skill finishing, new mail, an extractor stopping). Until now it
-- only stored the data; the home briefing worked the news out again
-- on every render and nothing remembered what had been said.
--
-- notifications is what the user is shown: one row per thing that
-- happened, unread until they act on it.
--
-- notification_seen is the worker's memory of what it has already
-- considered, one key per event, so an event is announced once. It
-- is kept apart from notifications because the two have different
-- lives: a notification is deleted when the user clears it, while
-- the fact that the event was seen must outlast that, and an event
-- for a kind the user has switched off is seen without ever being
-- shown.

CREATE TABLE IF NOT EXISTS notifications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    character_id BIGINT NOT NULL DEFAULT 0,
    kind         TEXT NOT NULL,
    title        TEXT NOT NULL,
    url          TEXT NOT NULL DEFAULT '',
    created_at   timestamptz NOT NULL DEFAULT now(),
    read_at      timestamptz
);

CREATE INDEX IF NOT EXISTS notifications_user_unread ON notifications (user_id, kind) WHERE read_at IS NULL;
CREATE INDEX IF NOT EXISTS notifications_user_recent ON notifications (user_id, id DESC);

CREATE TABLE IF NOT EXISTS notification_seen (
    user_id   BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    event_key TEXT NOT NULL,
    seen_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, event_key)
);
