-- Schema step 013: browser push subscriptions.
--
-- A browser that the user has asked to receive notifications hands
-- over the address of its push service, a public key and a secret.
-- One row per browser. The endpoint identifies the browser, so it is
-- unique across accounts: a browser belongs to whoever subscribed it
-- last.
--
-- failures counts sends refused in a row, so that a subscription a
-- push service keeps rejecting is dropped instead of retried for ever.

CREATE TABLE IF NOT EXISTS push_subscriptions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    endpoint   TEXT NOT NULL UNIQUE,
    p256dh     TEXT NOT NULL,
    auth       TEXT NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_ok_at timestamptz,
    failures   BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS push_subscriptions_user ON push_subscriptions (user_id);
