-- Schema step 014: ops, EveSynapse's own calendar entries.
--
-- An op is a planned fleet for one corporation: when, how long, what
-- to bring, where to form up, and who is running it. Members with a
-- character in that corporation see it on the calendar beside their
-- in-game events and sign up to it.
--
-- op_signups is one answer per character: coming, maybe or not, and
-- for those coming, the ship and the part they will play. A
-- character signs up, not an account, because it is the character
-- that will be in the fleet.

CREATE TABLE IF NOT EXISTS ops (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporation_id       BIGINT NOT NULL,
    title                TEXT NOT NULL,
    description          TEXT NOT NULL DEFAULT '',
    starts_at            timestamptz NOT NULL,
    duration_minutes     BIGINT NOT NULL DEFAULT 60,
    doctrine             TEXT NOT NULL DEFAULT '',
    form_up              TEXT NOT NULL DEFAULT '',
    fc_character_id      BIGINT NOT NULL DEFAULT 0,
    created_by_character BIGINT NOT NULL DEFAULT 0,
    created_at           timestamptz NOT NULL DEFAULT now(),
    cancelled_at         timestamptz
);

CREATE INDEX IF NOT EXISTS ops_corporation_start ON ops (corporation_id, starts_at);

CREATE TABLE IF NOT EXISTS op_signups (
    op_id        BIGINT NOT NULL REFERENCES ops (id) ON DELETE CASCADE,
    character_id BIGINT NOT NULL,
    user_id      BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    response     TEXT NOT NULL,
    ship         TEXT NOT NULL DEFAULT '',
    fleet_role   TEXT NOT NULL DEFAULT '',
    note         TEXT NOT NULL DEFAULT '',
    updated_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (op_id, character_id)
);
