-- Schema step 019: any number of Discord roles per server, and groups.
--
-- A server had two role settings (017): one for everyone connected,
-- one for members. Directors want as many as they have roles to give:
-- CEO, directors, members, the holders of an in-game role, the members
-- of a group they keep themselves. So a server now has rules, each
-- saying "whoever is this gets that role", and a member gets every
-- role they qualify for.
--
-- discord_role_rules.kind, and what ref holds:
--
--   linked    anyone connected with a working character       ref ''
--   member    a character in the owner (corporation, or a
--             corporation of the alliance)                     ref ''
--   corp      a character in one corporation                   ref corporation id
--   ceo       the CEO of the owner corporation, or of a
--             corporation of the owner alliance                ref ''
--   eve_role  holds an in-game corporation role there          ref the role, as ESI names it
--   group     a character in one of the owner's groups         ref group id

CREATE TABLE IF NOT EXISTS discord_role_rules (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id   TEXT NOT NULL REFERENCES discord_guilds (guild_id) ON DELETE CASCADE,
    kind       TEXT NOT NULL CHECK (kind IN ('linked', 'member', 'corp', 'ceo', 'eve_role', 'group')),
    ref        TEXT NOT NULL DEFAULT '',
    role_id    TEXT NOT NULL,
    created_by BIGINT NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (guild_id, kind, ref, role_id)
);

CREATE INDEX IF NOT EXISTS discord_role_rules_guild ON discord_role_rules (guild_id);

-- The two settings of 017 become rules. The columns stay where they
-- are and are no longer read.
INSERT INTO discord_role_rules (guild_id, kind, ref, role_id, created_by)
SELECT guild_id, 'linked', '', role_linked, added_by FROM discord_guilds WHERE role_linked <> ''
ON CONFLICT DO NOTHING;

INSERT INTO discord_role_rules (guild_id, kind, ref, role_id, created_by)
SELECT guild_id, 'member', '', role_member, added_by FROM discord_guilds WHERE role_member <> ''
ON CONFLICT DO NOTHING;

-- Groups: sets of characters that the directors of a corporation or
-- alliance keep by hand (a special interest group, a fleet commander
-- list, a logistics wing). A group belongs to its owner the way a
-- server does. Membership is by character; a character that has since
-- left the owner stays listed but counts for nothing until it is back.

CREATE TABLE IF NOT EXISTS org_groups (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_kind  TEXT NOT NULL CHECK (owner_kind IN ('corporation', 'alliance')),
    owner_id    BIGINT NOT NULL,
    name        TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    created_by  BIGINT NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS org_groups_owner_name ON org_groups (owner_kind, owner_id, lower(name));

CREATE TABLE IF NOT EXISTS org_group_members (
    group_id     BIGINT NOT NULL REFERENCES org_groups (id) ON DELETE CASCADE,
    character_id BIGINT NOT NULL,
    added_by     BIGINT NOT NULL,
    added_at     timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (group_id, character_id)
);

CREATE INDEX IF NOT EXISTS org_group_members_character ON org_group_members (character_id);
