-- Schema step 025: ship replacement (SRP), and who runs a
-- corporation's programmes.
--
-- corp_permissions is the choice a corporation's directors make of
-- who, besides themselves and the CEO, may run one of its programmes
-- here (ship replacement is the first). One choice per programme, in
-- the terms of a Discord role rule: an in-game role, or one of the
-- corporation's groups.
--
-- An srp_request is a pilot asking for a lost ship to be replaced.
-- It names the killmail and the op the ship was lost on; a killmail
-- is claimed once. The loss value is the estimate at the time of
-- asking; the payout is what the handler says was paid.

CREATE TABLE IF NOT EXISTS corp_permissions (
    corporation_id BIGINT NOT NULL,
    permission     TEXT NOT NULL,
    kind           TEXT NOT NULL,
    ref            TEXT NOT NULL DEFAULT '',
    updated_by     BIGINT NOT NULL DEFAULT 0,
    updated_at     timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (corporation_id, permission)
);

CREATE TABLE IF NOT EXISTS srp_settings (
    corporation_id BIGINT PRIMARY KEY,
    policy         TEXT NOT NULL DEFAULT '',
    updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS srp_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporation_id  BIGINT NOT NULL,
    op_id           BIGINT NOT NULL REFERENCES ops (id) ON DELETE CASCADE,
    killmail_id     BIGINT NOT NULL UNIQUE,
    killmail_hash   TEXT NOT NULL DEFAULT '',
    character_id    BIGINT NOT NULL,
    user_id         BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    ship_type_id    BIGINT NOT NULL DEFAULT 0,
    solar_system_id BIGINT NOT NULL DEFAULT 0,
    lost_at         timestamptz NOT NULL,
    loss_value      DOUBLE PRECISION NOT NULL DEFAULT 0,
    note            TEXT NOT NULL DEFAULT '',
    status          TEXT NOT NULL DEFAULT 'open',
    payout          DOUBLE PRECISION NOT NULL DEFAULT 0,
    handled_by      BIGINT NOT NULL DEFAULT 0,
    handler_note    TEXT NOT NULL DEFAULT '',
    handled_at      timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS srp_requests_corporation ON srp_requests (corporation_id, status, created_at);
CREATE INDEX IF NOT EXISTS srp_requests_user ON srp_requests (user_id, created_at);
