-- Schema step 026: doctrines.
--
-- A doctrine is a corporation's named set of fits for a kind of
-- fleet, kept by its directors and whoever they hand it to. It has a
-- category and tags to find it by. A fit in a doctrine is a copy of
-- the fit document as it was when it was added: the doctrine does not
-- change when the fit it came from is edited, made private or deleted.
--
-- An op can name the doctrine it flies (ops.doctrine_id). The id is
-- not a reference: an op keeps the doctrine's name as text, and
-- outlives a doctrine that is deleted.

CREATE TABLE IF NOT EXISTS doctrines (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporation_id BIGINT NOT NULL,
    name           TEXT NOT NULL,
    category       TEXT NOT NULL DEFAULT '',
    description    TEXT NOT NULL DEFAULT '',
    tags           TEXT NOT NULL DEFAULT '',
    created_by     BIGINT NOT NULL DEFAULT 0,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS doctrines_corporation_name ON doctrines (corporation_id, lower(name));

CREATE TABLE IF NOT EXISTS doctrine_fits (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctrine_id  BIGINT NOT NULL REFERENCES doctrines (id) ON DELETE CASCADE,
    name         TEXT NOT NULL,
    ship_type_id BIGINT NOT NULL DEFAULT 0,
    items_json   TEXT NOT NULL DEFAULT '{}',
    fleet_role   TEXT NOT NULL DEFAULT '',
    note         TEXT NOT NULL DEFAULT '',
    added_by     BIGINT NOT NULL DEFAULT 0,
    added_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS doctrine_fits_doctrine ON doctrine_fits (doctrine_id, id);

ALTER TABLE ops ADD COLUMN IF NOT EXISTS doctrine_id BIGINT NOT NULL DEFAULT 0;
