-- Schema step 029: warming ahead of a page view, on something that
-- happened in the game.
--
-- A foresight target is one piece of data the worker expects an
-- account to look at soon, because of an event in its own records: a
-- character docked at a trade hub, an industry job is about to finish,
-- a market order was undercut, a skill queue ran out, a war was
-- declared on its corporation. Each row says what happened (once: the
-- event key), what to warm, the page that would use it (the view key),
-- when it was warmed and at what cost in ESI calls, and whether the
-- account then opened that page before the target expired.
--
-- The rows are also the record the worker learns from: how often a
-- kind of event is followed by the page being opened decides how much
-- of the fetch allowance that kind is worth.

CREATE TABLE IF NOT EXISTS foresight_targets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    character_id BIGINT NOT NULL DEFAULT 0,
    event_kind   TEXT NOT NULL,
    event_key    TEXT NOT NULL,
    target_kind  TEXT NOT NULL,
    subject_id   BIGINT NOT NULL DEFAULT 0,
    region_id    BIGINT NOT NULL DEFAULT 0,
    detail       TEXT NOT NULL DEFAULT '',
    view_key     TEXT NOT NULL,
    created_at   timestamptz NOT NULL,
    expires_at   timestamptz NOT NULL,
    warmed_at    timestamptz,
    calls        BIGINT NOT NULL DEFAULT 0,
    opened_at    timestamptz,
    UNIQUE (user_id, event_key, target_kind, subject_id, region_id, detail)
);

CREATE INDEX IF NOT EXISTS foresight_targets_pending ON foresight_targets (created_at) WHERE warmed_at IS NULL;
CREATE INDEX IF NOT EXISTS foresight_targets_view ON foresight_targets (user_id, view_key) WHERE opened_at IS NULL;
CREATE INDEX IF NOT EXISTS foresight_targets_created ON foresight_targets (created_at);
