bind = "127.0.0.1:29621"
workers = 17
worker_class = "gevent"
proc_name = "EveSynapse"

def def_post_fork(server, worker):
    import psycogreen.gevent
    psycogreen.gevent.patch_psycopg()
    worker.log.info("Made Psycopg Green")

post_fork = def_post_fork