[program:memcached]
command=memcached -m 64 -s /home/makh/memcached.sock -P /home/makh/memcached.pid

[program:redis]
command=redis-server /home/makh/webapps/evesynapse_gunicorn/etc/redis.conf

[program:celery]
command=python /home/makh/webapps/evesynapse_gunicorn/evesynapse/manage.py celery worker -E -B --loglevel=INFO --autoscale=8,4 -n w1

[program:gunicorn]
command=gunicorn -c /home/makh/webapps/evesynapse_gunicorn/etc/gunicorn.conf core.wsgi:application

[supervisord]
loglevel = error
logfile_maxbytes = 1MB
logfile_backups = 0
pidfile = /home/makh/supervisord.pid
logfile = /home/makh/supervisord.log

[unix_http_server]
file = /home/makh/supervisord.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl = unix:///home/makh/supervisord.sock