-- ---------------------------------------------------------------------
-- Sold-per-day precompute (schema 035, web-tier scaling fix):
-- market_region_stats gains the 7-day average traded volume for
-- the (region, type), distilled from market_history by the sweep
-- at completion time. The spread scanner and tradefinder used to
-- recompute this per candidate type on every render (one history
-- query per type per viewer); now they read the stored figure,
-- exactly the platform's rule that aggregation happens at sweep
-- time, never at render time. 0 until the first sweep after this
-- column lands has covered the type (and for types with no
-- recorded history at all).
-- ---------------------------------------------------------------------
ALTER TABLE market_region_stats ADD COLUMN avg_daily_volume REAL NOT NULL DEFAULT 0;
