package app

// -migrate-pg: the one-time move of an existing SQLite-era
// database into Postgres (the v0.3.26 cutover). It opens the
// SQLite file read-only (never written, so rollback stays the
// previous binary + the old .env), creates/verifies the Postgres
// schema through the usual openDB path, copies every table in
// foreign-key-safe order, rewinds the identity sequences past
// the copied ids, and verifies per-table row counts plus a
// characters refresh-token spot check before it reports.
// Sessions are deliberately not migrated: everyone signs in once
// after the swap. Running it into a target that already holds
// rows is refused unless -force is given, in which case the
// target's tables are truncated first and re-copied.

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"os"
	"strings"

	_ "modernc.org/sqlite" // the migrator's read-only SQLite source driver
)

// pgMigrateTables is the copy list: every baseline table except
// sessions, in the baseline's own creation order so foreign keys
// resolve as rows land (users before characters, characters
// before everything that hangs off them).
var pgMigrateTables = []string{
	"users",
	"characters",
	"character_snapshots",
	"type_names",
	"sde_types",
	"sde_groups",
	"sde_categories",
	"sde_stations",
	"sde_systems",
	"sde_regions",
	"sde_meta",
	"killmail_details",
	"snapshot_fetch_state",
	"character_corporations",
	"item_names",
	"contract_details",
	"global_snapshots",
	"war_details",
	"sde_blueprints",
	"sde_blueprint_materials",
	"sde_blueprint_skills",
	"sde_skill_meta",
	"sde_requirements",
	"skill_plans",
	"skill_plan_items",
	"market_history",
	"market_history_wants",
	"market_fetch_state",
	"market_watchlist",
	"order_health",
	"structure_names",
	"pilot_records",
	"type_details",
	"wallet_history",
	"widget_configs",
	"guide_prices",
	"guide_prices_meta",
	"pilot_name_wants",
	"sde_market_groups",
	"planet_names",
	"corporation_records",
	"alliance_records",
	"guide_price_wants",
	"structure_context",
	"sde_type_attributes",
	"sde_attribute_types",
	"sde_effects",
	"sde_effect_modifiers",
	"sde_type_effects",
	"sde_type_physics",
	"local_fittings",
	"market_region_stats",
	"market_region_stats_daily",
	"market_station_stats",
	"order_lifecycle",
	"market_sweep_state",
	"market_sweep_orders",
}

// pgIdentityTables are the tables whose single identity column
// needs its sequence rewound past the copied ids (the copy
// inserts existing ids into GENERATED BY DEFAULT columns).
var pgIdentityTables = []string{"users", "skill_plans", "local_fittings"}

// RunMigratePG implements `evesynapse -migrate-pg [-force]`
// [-sqlite path]: copy the SQLite database named by DB_PATH
// (or the flag) into the Postgres database named by
// DATABASE_URL. Exit codes: 0 copied and verified, 1 failure,
// 2 usage.
func RunMigratePG(args []string, cfg Config, stdout, stderr io.Writer) int {
	force := false
	sqlitePath := cfg.DBPath()
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "-force":
			force = true
		case "-sqlite":
			i++
			if i >= len(args) {
				fmt.Fprintln(stderr, "Usage: evesynapse -migrate-pg [-force] [-sqlite path]")
				return 2
			}
			sqlitePath = args[i]
		default:
			fmt.Fprintln(stderr, "Usage: evesynapse -migrate-pg [-force] [-sqlite path]")
			return 2
		}
	}
	if _, err := os.Stat(sqlitePath); err != nil {
		fmt.Fprintf(stderr, "No SQLite database found at %s — nothing to migrate.\n", sqlitePath)
		return 1
	}

	// Read-only open: the SQLite file is the rollback anchor and
	// is never written by the migration.
	src, err := sql.Open("sqlite", "file:"+sqlitePath+"?mode=ro")
	if err != nil {
		fmt.Fprintf(stderr, "Couldn't open the SQLite database: %v\n", err)
		return 1
	}
	defer src.Close()
	if err := src.Ping(); err != nil {
		fmt.Fprintf(stderr, "Couldn't open the SQLite database at %s: %v\n", sqlitePath, err)
		return 1
	}

	ctx := context.Background()
	dst, pool, err := openDB(ctx, cfg.DatabaseURL())
	if err != nil {
		fmt.Fprintf(stderr, "Couldn't open the Postgres database: %v\n", err)
		return 1
	}
	defer dst.Close()
	defer pool.Close()

	report, err := migrateSQLiteToPG(ctx, src, dst, force)
	for _, line := range report {
		fmt.Fprintln(stdout, line)
	}
	if err != nil {
		fmt.Fprintf(stderr, "The migration didn't finish: %v\n", err)
		return 1
	}
	return 0
}

// migrateSQLiteToPG performs the copy and returns the report
// lines (also returned on failure, so the caller prints what
// happened up to the error).
func migrateSQLiteToPG(ctx context.Context, src, dst *sql.DB, force bool) ([]string, error) {
	var report []string

	// Refuse a non-empty target unless forced: a second run
	// would collide on primary keys and confuse the counts.
	nonEmpty, err := pgTargetNonEmpty(ctx, dst)
	if err != nil {
		return report, err
	}
	if nonEmpty && !force {
		return report, fmt.Errorf("the Postgres database already holds EveSynapse rows; re-run with -force to truncate and re-copy")
	}
	if nonEmpty {
		report = append(report, "Target already held rows: truncating all tables (-force).")
		trunc := "TRUNCATE " + strings.Join(pgMigrateTables, ", ") + " RESTART IDENTITY CASCADE"
		if _, err := dst.ExecContext(ctx, trunc); err != nil {
			return report, fmt.Errorf("truncate target: %w", err)
		}
	}

	srcTables, err := sqliteTableSet(ctx, src)
	if err != nil {
		return report, err
	}

	var total int64
	for _, table := range pgMigrateTables {
		if !srcTables[table] {
			report = append(report, fmt.Sprintf("  %-28s skipped (absent in the SQLite database)", table))
			continue
		}
		n, err := copyTable(ctx, src, dst, table)
		if err != nil {
			return report, fmt.Errorf("copy %s: %w", table, err)
		}
		total += n
		report = append(report, fmt.Sprintf("  %-28s %d rows", table, n))
	}

	// Copied ids went into GENERATED BY DEFAULT identity columns;
	// rewind each sequence past the copied max so the next live
	// insert doesn't collide.
	for _, table := range pgIdentityTables {
		if _, err := dst.ExecContext(ctx,
			`SELECT setval(pg_get_serial_sequence($1, 'id'), COALESCE((SELECT MAX(id) FROM `+table+`), 1))`, table); err != nil {
			return report, fmt.Errorf("rewind %s sequence: %w", table, err)
		}
	}

	// Verification: per-table counts must match exactly, and a
	// sample of character refresh tokens must match byte-for-byte
	// (the fleet's sign-ins ride on them surviving).
	report = append(report, "Verification:")
	for _, table := range pgMigrateTables {
		if !srcTables[table] {
			continue
		}
		var srcN, dstN int64
		if err := src.QueryRowContext(ctx, "SELECT COUNT(*) FROM "+table).Scan(&srcN); err != nil {
			return report, fmt.Errorf("count source %s: %w", table, err)
		}
		if err := dst.QueryRowContext(ctx, "SELECT COUNT(*) FROM "+table).Scan(&dstN); err != nil {
			return report, fmt.Errorf("count target %s: %w", table, err)
		}
		if srcN != dstN {
			return report, fmt.Errorf("%s: %d rows in SQLite, %d in Postgres — counts differ, migration NOT verified", table, srcN, dstN)
		}
	}
	if err := verifyRefreshTokens(ctx, src, dst); err != nil {
		return report, err
	}
	report = append(report, "  row counts match on every table; character refresh tokens verified")
	report = append(report, fmt.Sprintf("Migrated %d rows. Sessions were not migrated — everyone signs in once on the new build.", total))
	return report, nil
}

// pgTargetNonEmpty reports whether any copied table in the
// target already holds rows.
func pgTargetNonEmpty(ctx context.Context, dst *sql.DB) (bool, error) {
	for _, table := range pgMigrateTables {
		var n int64
		if err := dst.QueryRowContext(ctx, "SELECT COUNT(*) FROM "+table).Scan(&n); err != nil {
			return false, fmt.Errorf("count target %s: %w", table, err)
		}
		if n > 0 {
			return true, nil
		}
	}
	return false, nil
}

func sqliteTableSet(ctx context.Context, src *sql.DB) (map[string]bool, error) {
	rows, err := src.QueryContext(ctx, `SELECT name FROM sqlite_master WHERE type = 'table'`)
	if err != nil {
		return nil, fmt.Errorf("list source tables: %w", err)
	}
	defer rows.Close()
	set := map[string]bool{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		set[name] = true
	}
	return set, rows.Err()
}

// copyTable streams one table from SQLite into Postgres through
// the target's own column list (columns the source lacks — the
// order_lifecycle id — are left to their defaults), in one
// transaction, in batches.
func copyTable(ctx context.Context, src, dst *sql.DB, table string) (int64, error) {
	cols, err := pgColumns(ctx, dst, table)
	if err != nil {
		return 0, err
	}
	srcCols, err := sqliteColumns(ctx, src, table)
	if err != nil {
		return 0, err
	}
	var use []string
	for _, c := range cols {
		if srcCols[c] {
			use = append(use, c)
		}
	}
	if len(use) == 0 {
		return 0, nil
	}

	placeholders := make([]string, len(use))
	for i := range placeholders {
		placeholders[i] = fmt.Sprintf("$%d", i+1)
	}
	insertSQL := "INSERT INTO " + table + " (" + strings.Join(use, ", ") +
		") VALUES (" + strings.Join(placeholders, ", ") + ")"

	rows, err := src.QueryContext(ctx, "SELECT "+strings.Join(use, ", ")+" FROM "+table)
	if err != nil {
		return 0, err
	}
	defer rows.Close()

	tx, err := dst.BeginTx(ctx, nil)
	if err != nil {
		return 0, err
	}
	defer tx.Rollback()
	stmt, err := tx.PrepareContext(ctx, insertSQL)
	if err != nil {
		return 0, err
	}
	defer stmt.Close()

	var copied int64
	for rows.Next() {
		vals := make([]any, len(use))
		dest := make([]any, len(use))
		for i := range vals {
			dest[i] = &vals[i]
		}
		if err := rows.Scan(dest...); err != nil {
			return 0, err
		}
		if _, err := stmt.ExecContext(ctx, vals...); err != nil {
			return 0, fmt.Errorf("row %d: %w", copied+1, err)
		}
		copied++
	}
	if err := rows.Err(); err != nil {
		return 0, err
	}
	if err := tx.Commit(); err != nil {
		return 0, err
	}
	return copied, nil
}

func pgColumns(ctx context.Context, db *sql.DB, table string) ([]string, error) {
	rows, err := db.QueryContext(ctx,
		`SELECT column_name FROM information_schema.columns
		  WHERE table_schema = 'public' AND table_name = $1
		  ORDER BY ordinal_position`, table)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var cols []string
	for rows.Next() {
		var c string
		if err := rows.Scan(&c); err != nil {
			return nil, err
		}
		cols = append(cols, c)
	}
	return cols, rows.Err()
}

func sqliteColumns(ctx context.Context, db *sql.DB, table string) (map[string]bool, error) {
	rows, err := db.QueryContext(ctx, `SELECT name FROM pragma_table_info(?)`, table)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	set := map[string]bool{}
	for rows.Next() {
		var c string
		if err := rows.Scan(&c); err != nil {
			return nil, err
		}
		set[c] = true
	}
	return set, rows.Err()
}

// verifyRefreshTokens spot-checks the first few characters'
// refresh tokens byte-for-byte between source and target.
func verifyRefreshTokens(ctx context.Context, src, dst *sql.DB) error {
	rows, err := src.QueryContext(ctx,
		`SELECT character_id, refresh_token FROM characters ORDER BY character_id LIMIT 3`)
	if err != nil {
		return fmt.Errorf("read source refresh tokens: %w", err)
	}
	defer rows.Close()
	checked := 0
	for rows.Next() {
		var id int64
		var token string
		if err := rows.Scan(&id, &token); err != nil {
			return err
		}
		var got string
		if err := dst.QueryRowContext(ctx,
			`SELECT refresh_token FROM characters WHERE character_id = $1`, id).Scan(&got); err != nil {
			return fmt.Errorf("read migrated refresh token for character %d: %w", id, err)
		}
		if got != token {
			return fmt.Errorf("refresh token mismatch for character %d — migration NOT verified", id)
		}
		checked++
	}
	if err := rows.Err(); err != nil {
		return err
	}
	if checked == 0 {
		return fmt.Errorf("no characters in the source database to verify — migration NOT verified")
	}
	return nil
}
